
<!DOCTYPE html>
<html>
    <body>
    <center>
        <div class="content">
            <div class="top_content clear banner">
                <div style="position: absolute; top: 120px; right: 70px; ">
                    <a href="<?php echo $this->baseUrl(); ?>/user/logout"><font style="color: #7E3500; font-weight: bold; text-decoration: underline;">ログアウト</font>
                    </a>
                </div>
                <div  class="topbar-username"><big>ようこそ!</bigF><?php echo $this->user_info['name']; ?></div>
            </div>
            <big>

                <!--Menu Tab Bar-->
                <div class="menus clear">
                    <div class="mn">
                        <a class="home" href="<?php echo $this->baseUrl(); ?>/teacher/index">
                            <font style="color: white;">ホーム</font>
                        </a>
                    </div>
                    <div title="" class="mn"><a href="<?php echo $this->baseUrl(); ?>/teacher/myLesson"><font style="color: white;">マイレッスン</font></a>
                    </div>
                    <div title="" class="mn first_mn"><a href="<?php echo $this->baseUrl(); ?>/teacher/payment">
                            <font style="color: white;">支払い</font></a><font style="color: white;">
                        </font>
                    </div>
                    <font style="color: white;">
                    <div title="" class="mn "><a href="<?php echo $this->baseUrl(); ?>/teacher/profile"><font style="color: white;">プロファイル</font></a>
                    </div>
                    </font>
                </div>
                <form action="" method="post">
                    <div class="row-show" style="padding: 20px 0 20px 0">
                        <font style="text-align: center; color: #bb670a; font-size: 23px; width: 100%; float: left; margin-top: 20px;margin-bottom: 20px; font-weight: bold;">パスワード変更</font>
                        <table cellpadding="10" cellspacing="5" style="border-style: double; border-color: #093; width: 50%;">
                            <tr class="profile">
                                <td colspan="2"><font class="font-big font-bold">新しいパスワードを入力してください！<font></td>
                            </tr>

                            <tr class="profile">
                                <!--ユーザネーム-->
                                <td>
                                    <b>ユーザ名:</b>
                                </td>
                                <td>
                                    <input hidden name="username" value="<?php echo $this->user_info['username']; ?>">
                                    <font style="font-family: fantasy; font-size: 18px;">
                                    <?php echo $this->user_info['username']; ?>
                                    </font>
                                </td>
                            </tr>
                            <tr class = "profile">
                                <!--現在のパスワード-->
                                <td><b>現在パスワード<span class="red">(*)</span>：</b></td>
                                <td><input type="password" name="password" class="res_input"></td>
                            </tr>

                            <tr class = "profile">
                                <!--新しいパスワード-->
                                <td><b>新しいパスワード<span class="red">(*)</span>：</b></td>
                                <td><input type="password" name="new_password" class="res_input"></td>
                            </tr>

                            <tr class = "profile">
                                <!--新しいパスワードが確認-->
                                <td><b>新しいパスワード確認<span class="red">(*)</span>:</b></td>
                                <td><input type="password" name="new_password_confirm" class="res_input"></td>
                            </tr>
                            <tr>
                                <td colspan="2" style="text-align: center;">
                                    <font class="msg-error">
                                    <?php
                                    if (isset($this->errorMessage)) {
                                        echo $this->errorMessage;
                                    }
                                    ?>
                                    </font>
                                </td>
                            </tr>
                        </table>
                    </div>
                    <div style="width: 30%;">
                        <button type="submit" class="showlogfromm">更新</button>
                        <a href="../teacher/profile"><button class="register-cus" style="width: 130px;">キャンセル</button></a>
                    </div>
                </form>
        </div>
    </center>
</body>
</html>
