
<!DOCTYPE html>
<html>
    <body>
    <center>
        <div class="content">
            <?php 
                echo $this->partial("teacher/teacher-top.phtml", array('username'=>$this->user_info['name']));
            ?>
            <form action="" method="post">
                <div class="row-show" style="padding: 20px 0 20px 0">
                    <font style="text-align: center; color: #bb670a; font-size: 23px; width: 100%; float: left; margin-top: 20px;margin-bottom: 20px; font-weight: bold;">パスワード変更</font>
                    <table cellpadding="10" cellspacing="5" style="border-style: double; border-color: #093; width: 50%;">
                        <tr class="profile">
                            <td colspan="2"><font class="font-big font-bold">新しいパスワードを入力してください！<font></td>
                        </tr>

                        <tr class="profile">
                            <!--ユーザネーム-->
                            <td>
                                <b>ユーザ名:</b>
                            </td>
                            <td>
                                <input hidden name="username" value="<?php echo $this->user_info['username']; ?>">
                                <font style="font-family: fantasy; font-size: 18px;">
                                <?php echo $this->user_info['username']; ?>
                                </font>
                            </td>
                        </tr>
                        <tr class = "profile">
                            <!--現在のパスワード-->
                            <td><b>現在パスワード<span class="red">(*)</span>：</b></td>
                            <td><input type="password" name="password" class="res_input"></td>
                        </tr>

                        <tr class = "profile">
                            <!--新しいパスワード-->
                            <td><b>新しいパスワード<span class="red">(*)</span>：</b></td>
                            <td><input type="password" name="new_password" class="res_input"></td>
                        </tr>

                        <tr class = "profile">
                            <!--新しいパスワードが確認-->
                            <td><b>新しいパスワード確認<span class="red">(*)</span>:</b></td>
                            <td><input type="password" name="new_password_confirm" class="res_input"></td>
                        </tr>
                        <tr>
                            <td colspan="2" style="text-align: center;">
                                <font class="msg-error">
                                <?php
                                if (isset($this->errorMessage)) {
                                    echo $this->errorMessage;
                                }
                                ?>
                                </font>
                            </td>
                        </tr>
                    </table>
                </div>
                <div style="width: 30%;">
                    <button type="submit" class="showlogfromm">更新</button>
                    <a href="../teacher/profile"><button class="register-cus" style="width: 130px;">キャンセル</button></a>
                </div>
            </form>
        </div>
    </center>
</body>
</html>
