<style type="text/css">
    .visible {
        display: block;
    }
    .not_visible {
        display: none;
    }
    .res_input {
        width: 400px;
    }
    .lesson-dec, .file_dec {
        width: 400px;
        height: 100px;
    }
    .tag {
        background-color: yellowgreen;
        padding: 5px;
        margin: 0px 5px;
        border-radius: 2px;
        float: left;
    }
</style>
<?php $this->headScript()->appendFile($this->baseUrl('/public/js/jquery.min.js')); ?>
<script type="text/javascript">
    $(document).ready(function() {
        var fileCount = 0;
        $("#btn_add_tag").click(function() {
            if ($(".tag_input").val() !== "") {
                var tagCount = $(".tags_list").data("tag-count");
                var tagValue = $(".tag_input").val();
                $(".tags_list").append("<div class='tag'>" + tagValue + "</div>" +
                        "<input type='hidden' name='tags[" + tagCount + "]' class='tag_hidden' value='" + tagValue + "'>");
                tagCount++;
                $(".tags_list").data("tag-count", tagCount);
                $(".tag_input").val("");
            }

            return false;
        });
        $("#btn_clear_tags").click(function() {
            $(".tags_list").data("tag-count", 0);
            $(".tags_list").html("");
            return false;
        });
        $("#file_0").change(function() {
            if ($("#btn_more_file").hasClass('not_visible')) {
                $("#btn_more_file").removeClass('not_visible');
                $("#btn_more_file").addClass('visible');
            }

            $("#btn_remove_file").removeClass('visible');
            $("#btn_remove_file").addClass('not_visible');
        });
        $("#btn_more_file").click(function() {
            fileCount += 1;
            var itemHtml = "<div class='file_item item_" + fileCount + "'>" +
                    "<div>ファイル</div>" +
                    "<table>" +
                    "<tr>" +
                    "<td style='width: 52px'></td>" +
                    "<td>" +
                    "<input type='file' name='file[" + fileCount + "]' id='file_" + fileCount + "'>" +
                    "</td>" +
                    "</tr>" +
                    "<tr>" +
                    "<td>説明</td>" +
                    "<td>" +
                    "<textarea class='file_dec' name='file_dec[" + fileCount + "]'></textarea><br>" +
                    "</td>" +
                    "</tr>" +
                    "<tr>" +
                    "<td colspan='2'>" +
                    "注意：アップロードできるフォーマット：ｍｐ３、ｐｎｊ、ｊｐｇ、ｔｓｖ"
            "</td>" +
                    "</tr>" +
                    "</table>" +
                    "</div>";
            $("#list_file").append(itemHtml);
            $(".item_" + fileCount).hide();
            $(".item_" + fileCount).show('slow');
            $("#btn_more_file").removeClass('visible');
            $("#btn_more_file").addClass('not_visible');
            $("#btn_remove_file").removeClass('visible');
            $("#btn_remove_file").addClass('not_visible');
            $("#file_" + fileCount).change(function() {
                if ($("#btn_more_file").hasClass('not_visible')) {
                    $("#btn_more_file").removeClass('not_visible');
                    $("#btn_more_file").addClass('visible');
                }
                if ($("#btn_remove_file").hasClass('not_visible')) {
                    $("#btn_remove_file").removeClass('not_visible');
                    $("#btn_remove_file").addClass('visible');
                }
            });



            return false;
        });
        $("#btn_remove_file").click(function() {
            $(".item_" + fileCount).hide(function() {
                if (fileCount >= 1) {
                    $(".item_" + fileCount).remove();
                    fileCount--;
                    if (fileCount == 0) {
                        $("#btn_remove_file").addClass('not_visible');
                        $("#btn_remove_file").removeClass('visible');
                    }
                }
            });

            return false;
        });
        
        $('form').submit(function(){
            // Disable next submit
            $('form').submit(function(){
                return false;
            });
        });
    });
</script>
<center>
    <div class="content" style="background: #F0F0F0;">
        <div class="top_content clear banner">
            <div style="position: absolute; top: 120px; right: 70px; ">
                <a href="<?php echo $this->baseUrl(); ?>/user/logout"><font style="color: #7E3500; font-weight: bold; text-decoration: underline;">ログアウト</font>
                </a>
            </div>
            <div  class="topbar-username"><big>ようこそ!</bigF><?php echo $this->user_info['name']; ?></div>
        </div>
        <big>

            <!--Menu Tab Bar-->
            <div class="menus clear">
                <div class="mn first_mn">
                    <a class="home" href="<?php echo $this->baseUrl(); ?>/teacher/index">
                        <font style="color: white;">ホーム</font>
                    </a>
                </div>
                <div title="" class="mn"><a href="<?php echo $this->baseUrl(); ?>/teacher/myLesson"><font style="color: white;">マイレッスン</font></a>
                </div>
                <div title="" class="mn "><a href="<?php echo $this->baseUrl(); ?>/teacher/payment">
                        <font style="color: white;">支払い</font></a><font style="color: white;">
                    </font>
                </div>
                <font style="color: white;">
                <div title="" class="mn "><a href="<?php echo $this->baseUrl(); ?>/teacher/profile"><font style="color: white;">プロファイル</font></a>
                </div>
                </font>
            </div>
            <div class="containt_center_cen clear" style="margin: 0px auto;">
                <form action="" method="post" enctype="multipart/form-data">
                    <div class="error_message" style="color: red;">
                        <?php if (isset($this->errorMessage)) echo $this->errorMessage; ?>
                    </div>
                    <table border="0" cellpadding="5" cellspacing="5" style="background: #E1E1E1;width: 60%; border-style: solid; border-width: thin; border-radius: 4px; padding: 10px;">
                        <tbody>
                            <tr>
                                <td colspan="2">
                                    授業作る
                                </td>
                            </tr>
                            <tr>
                                <td style="width: 52px;">タイトル</td>
                                <td> <input type="text" name="title" id="les_title" class="res_input"></td>
                            </tr>
                            <tr>
                                <td></td>
                                <td>
                                    <div class="tags_list" data-tag-count="0">
                                    </div>

                                    <button class="normal-button" style="float: right" id="btn_clear_tags">クリア</button>
                                </td>
                            </tr>
                            <tr>
                                <td>タグ</td>
                                <td>
                                    <input type="text" id="les_tag" class="res_input tag_input" style="width: 360px;">
                                    <button class="normal-button" id="btn_add_tag" style="float: right">追加</button>
                                </td>
                            </tr>

                            <tr>
                                <td>説明</td>
                                <td><textarea name="description" class="lesson-dec"></textarea></td>
                            </tr>

                            <tr>
                                <td colspan="2">
                                    <b>  ファイルアップロード</b>
                                </td>
                            </tr>

                            <tr>
                                <td colspan="2">
                                    <!--Item 1-->
                                    <div id= "list_file">
                                        <div class = "file_item">
                                            <div>ファイル</div>
                                            <table>
                                                <tr>
                                                    <td style="width: 52px;"></td>
                                                    <td>
                                                        <input type="file" name="file[0]" id="file_0">
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>説明</td>
                                                    <td>
                                                        <textarea class="file_dec" name="file_dec[0]"></textarea><br>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td colspan='2'>
                                                        注意：アップロードできるフォーマット：ｍｐ３、wav、ｐｎｇ、ｍｐ４、ｊｐｇ、ｔｓｖ、gif、ｐｄｆ
                                                    </td>
                                                </tr>
                                            </table>
                                        </div>
                                    </div>
                                    <button id="btn_more_file" class="not_visible normal-button" style="float:left;margin: 5px;">もう一つ</button>
                                    <button id="btn_remove_file" class="not_visible normal-button" style="float:left;margin: 5px;">削除</button>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="2">
                                    <input type="checkbox" name="copyright_check" value="">著作権規則と同意する<br>
                                    <input type="submit" name="submit" value="作成" style="margin-top: 5px;" id="les_submit" class="showlogfromm normal-button">
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </form>
            </div>
    </div>
</center>