<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<center>
    <div class="content" style="background: #F0F0F0;">
        <?php 
            echo $this->partial("teacher/teacher-top.phtml", array('username'=>$this->user_info['name']));
        ?>

        <div class="row-show float-left">
            <div class="lesson_register_content" style="width: 98%;">
                <div class="full-width lesson-big-title">
                    <?php echo $this->lessonInfo['title']; ?>
                </div>
                <table cellpadding='1' cellspacing='0' border='0' style="width: 100%;border-width: thin;border-style: solid;">
                    <tbody>
                        <tr valign="top">
                            <!--Left content-->
                            <td style="width: 22%;">
                                <div class="full-width" style="font-weight: bolder; color: white; padding-top: 3px;font-size: 16px; background: #51A007; width: 100%;">
                                    ファイル一覧
                                </div>
                                <div class="full-width" style="background: wheat; padding-top: 3px;">
                                    <?php
                                    $count = 0;
                                    foreach ($this->files as $file) {
                                        $count++;
                                        $fileType = explode(".", $file['filename']);
                                        $fileType =$fileType[1];
                                        if ($fileType == 'pdf') {
                                            ?>
                                            <a href="<?php echo $this->baseUrl(); ?>/teacher/file?lesson_id=<?php echo $this->lessonInfo['id']; ?>&file_id=<?php echo $file['id']; ?>">
                                                <div class="full-width" style="font-size: 16px; font-weight: bold; margin: 5px;">
                                                    <font style="color: #7E3500">
                                                    <?php echo $count . '.'; ?>
                                                    </font>
                                                    <?php echo $file['filename']; ?>
                                                    <img src="<?php echo $this->baseUrl(); ?>/public/images/pdf.png" width="16" height="16">
                                                </div>
                                            </a>           
                                            <?php
                                        } else if ($fileType == 'mp3') {
                                            ?>
                                            <a href="<?php echo $this->baseUrl(); ?>/teacher/file?lesson_id=<?php echo $this->lessonInfo['id']; ?>&file_id=<?php echo $file['id']; ?>">
                                                <div class="full-width" style="font-size: 16px;  font-weight: bold; margin: 5px;">
                                                    <font style="color: #7E3500">
                                                    <?php echo $count . '.'; ?>
                                                    </font>
                                                    <?php echo $file['filename']; ?>
                                                    <img src="<?php echo $this->baseUrl(); ?>/public/images/audio.png" width="16" height="16">
                                                </div>
                                            </a>              
                                            <?php
                                        } else if ($fileType = 'mp4') {
                                            ?>
                                            <a href="<?php echo $this->baseUrl(); ?>/teacher/file?lesson_id=<?php echo $this->lessonInfo['id']; ?>&file_id=<?php echo $file['id']; ?>">
                                                <div class="full-width" style="font-size: 16px;  font-weight: bold; margin: 5px;">
                                                    <font style="color: #7E3500">
                                                    <?php echo $count . '.'; ?>
                                                    </font>
                                                    <?php echo $file['filename']; ?>
                                                    <img src="<?php echo $this->baseUrl(); ?>/public/images/mp4.png" width="16" height="16">
                                                </div>
                                            </a>       
                                            <?php
                                        } else if ($fileType = 'png' || $fileType == 'jpg' || $fileType == 'jpeg') {
                                            ?>
                                            <a href="<?php echo $this->baseUrl(); ?>/teacher/file?lesson_id=<?php echo $this->lessonInfo['id']; ?>&file_id=<?php echo $file['id']; ?>">
                                                <div class="full-width" style="font-size: 16px;  font-weight: bold; margin: 5px;">
                                                    <font style="color: #7E3500">
                                                    <?php echo $count . '.'; ?>
                                                    </font>
                                                    <?php echo $file['filename']; ?>
                                                    <img src="<?php echo $this->baseUrl(); ?>/public/images/image.png" width="16" height="16">
                                                </div>
                                            </a> 
                                            <?php
                                        } else if ($fileType == 'tsv') {
                                            ?>
                                            <a href="<?php echo $this->baseUrl(); ?>/teacher/file?lesson_id=<?php echo $this->lessonInfo['id']; ?>&file_id=<?php echo $file['filename']; ?>">
                                                <div class="full-width" style="font-size: 16px;  font-weight: bold; margin: 5px;">
                                                    <font style="color: #7E3500">
                                                    <?php echo $count . '.'; ?>
                                                    </font>
                                                    <?php echo $file['filename']; ?>
                                                    <img src="<?php echo $this->baseUrl(); ?>/public/images/test.png" width="16" height="16">
                                                </div>
                                            </a> 
                                            <?php
                                        }
                                    }
                                    ?>
                                </div>
                            </td>
                            <!--View-->
                            <td>
                                <div class="full-width" style="font-weight: bolder; color: white; padding-top: 3px; padding-bottom: 3px; font-size: 16px; background: #51A007;">
                                    ファイル内容
                                </div>
                                <div style="margin: 10px; width: 95%;min-height: 500px;max-height: 800px; border-color: #007F9F; border-style: solid; border-width: thin;">
                                    <!--Content here-->
                                    <?php
                                    $currentFile = explode(".", $this->currentFile['filename']);
                                    $currentFile = $currentFile[1];
                                    if ($currentFile == 'pdf') { // PDFファイル
                                        ?>
                                        <embed src = "<?php echo $this->baseUrl(); ?>/<?php echo $this->currentFile['location']; ?>"
                                               width = "100%" height = "600px;">
                                               <?php
                                           } else if ($currentFile == 'mp3') {
                                               ?>
                                        <audio controls>
                                            <source src="<?php echo $this->baseUrl(); ?>/<?php echo $this->currentFile['location']; ?>" type="audio/mpeg">
                                            <embed height="100" width="90%" src="<?php echo $this->baseUrl(); ?>/<?php echo $this->currentFile['location']; ?>">
                                        </audio>
                                        <?php
                                    } else if ($currentFile == 'mp4') { // Videoファイル
                                        ?>
                                        <video width="100%" autoplay="false" controls>
                                            <source src="<?php echo $this->baseUrl(); ?>/<?php echo $this->currentFile['location']; ?>" type="video/mp4">
                                        </video>                                    
                                        <?php
                                    } else if ($currentFile == 'tsv') { // テストファイル
                                        ?>
                                        <!--フォームスタット-->
                                        <?php
                                        $controller = $this->controller;
                                        echo $controller->getTestHtml($this->currentFile['id']);
                                        ?>
<!--                                        <a href="<?php echo $this->baseUrl()."/teacher/students?learn_id=".$this->lessonId."&file_id=".$this->currentFile['id']; ?>">
                                            <button class="normal-button">学生リスト</button>
                                        </a>-->
                                    <?php
                                    }
                                    ?>
                                </div>
                                <script>
                                    function showReportForm()
                                    {
                                        $("#report_form").show();
                                        $("#btn_report").hide();
                                    }

                                    function hideReportForm() {
                                        $("#report_form").hide();
                                        $("#btn_report").show();
                                    }

                                    function hideReport() {
                                        $("#report_form").hide();
                                        $("#btn_report").hide();
                                    }

                                </script>
                                <div id="report_form" style="display: none; width: 60%; margin-left: 100px; border: none; border-radius: 4px;">
                                    <form method="post" action="<?php echo $this->baseUrl(); ?>/student/file?lesson_id=<?php echo $this->lessonInfo['id']; ?>&file_id=<?php echo $this->currentFile['id']; ?>">
                                        <textarea cols="60" name="report_content" rows="5" placeholder="理由" style="border-style: solid; border-width: medium; border-radius: 3px;"></textarea>
                                        <input type="submit" onclick="hideReport();" value="賛成" class="showlogfromm" style="width: 80px; height: 30px; margin-left: 180px;">
                                        <input id="btn_sen_report" onclick="hideReportForm();" type="button" value="キャンセル" class="register-cus" style="width: 80px; height: 30px;">
                                    </form>
                                </div>

                                <!--Comment file-->
                                <div style="width: 70%; margin-left: 100px;">
                                    <?php if (isset($this->comments)) {
                                    foreach ($this->comments as $comment) {
                                        ?>
                                        <div style="width: 70%;text-align: left;background: #DFF2F8; margin-left: 100px; margin-top: 5px; margin-bottom: 5px;box-shadow: 2px 2px 2px; border-style: solid; border-width: thin; border-radius: 1px;">
                                            <div class="full-width" style="padding-left: 20px;padding-top: 10px; font-weight: bolder; font-size: 16px; color: #7E3500">
                                                <?php
                                                if ($comment['role'] == 1) {
                                                    echo "学生:";
                                                } else {
                                                    echo "先生:";
                                                }
                                                echo $comment['name'];
                                                ?>
                                            </div>
                                            <div class="full-width" style="padding-left: 50px; font-size: 12px; color: #A66322; font-style: italic;">
                                                <?php
                                                $raw = $comment['time'];
                                                $arr = explode(" ", $raw);
                                                $ymd = explode("-", $arr[0]);
                                                $hsm = explode(":", $arr[1]);
                                                echo $ymd[0] . "年" . $ymd[1] . "月" . $ymd[2] . "日" . "-" . $hsm[0] . "時" . $hsm[1] . "分";
                                                ?>
                                            </div>
                                            <div class="full-width" style="padding-left: 50px; font-size: 14px;"><?php
                                                echo $comment['comment'];
                                                ?>
                                            </div>

                                        </div>
                                        <?php
                                    }
                                }
                                ?>
                                
                                </div>
                                <div style="width: 70%;text-align: left;background: #DFF2F8; margin-left: 100px; margin-top: 5px; margin-bottom: 5px;box-shadow: 2px 2px 2px; border-style: solid; border-width: thin; border-radius: 1px;">
                                    <form action="" method="post">
                                        <div  style="width: 70%;padding-left: 20px;padding-top: 10px; font-weight: bolder; font-size: 16px; color: #7E3500">
                                            <textarea cols="60" name="comment" placeholder="コメント内容" rows="5"　style="border-radius: 2px;text-align: left; border-style: solid; border-color: #A66322;"></textarea>
                                            <button type="submit" value="コメント" class="showlogfromm" style="height: 30px; margin-bottom: 10px;">コメント</button>
                                        </div>
                                    </form>
                                </div>                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</center>
<?php
if (isset($this->reportNotify)) {
    ?>
    <script type="text/javascript">
        alert("<?php echo $this->reportNotify; ?>");
        hideReport();
    </script>
    <?php
    unset($this->reportNotify);
}
?>