<!--
@Controller: teacher
@Action: lesson
-->
<style type="text/css">
    #lesson_container {
        width: 800px;
        margin: 20px auto;
        margin-top: 200px;
        padding: 10px;
        border: 1px solid yellowgreen;
        border-radius: 5px;
    }
    #lesson_container .title {
        font-weight: bold;
        margin-bottom: 20px;
    }
    #lesson_container .tag_label {
        font-weight: bold;
    }
    #lesson_container .tags span {
        padding: 5px;
        margin-right: 10px;
        border-radius: 5px;
        background-color: green;
        color: white;
    }
    #lesson_container .created_date {
        margin-top: 20px;
        font-size: 14px;
        color: gray;
    }
    #lesson_container .description {
        width: 500px;
        float: right;
        border: 1px solid yellowgreen;
        padding: 5px;
        height: 180px;
        margin-bottom: 10px;
        margin-left: 10px;
    }
    .message {
        width: 100%;
    }
    .file_container {
        border-top: 1px solid gray;
        cursor: pointer;
    }
    .file_container:hover {
        background-color: gainsboro;
    }
    .file_type {
        width: 50px;
        height: 50px;
        float: left;
    }
    .file_name_label {
        width: 250px;
        float: left;
        font-size: 14px;
        font-weight: bold;
        color: gray;
        margin-left: 8px;
        margin-bottom: 5px;
    }
    .file_description_label {
        font-size: 14px;
        font-weight: bold;
        color: gray;
        margin-bottom: 5px;
    }
    .file_type img {
        width: 40px;
        height: 40px;
        margin: 5px;
    }
    .file_name {
        overflow: auto;
        line-height: 50px;
        width: 200px;
        height: 50px;
        float: left;
    }
    .file_description {
        line-height: 50px;
        overflow: hidden;
        width: 440px;
        height: 50px;
        float: left;
    }
    .file_report {
        line-height: 50px;
        overflow: hidden;
        width: 30px;
        height: 40px;
        float: left;
        padding-top: 10px;
    }
    .file_report img {
        width: 30px;
        height: 30px;
    }
    .file_lock {
        line-height: 50px;
        overflow: hidden;
        width: 50px;
        height: 40px;
        float: left;
        padding-top: 10px;
    }
    .file_lock img {
        width: 30px;
        height: 30px;
    }
    .btn-delete {
        line-height: 50px;
        width: 50px;
        height: 50px;
        color: orange;
        cursor: pointer;
    }
    .btn-delete:hover {
        color: white;
    }
    #comment_container {
        width: 600px;
        margin: 0px auto;
        padding: 10px;
    }
    .comment_slot {
        margin: 10px 0px;
    }
    .comment_owner {
        font-weight: bold;
        font-size: 16px;
        color: #2793e6;
    }
    .comment_input textarea {
        width: 100%;
        height: 80px;
    }
    .created_time {
        color: gray;
        font-size: 14px;
        font-style: italic;
        margin-left: 30px;
    }
    .comment_content {
        margin-left: 30px;
    }
    .btn-inactive {
        color: gray;
    }
    .btn-inactive:hover {
        color: gray;
    }
</style>
<script type="text/javascript">
    $(document).ready(function() {

        $(".btn-add-file").click(function() {
            $(this).hide();
            $('form').show();
        });

        $(".btn-delete").click(function() {
            if ($(this).attr('href') != "#") {
                if (confirm("ファイルを本当に削除したいですか？")) {
                    return true;
                } else {
                    return false;
                }
            }
        });

        $(".btn-comment").click(function() {
            var comment = $(".comment-input").val();
            if (comment !== '') {
                $.ajax({
                    type: "POST",
                    url: "<?php echo $this->baseUrl(); ?>/api/lesson-comment",
                    data: {comment: comment, lesson_id: <?php echo $this->lessonId; ?>}
                })
                        .done(function(data) {
                            console.log(data);
                            $(".comment-input").before(
                                    "<div class='comment_slot'>" +
                                    "<div class='comment_owner'>" + data.name + "</div>" +
                                    "<div class='comment_content'>" + data.comment + "</div>" +
                                    "<div class='created_time'>" + data.time + "</div>" +
                                    "</div>");
                            $(".comment-input").val("");
                        });
            }
            return false;
        });

    });
</script>

<div class="content" style="background: #F0F0F0;">
    <center>
        <div class="top_content clear banner">
            <div style="position: absolute; top: 120px; right: 70px; ">
                <a href="<?php echo $this->baseUrl(); ?>/user/logout"><font style="color: #7E3500; font-weight: bold; text-decoration: underline;">ログアウト</font>
                </a>
            </div>
            <div  class="topbar-username"><big>ようこそ!</bigF><?php echo $this->user_info['name']; ?></div>
        </div>
        <big>

            <!--Menu Tab Bar-->
            <div class="menus clear">
                <div class="mn first_mn">
                    <a class="home" href="<?php echo $this->baseUrl(); ?>/teacher/index">
                        <font style="color: white;">ホーム</font>
                    </a>
                </div>
                <div title="" class="mn"><a href="<?php echo $this->baseUrl(); ?>/teacher/myLesson"><font style="color: white;">マイレッスン</font></a>
                </div>
                <div title="" class="mn "><a href="<?php echo $this->baseUrl(); ?>/teacher/payment">
                        <font style="color: white;">支払い</font></a><font style="color: white;">
                    </font>
                </div>
                <font style="color: white;">
                <div title="" class="mn "><a href="<?php echo $this->baseUrl(); ?>/teacher/profile"><font style="color: white;">プロファイル</font></a>
                </div>
                </font>
            </div>
    </center>
    
    <?php if ($this->lessonInfo) { // Check lesson NULL ?>
    <div id="lesson_container">
        <div class="message">
            <?php foreach ($this->messages as $message) { ?>
                <div style="color: green; padding-bottom: 10px;"><?php echo $message; ?></div>
            <?php } ?>
            <?php foreach ($this->errorMessages as $errorMessage) { ?>
                <div style="color: red; padding-bottom: 10px;"><?php echo $errorMessage; ?></div>
            <?php } ?>
        </div>
        <div class="description">
            <?php echo $this->lessonInfo['description']; ?>
        </div>
        <div style="height: 200px;">
            <div class="teacher_name">
                先生：<?php echo $this->lessonInfo['name']; ?>
            </div>
            <div class="tag_label">タグ:　</div>
            <div class="tags">
                <?php
                foreach ($this->tags as $tag) {
                    echo "<div style='margin: 15px;'><span>" . $tag['tag_name'] . "</span></div>";
                }
                ?>
            </div>
            <div class="created_date">
                <?php
                $time = $this->lessonInfo['create_time'];
                $correct = explode(" ", $time);
                $correct = $correct[0];
                $arr = explode("-", $correct);
                $year = $arr[0];
                $mon = $arr[1];
                $day = $arr[2];
                echo $year . "年" . $mon . "月" . $day . "日";
                ?>
            </div>
            <div class="like" style="width: 100%; margin: 10px 0px;">
                <span>
                    <img src="<?php echo $this->baseUrl(); ?>/public/images/num-like.png" width="15" height="15">
                    <span><?php echo $this->lessonInfo['num_like'] ?></span>
                </span>
                <span>
                    <img src="<?php echo $this->baseUrl(); ?>/public/images/num-view.png" width="15" height="15">
                    <span><?php echo $this->lessonInfo['view'] ?></span>
                </span>
                <span>
                    <img src="<?php echo $this->baseUrl(); ?>/public/images/student.png" width="15" height="15">
                    <span><?php echo $this->lessonInfo['students_num'] ?></span>
                </span>
                <?php if ($this->lessonInfo['is_mine']) { ?>
                <a style="font-size: 14px; margin-top: -3px;text-decoration: underline;padding-left: 30px" href="<?php echo $this->baseUrl(); ?>/teacher/students?lesson_id=<?php echo $this->lessonId ?>">
                    学生リスト見る
                </a>
                <?php } // End if ?>
            </div>
        </div>
        <div>
            <div>
                <div class="file_name_label">ファイル名</div>
                <div class="file_description_label">説明</div>
            </div>
            <?php
            // ファイルリスト
            foreach ($this->files as $file) {
                $fileTypes = explode(".", $file['filename']);

                $fileType = strtolower($fileTypes[count($fileTypes) - 1]);
                if ($fileType == 'pdf') {
                    $icon = $this->baseUrl() . "/public/images/pdf.png";
                } else if ($fileType == 'jpg' || $fileType == 'png' || $fileType == 'gif') {
                    $icon = $this->baseUrl() . "/public/images/image.png";
                } else if ($fileType == 'mp3' || $fileType == 'wav') {
                    $icon = $this->baseUrl() . "/public/images/audio.png";
                } else if ($fileType == 'mp4') {
                    $icon = $this->baseUrl() . "/public/images/mp4.png";
                } else if ($fileType == 'tsv') {
                    $icon = $this->baseUrl() . "/public/images/test.png";
                }
                ?>
            
                <!--ファイル-->
                <div class="file_container">
                    <?php 
                    $link = "#"; 
                    $deleteLink = "#";
                    $deleteBtnClass = " btn-inactive";
                    if ($this->lessonInfo['is_mine']) {
                        $link = $this->baseUrl() . "/teacher/file?file_id=" . $file['id'] . "&lesson_id=" . $this->lessonId;
                        $deleteLink = $this->baseUrl() . "/teacher/delete-file?file_id=" . $file['id'];
                        $deleteBtnClass = "";
                    }
                    ?>
                    <a href="<?php echo $link; ?>">
                        <div class="file_type"><img src="<?php echo $icon ?>"></div>
                        <div class="file_name"><?php echo $file['filename']; ?></div>
                        <div class="file_description"><?php echo $file['description'] ?></div>
                        <div class="file_report">
                            <?php if ($file['is_reported']) { ?>
                                <img src="<?php echo $this->baseUrl(); ?>/public/images/copyright_report.png">
                            <?php } ?>
                        </div>
                        <div class="file_lock">
                            <?php if ($file['status'] == 2) { ?>
                                <img src="<?php echo $this->baseUrl(); ?>/public/images/locked.png">
                            <?php } ?>
                        </div>
                    </a>
                    <a href="<?php echo $deleteLink; ?>" class="btn-delete<?php echo $deleteBtnClass; ?>">X</a>
                </div> <!--End file container-->
                <?php
            } // End foreach files
            ?>
            
            <!--ファイルアップロード-->
            <?php if ($this->lessonInfo['is_mine']) { ?>
            <div class="file_container">
                <center>
                    <form action="<?php echo $this->baseUrl() . "/teacher/add-file"; ?>" method="post"  enctype="multipart/form-data" style="display: none">
                        <input type="hidden" name="lesson_id" value="<?php echo $this->lessonInfo['id']; ?>">
                        <input name="file[0]" type="file"></br>
                        <div style="font-size: 14px;">ファイルの説明：</div>
                        <textarea style="width: 350px;height: 80px" name="description[0]"></textarea></br>
                        <input type="checkbox" name="copyright_check" value="">著作権規則と同意する
                        <input type="submit" value="アップロード" class="normal-button">
                    </form>
                    <div class="normal-button btn-add-file" style="margin: 5px;padding: 5px;">ファイル追加</div>
                </center>
            </div> <!--End file upload-->
            <?php } ?>
        </div>
    </div> <!--End lesson container-->
    <?php } else { // End if check lesson null  ?>
    <div style="color: red; padding-bottom: 10px;">ファイルが無効</div>
    <?php } ?>
    
    <hr class="clear">
        
    <!--コメント-->
    <?php if ($this->lesson) { // Check lesson null ?>
    <form method="post" id="comment_container">
        <?php
        foreach ($this->comments as $comment) {
            ?>
            <div class="comment_slot">
                <div class="comment_owner"><?php echo $comment['name']; ?></div>
                <div class="comment_content"><?php echo $comment['comment']; ?></div>
                <div class="created_time"><?php echo $comment['time']; ?></div>
            </div>
            <?php
        }
        ?>
        <div class="comment_input" >
            <textarea name="comment" class="comment-input"></textarea>
        </div>
        <input type="submit" value="コメント" class="normal-button btn-comment">
    </form>
    <?php } // End if check lesson null ?>
</div>