<!--
@Controller: teacher
@Action: lesson
-->
<style type="text/css">
    #lesson_container {
        width: 800px;
        margin: 20px auto;
        margin-top: 200px;
        padding: 10px;
        border: 1px solid yellowgreen;
        border-radius: 5px;
    }
    #lesson_container .title {
        font-weight: bold;
        margin-bottom: 20px;
    }
    #lesson_container .tag_label {
        font-weight: bold;
        float: left;
    }
    #lesson_container .tags span {
        text-decoration: underline;
    }
    #lesson_container .created_date {
        margin-top: 20px;
        color: gray;
    }
    #lesson_container .description {
        width: 500px;
        float: right;
        border: 1px solid yellowgreen;
        padding: 5px;
        min-height: 100px;
        margin-bottom: 10px;
        margin-left: 10px;
    }
    .file_container {
        border-top: 1px solid gray;
        cursor: pointer;
    }
    .file_container:hover {
        background-color: gainsboro;
    }
    .file_type {
        width: 50px;
        height: 50px;
        float: left;
    }
    .file_name_label {
        width: 250px;
        float: left;
        font-size: 14px;
        font-weight: bold;
        color: gray;
        margin-left: 8px;
        margin-bottom: 5px;
    }
    .file_description_label {
        font-size: 14px;
        font-weight: bold;
        color: gray;
        margin-bottom: 5px;
    }
    .file_type img {
        width: 40px;
        height: 40px;
        margin: 5px;
    }
    .file_name {
        line-height: 50px;
        width: 200px;
        height: 50px;
        float: left;
    }
    .file_description {
        line-height: 50px;
        width: 500px;
        height: 50px;
    }
    #comment_container {
        width: 600px;
        margin: 0px auto;
        padding: 10px;
    }
    .comment_slot {
        margin: 10px 0px;
    }
    .comment_owner {
        font-weight: bold;
        font-size: 16px;
        color: #2793e6;
    }
    .comment_input textarea {
        width: 100%;
        height: 80px;
    }
    .created_time {
        color: gray;
        font-size: 14px;
        font-style: italic;
        margin-left: 30px;
    }
    .comment_content {
        margin-left: 30px;
    }
</style>
<div class="content" style="background: #F0F0F0;">
    <center>
        <?php 
            echo $this->partial("teacher/teacher-top.phtml", array('username'=>$this->user_info['name']));
        ?>
    </center>
    <div id="lesson_container">
        <div class="description">
            これは授業の説明ばらばら。。。これは授業の説明ばらばら。。。これは授業の説明ばらばら。。。これは授業の説明ばらばら。。。これは授業の説明ばらばら。。。
        </div>
        <div>
            <div class="title">IT日本語</div>
            <div class="tag_label">タグ:　</div>
            <div class="tags">
                <span>IT</span>、
                <span>日本語</span>、
                <span>日本語</span>、
                <span>日本語</span>、
                <span>日本語</span>
            </div>
            <div class="created_date">2014年3月8日</div>
            <div class="like" style="width: 100%; margin: 10px 0px;">
                <span>
                    <img src="/Elearning/public/images/num-like.png" width="15" height="15">
                    <span>100</span>
                </span>
                <span>
                    <img src="/Elearning/public/images/num-view.png" width="15" height="15">
                    <span>200</span>
                </span>
            </div>
        </div>
        <div>
            <div>
                <div class="file_name_label">ファイル名</div>
                <div class="file_description_label">説明</div>
            </div>
            <div class="file_container">
                <a>
                    <div class="file_type"><img src="<?php echo $this->baseUrl()."/public/images/pdf.png" ?>"></div>
                    <div class="file_name">ファイル1</div>
                    <div class="file_description">ファイルの説明</div>
                </a>
            </div>
            <div class="file_container">
                <a>
                    <div class="file_type"><img src="<?php echo $this->baseUrl()."/public/images/pdf.png" ?>"></div>
                    <div class="file_name">ファイル1</div>
                    <div class="file_description">ファイルの説明</div>
                </a>
            </div>
            <div class="file_container">
                <a>
                    <div class="file_type"><img src="<?php echo $this->baseUrl()."/public/images/mp3.png" ?>"></div>
                    <div class="file_name">ファイル1</div>
                    <div class="file_description">ファイルの説明</div>
                </a>
            </div>
            <div class="file_container">
                <a>
                    <div class="file_type"><img src="<?php echo $this->baseUrl()."/public/images/img_file.png" ?>"></div>
                    <div class="file_name">ファイル1</div>
                    <div class="file_description">ファイルの説明</div>
                </a>
            </div>
        </div>
    </div>
    <div id="comment_container">
        <div class="comment_input">
            <textarea></textarea>
        </div>
        <button>コメント</button>
        <div class="comment_slot">
            <div class="comment_owner">学生１</div>
            <div class="comment_content">この授業はいいですね</div>
            <div class="created_time">2013年11月1日12時30分</div>
        </div>
        <div class="comment_slot">
            <div class="comment_owner">学生２</div>
            <div class="comment_content">この授業はいいですね</div>
            <div class="created_time">2013年11月1日12時30分</div>
        </div>
        <div class="comment_slot">
            <div class="comment_owner">学生３</div>
            <div class="comment_content">この授業はいいですね</div>
            <div class="created_time">2013年11月1日12時30分</div>
        </div>
    </div>
</div>