<!--
@Controller: teacher
@Action: lesson
-->
<style type="text/css">
    #lesson_container {
        width: 800px;
        margin: 20px auto;
        margin-top: 200px;
        padding: 10px;
        border: 1px solid yellowgreen;
        border-radius: 5px;
    }
    #lesson_container .title {
        font-weight: bold;
        margin-bottom: 20px;
    }
    #lesson_container .tag_label {
        font-weight: bold;
        float: left;
    }
    #lesson_container .tags span {
        padding: 5px;
        margin-right: 10px;
        border-radius: 5px;
        background-color: green;
        color: white;
    }
    #lesson_container .created_date {
        margin-top: 20px;
        font-size: 14px;
        color: gray;
    }
    #lesson_container .description {
        width: 500px;
        float: right;
        border: 1px solid yellowgreen;
        padding: 5px;
        height: 180px;
        margin-bottom: 10px;
        margin-left: 10px;
    }
    .file_container {
        border-top: 1px solid gray;
        cursor: pointer;
    }
    .file_container:hover {
        background-color: gainsboro;
    }
    .file_type {
        width: 50px;
        height: 50px;
        float: left;
    }
    .file_name_label {
        width: 250px;
        float: left;
        font-size: 14px;
        font-weight: bold;
        color: gray;
        margin-left: 8px;
        margin-bottom: 5px;
    }
    .file_description_label {
        font-size: 14px;
        font-weight: bold;
        color: gray;
        margin-bottom: 5px;
    }
    .file_type img {
        width: 40px;
        height: 40px;
        margin: 5px;
    }
    .file_name {
        overflow: auto;
        line-height: 50px;
        width: 200px;
        height: 50px;
        float: left;
    }
    .file_description {
        line-height: 50px;
        width: 500px;
        height: 50px;
    }
    #comment_container {
        width: 600px;
        margin: 0px auto;
        padding: 10px;
    }
    .comment_slot {
        margin: 10px 0px;
    }
    .comment_owner {
        font-weight: bold;
        font-size: 16px;
        color: #2793e6;
    }
    .comment_input textarea {
        width: 100%;
        height: 80px;
    }
    .created_time {
        color: gray;
        font-size: 14px;
        font-style: italic;
        margin-left: 30px;
    }
    .comment_content {
        margin-left: 30px;
    }
</style>
<div class="content" style="background: #F0F0F0;">
    <center>
        <?php 
            echo $this->partial("teacher/teacher-top.phtml", array('username'=>$this->user_info['name']));
        ?>
    </center>
    <div id="lesson_container">
        <div class="description">
            <?php echo $this->lessonInfo['description']; ?>
        </div>
        <div style="height: 200px;">
            <div class="title">IT日本語</div>
            <div class="tag_label">タグ:　</div>
            <div class="tags">
                <?php foreach ($this->tags as $tag) {
                    echo "<span>".$tag['tag_name']."</span>";
                }
                ?>
            </div>
            <div class="created_date">
                <?php
                    $time = $this->lessonInfo['create_time'];
                    $correct = explode(" ", $time)[0];
                    $arr = explode("-", $correct);
                    $year = $arr[0];
                    $mon = $arr[1];
                    $day = $arr[2];
                    echo $year . "年" . $mon . "月" . $day . "日";
                ?>
            </div>
            <div class="like" style="width: 100%; margin: 10px 0px;">
                <span>
                    <img src="<?php echo $this->baseUrl(); ?>/public/images/num-like.png" width="15" height="15">
                    <span><?php echo $this->lessonInfo['like'] ?></span>
                </span>
                <span>
                    <img src="<?php echo $this->baseUrl(); ?>/public/images/num-view.png" width="15" height="15">
                    <span><?php echo $this->lessonInfo['view'] ?></span>
                </span>
                <span>
                    <img src="<?php echo $this->baseUrl(); ?>/public/images/student.png" width="15" height="15">
                    <span><?php echo $this->lessonInfo['students_num'] ?></span>
                </span>
            </div>
        </div>
        <div>
            <div>
                <div class="file_name_label">ファイル名</div>
                <div class="file_description_label">説明</div>
            </div>
            <?php 
                foreach ($this->files as $file) {
                    $fileLocation = $file['location'];
                    $ext = explode('.', $fileLocation)[1];
                    if ($ext == 'pdf') {
                        $icon = "pdf.png";
                    } else if ($ext == 'jpg' ||$ext == 'jpge' ) {
                        $icon = "img_file.png";
                    } else if ($ext == 'mp3') {
                        $icon = "mp3.png";
                    } else if ($ext == 'mp4') {
                        $icon = "video.png";
                    } else if ($ext == 'html') {
                        $icon = "test.png";
                    }
            ?>
            <div class="file_container">
                <a href="<?php echo $this->baseUrl()."/teacher/file?file_id=".$file['id']; ?>">
                    <div class="file_type"><img src="<?php echo $this->baseUrl()."/public/images/".$icon ?>"></div>
                    <div class="file_name"><?php echo $file['filename']; ?></div>
                    <div class="file_description"><?php echo $file['description'] ?></div>
                </a>
            </div>
            <?php
                }
            ?>
        </div>
    </div>
    <div id="comment_container">
        <div class="comment_input">
            <textarea></textarea>
        </div>
        <button>コメント</button>
        <div class="comment_slot">
            <div class="comment_owner">学生１</div>
            <div class="comment_content">この授業はいいですね</div>
            <div class="created_time">2013年11月1日12時30分</div>
        </div>
        <div class="comment_slot">
            <div class="comment_owner">学生２</div>
            <div class="comment_content">この授業はいいですね</div>
            <div class="created_time">2013年11月1日12時30分</div>
        </div>
        <div class="comment_slot">
            <div class="comment_owner">学生３</div>
            <div class="comment_content">この授業はいいですね</div>
            <div class="created_time">2013年11月1日12時30分</div>
        </div>
    </div>
</div>