<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<center>
    <div class="content" style="background: #F0F0F0;">
        <div class="top_content clear banner">
                    <div style="position: absolute; top: 120px; right: 70px; ">
                        <a href="<?php echo $this->baseUrl(); ?>/user/logout"><font style="color: #7E3500; font-weight: bold; text-decoration: underline;">ログアウト</font>
                        </a>
                    </div>
                    <div  class="topbar-username"><big>ようこそ!</bigF><?php echo $this->user_info['name']; ?></div>
                </div>
                <big>

                    <!--Menu Tab Bar-->
                    <div class="menus clear">
                        <div class="mn first_mn">
                            <a class="home" href="<?php echo $this->baseUrl(); ?>/teacher/index">
                                <font style="color: white;">ホーム</font>
                            </a>
                        </div>
                        <div title="" class="mn"><a href="<?php echo $this->baseUrl(); ?>/teacher/myLesson"><font style="color: white;">マイレッスン</font></a>
                        </div>
                        <div title="" class="mn "><a href="<?php echo $this->baseUrl(); ?>/teacher/payment">
                                <font style="color: white;">支払い</font></a><font style="color: white;">
                            </font>
                        </div>
                        <font style="color: white;">
                        <div title="" class="mn"><a href="<?php echo $this->baseUrl(); ?>/teacher/profile"><font style="color: white;">プロファイル</font></a>
                        </div>
                        </font>
                    </div>
        <?php if(!empty($this->students)) :?>
		<div>
			<br> <h3>学生リスト</h3>
			<table width="560" border="1" bordercolor="#d5d5d5" style="border-collapse:collapse" cellpadding="4" cellspacing="4">
			<tr>
				<td>ユーザ名</td>
				<td>名前</td>
				<td></td>
			</tr>
			<?php foreach ($this->students as $student):?>
				<tr>
					<td><?php echo $student["username"]?></td>
					<td><?php echo $student["name"]?></td>
					<?php if(! $student["id"] || $student["id"] == 0 ):?>
					<td><a href="<?php echo $this->baseUrl()?>/teacher/lock-student-learn-lesson?lesson_id=<?php echo $this->lessonId; ?>&id=<?php echo $student["s_id"]?>"/><u>ロック</u></a></td>
					<?php else : ?>
					<td><a href="<?php echo $this->baseUrl()?>/teacher/unlock-student-learn-lesson?lesson_id=<?php echo $this->lessonId; ?>&id=<?php echo $student["s_id"]?>"/><u>アンロック</u></a></td>
					<?php endif;?>
				</tr>
			<?php endforeach;?>
			</table>
			<br>
		</div>
		<?php else : echo "データがない"; endif;?>
		<br>
		<u><a href = "<?php echo $this->baseUrl()?>/teacher/lesson?lesson_id=<?php echo $this->lessonId?>" >授業に戻る</a></u>
      </div>
</center>