
<!DOCTYPE html>
<html>
    <body>
        <script>
            function confirmDelete() {
                if (confirm("アカウントを削除する？")) {
                    return true;
                } else {
                    return false;
                }
            }
        </script>
        <div class="content">
            <center>
                <div class="top_content clear banner">
                    <div style="position: absolute; top: 120px; right: 70px; ">
                        <a href="<?php echo $this->baseUrl(); ?>/user/logout"><font style="color: #7E3500; font-weight: bold; text-decoration: underline;">ログアウト</font>
                        </a>
                    </div>
                    <div  class="topbar-username"><big>ようこそ!</bigF><?php echo $this->user_info['name']; ?></div>
                </div>
                <big>

                    <!--Menu Tab Bar-->
                    <div class="menus clear">
                        <div class="mn">
                            <a class="home" href="<?php echo $this->baseUrl(); ?>/teacher/index">
                                <font style="color: white;">ホーム</font>
                            </a>
                        </div>
                        <div title="" class="mn"><a href="<?php echo $this->baseUrl(); ?>/teacher/myLesson"><font style="color: white;">マイレッスン</font></a>
                        </div>
                        <div title="" class="mn "><a href="<?php echo $this->baseUrl(); ?>/teacher/payment">
                                <font style="color: white;">支払い</font></a><font style="color: white;">
                            </font>
                        </div>
                        <font style="color: white;">
                        <div title="" class="mn first_mn"><a href="<?php echo $this->baseUrl(); ?>/teacher/profile"><font style="color: white;">プロファイル</font></a>
                        </div>
                        </font>
                    </div>
                    <div class="row-show" style="background: #F0F0F0;">
                        <font style="text-align: center; color: #bb670a; font-size: 23px; width: 100%; float: left; margin-top: 20px;margin-bottom: 20px; font-weight: bold;">ユーザ情報</font>
                        <table cellpadding="10" cellspacing="1" style="border-style: double; border-color: #093; width: 50%;padding-left: 40px;">
                            <tr class="profile">
                                <!--ユーザネーム-->
                                <td>
                                    <b>ユーザ名:</b>
                                </td>
                                <td colspan="2">
                                    <font style="font-family: fantasy; font-size: 18px;">
                                    <?php echo $this->user_info['username']; ?>
                                    </font>
                                </td>
                            </tr>
                            <tr class="profile">
                                <!--Full name-->
                                <td><b>名前:</b></td>
                                <td colspan="2"><font style="font-family: serif; font-size: 18px;">
                                    <?php echo $this->user_info['name'] ?>
                                    </font>
                                </td>
                            </tr>

                            <tr class="profile">
                                <!--Birthday-->
                                <td><b>生年月日:</b></td>
                                <td colspan="2"><?php echo str_replace('-', '/', $this->user_info['birthday']); ?></td>
                            </tr>

                            <tr class="profile">
                                <!--Address-->
                                <td><b>アドレス:</b></td>
                                <td colspan="2"><?php echo $this->user_info['address'] ?></td>
                            </tr>

                            <tr class="profile">
                                <!--Email-->
                                <td><b>イーメール:</b></td>
                                <td><?php echo $this->user_info['email'] ?></td>
                            </tr>

                            <tr class="profile">
                                <!--Phone number-->
                                <td><b>電話番後:</b></td>
                                <td colspan="2"><?php echo $this->user_info['phone'] ?></td>
                            </tr>

                            <tr class="profile">
                                <!--Bank account-->
                                <td><b>銀後アカウント:</b></td>
                                <td colspan="2"><?php echo $this->user_info['bank_account'] ?></td>
                            </tr>

                            <tr class="profile">
                                <!--Role-->
                                <td><b>役割:</b></td>
                                <td colspan="2"><?php
                                    if ($this->user_info['role'] == 1) {
                                        echo "学生";
                                    } else {
                                        echo "先生";
                                    }
                                    ?></td>
                            </tr>
                            <tr col="4">
                                <td><a href="../teacher/profileChangeInfo"><button class="showlogfromm">情報更新</button></a></td>
                                <td><a href="../teacher/changePassword"><button class="showlogfromm">パスワード更新</button></a></td>
                                <td><a href="../teacher/delete-acount"><button class="showlogfromm" onclick= "return confirmDelete();">削除</button></a></td>
                                <td style="width: 160px;"><a href="../teacher/changeSecretQA"><button class="showlogfromm">機密質問情報を更新</button></a></td>
                            </tr>
                        </table>
                    </div>
            </center>
        </div>

    </body>
</html>
