
<!DOCTYPE html>
<html>
    <body>
    <center>
        <div class="content">
            <?php
            echo $this->partial("teacher/teacher-top.phtml", array('username' => $this->user_info['name']));
            ?>
            <form action="" method="post">
                <div class="row-show" style="padding: 20px 0 20px 0">
                    <font style="text-align: center; color: #bb670a; font-size: 23px; width: 100%; float: left; margin-top: 20px;margin-bottom: 20px; font-weight: bold;">ユーザ情報</font>
                    <table cellpadding="10" cellspacing="5" style="border-style: double; border-color: #093; width: 50%;">
                        <tr class="profile">
                            <!--ユーザネーム-->
                            <td>
                                <b>ユーザ名</b>
                            </td>
                            <td>
                                <input hidden name="username" value="<?php echo $this->user_info['username']; ?>">
                                <font style="font-family: fantasy; font-size: 18px;">
                                <?php echo $this->user_info['username']; ?>
                                </font>
                            </td>
                        </tr>
                        <tr class="profile">
                            <!--Full name-->
                            <td><b>名前</b></td>
                            <td>
                                <font style="font-family: serif; font-size: 18px;">
                                <input class="res_input" name="fullname" type="text" value="<?php echo $this->user_info['name'] ?>">
                                </font>
                            </td>
                        </tr>

                        <tr class="profile">
                            <!--Birthday-->
                            <td><b>生年月日</b></td>
                            <td>
                                <?php
                                $birthday = explode('-', $this->user_info['birthday']);
                                $day = $birthday[0];
                                $month = $birthday[1];
                                $year = $birthday[2];
                                ?>
                                <select id = "day" name = "day" style="width: 50px; text-align: right;">
                                    <option value = "<?php echo $day; ?>"><?php echo $day; ?></option>

                                    <option value = "1">1</option>

                                    <option value = "2">2</option>

                                    <option value = "3">3</option>

                                    <option value = "4">4</option>

                                    <option value = "5">5</option>

                                    <option value = "6">6</option>

                                    <option value = "7">7</option>

                                    <option value = "8">8</option>

                                    <option value = "9">9</option>

                                    <option value = "10">10</option>

                                    <option value = "11">11</option>

                                    <option value = "12">12</option>

                                    <option value = "13">13</option>

                                    <option value = "14">14</option>

                                    <option value = "15">15</option>

                                    <option value = "16">16</option>

                                    <option value = "17">17</option>

                                    <option value = "18">18</option>

                                    <option value = "19">19</option>

                                    <option value = "20">20</option>

                                    <option value = "21">21</option>

                                    <option value = "22">22</option>

                                    <option value = "23">23</option>

                                    <option value = "24">24</option>

                                    <option value = "25">25</option>

                                    <option value = "26">26</option>

                                    <option value = "27">27</option>

                                    <option value = "28">28</option>

                                    <option value = "29">29</option>

                                    <option value = "30">30</option>

                                    <option value = "31">31</option>

                                </select>
                                <b>日</b>
                                <select id="mon" name="month" style="width: 40px;">
                                    <option value="<?php echo $month; ?>"><?php echo $month; ?></option>

                                    <option value="1">1</option>

                                    <option value="2">2</option>

                                    <option value="3">3</option>

                                    <option value="4">4</option>

                                    <option value="5">5</option>

                                    <option value="6">6</option>

                                    <option value="7">7</option>

                                    <option value="8">8</option>

                                    <option value="9">9</option>

                                    <option value="10">10</option>

                                    <option value="11">11</option>

                                    <option value="12">12</option>
                                </select>
                                <b>月</b>
                                <select id="year" name="year" style="width: 60px;">
                                    <option value="<?php echo $year; ?>"><?php echo $year; ?></option>

                                    <option value="2013">2013</option>

                                    <option value="2012">2012</option>

                                    <option value="2011">2011</option>

                                    <option value="2010">2010</option>

                                    <option value="2009">2009</option>

                                    <option value="2008">2008</option>

                                    <option value="2007">2007</option>

                                    <option value="2006">2006</option>

                                    <option value="2005">2005</option>

                                    <option value="2004">2004</option>

                                    <option value="2003">2003</option>

                                    <option value="2002">2002</option>

                                    <option value="2001">2001</option>

                                    <option value="2000">2000</option>

                                    <option value="1999">1999</option>

                                    <option value="1998">1998</option>

                                    <option value="1997">1997</option>

                                    <option value="1996">1996</option>

                                    <option value="1995">1995</option>

                                    <option value="1994">1994</option>

                                    <option value="1993">1993</option>

                                    <option value="1992">1992</option>

                                    <option value="1991">1991</option>

                                    <option value="1990">1990</option>

                                    <option value="1989">1989</option>

                                    <option value="1988">1988</option>

                                    <option value="1987">1987</option>

                                    <option value="1986">1986</option>

                                    <option value="1985">1985</option>

                                    <option value="1984">1984</option>

                                    <option value="1983">1983</option>

                                    <option value="1982">1982</option>

                                    <option value="1981">1981</option>

                                    <option value="1980">1980</option>

                                    <option value="1979">1979</option>

                                    <option value="1978">1978</option>

                                    <option value="1977">1977</option>

                                    <option value="1976">1976</option>

                                    <option value="1975">1975</option>

                                    <option value="1974">1974</option>

                                    <option value="1973">1973</option>

                                    <option value="1972">1972</option>

                                    <option value="1971">1971</option>

                                    <option value="1970">1970</option>

                                    <option value="1969">1969</option>

                                    <option value="1968">1968</option>

                                    <option value="1967">1967</option>

                                    <option value="1966">1966</option>

                                    <option value="1965">1965</option>

                                    <option value="1964">1964</option>

                                    <option value="1963">1963</option>

                                    <option value="1962">1962</option>

                                    <option value="1961">1961</option>

                                    <option value="1960">1960</option>

                                    <option value="1959">1959</option>

                                    <option value="1958">1958</option>

                                    <option value="1957">1957</option>

                                    <option value="1956">1956</option>

                                    <option value="1955">1955</option>

                                    <option value="1954">1954</option>

                                    <option value="1953">1953</option>

                                    <option value="1952">1952</option>

                                    <option value="1951">1951</option>

                                    <option value="1950">1950</option>
                                </select>
                                <b>年</b>
                            </td>
                        </tr>

                        <tr class = "profile">
                            <!--Address-->
                            <td><b>アドレス</b></td>
                            <td><input value="<?php echo $this->user_info['address']; ?>" type="text" name="address" class="res_input"></td>
                        </tr>

                        <tr class = "profile">
                            <!--Email-->
                            <td><b>イーメール</b></td>
                            <td><input value="<?php echo $this->user_info['email']; ?>" type="text" name="email" class="res_input"></td>
                        </tr>

                        <tr class="profile">
                            <!--Phone number-->
                            <td><b>電話番後</b></td>
                            <td><input type="text" class="res_input" value="<?php echo $this->user_info['phone'] ?>" name="phone"></td>
                        </tr>

                        <tr class="profile">
                            <!--Bank account-->
                            <td><b>銀後アカウント</b></td>
                            <td><input class="res_input" name="bank_acc" value="<?php echo $this->user_info['bank_account'] ?>"></td>
                        </tr>

                        <tr class="profile">
                            <!--Role-->
                            <td><b>役割</b></td>
                            <td><?php
                                if ($this->user_info['role'] == 1) {
                                    echo "学生";
                                } else {
                                    echo "先生";
                                }
                                ?></td>
                        </tr>
                        <tr>
                            <td>
                                <font style="color: #900;">
                                <?php
                                if (isset($this->errorMessage)) {
                                    echo $this->errorMessage;
                                }
                                ?>
                                </font>
                            </td>
                        </tr>
                    </table>
                </div>
                <div style="width: 30%;">
                    <button type="submit" class="showlogfromm">更新</button>
                    <a href="<?php echo $this->baseUrl(); ?>/teacher/profile"><button class="register-cus" style="width: 130px;">キャンセル</button></a>
                </div>
            </form>

        </div>
    </center>
</body>
</html>
