<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<center>
    <div class="content" style="background: #F0F0F0;">
        <?php 
            echo $this->partial("teacher/teacher-top.phtml", array('username'=>$this->user_info['name']));
        ?>
        <?php if(!empty($this->students)) :?>
		<div >
			<h3>授業タイトル: <?php echo $this->students[0]["title"]?></h3>
			<table width="760" border="1" bordercolor="#d5d5d5" style="border-collapse:collapse" cellpadding="4" cellspacing="4">
			<tr>
				<td>ユーザ名</td>
				<td>名前</td>
				<td>勉強時間</td>
				<td>ライク</td>
				<td>コメント</td>
				<td></td>
				<td></td>
			</tr>
			<?php foreach ($this->students as $student):?>
				<tr>
					<td><?php echo $student["username"]?></td>
					<td><?php echo $student["name"]?></td>
					<td><?php echo $student["register_time"] ?></td>
					<td><?php if($student["liked"] != NULL ) echo "ライク"?></td>
					<td><?php echo $student["comment"] ?></td>
					<?php if($student["status"] == 1):?>
					<td><a href="<?php echo $this->baseUrl()?>/teacher/lock-student?lesson_id=<?php echo $this->lessonId?>&id=<?php echo $student["id"]?>"/><u>ロック</u></a></td>
					<?php else : ?>
					<td><a href="<?php echo $this->baseUrl()?>/teacher/unlock-student?lesson_id=<?php echo $this->lessonId?>&id=<?php echo $student["id"]?>"/><u>アンロック</u></a></td>
					<?php endif;?>
					<td> <u><a href = "<?php echo $this->baseUrl() ?>/teacher/student-result/learn_id/<?php echo $student["id"]?> ">テスト結果</a></u></td>
				</tr>
			<?php endforeach;?>
			</table>
			<br>
		</div>
		<?php endif;?>
      </div>
</center>