<?php 
$vars = $this->getVars(); 
$username = $vars['username'];
?>
<div class="top_content clear banner">
    <div style="position: absolute; top: 120px; right: 70px; ">
        <a href="<?php echo $this->baseUrl(); ?>/user/logout"><font style="color: #7E3500; font-weight: bold; text-decoration: underline;">ログアウト</font>
        </a>
    </div>
    <div  class="topbar-username"><big>ようこそ!</bigF><?php echo $username; ?></div>
</div>
<big>

<!--Menu Tab Bar-->
<div class="menus clear">
    <div class="mn first_mn">
        <a class="home" href="<?php echo $this->baseUrl(); ?>/teacher/index">
            <font style="color: white;">ホーム</font>
        </a>
    </div>
    <div title="" class="mn"><a href="<?php echo $this->baseUrl(); ?>/teacher/index"><font style="color: white;">マイ授業</font></a>
    </div>
    <div title="" class="mn "><a href="<?php echo $this->baseUrl(); ?>/teacher/payment">
        <font style="color: white;">支払い</font></a><font style="color: white;">
        </font>
    </div>
    <font style="color: white;">
        <div title="" class="mn "><a href="<?php echo $this->baseUrl(); ?>/teacher/profile"><font style="color: white;">プロファイル</font></a>
        </div>
    </font>
</div>