
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta http-Equiv="Cache-Control" Content="no-cache">
<meta http-Equiv="Pragma" Content="no-cache">
<meta http-Equiv="Expires" Content="0">
<!-- style tong hop -->
<link rel="stylesheet" type="text/css"
	href="http://www.tienganh123.com/static/css/ta123_styles.css?v=3" />
<script type="text/javascript"
	src="http://www.tienganh123.com/static/js/libraries.js?v=4"></script>
<script type="text/javascript"
	src="http://www.tienganh123.com/static/js/jquery_ready.js?v=8"></script>
<!--[if lte IE 10]>
        <link rel="stylesheet" type="text/css" href="http://www.tienganh123.com/static/css/common.css">
        <![endif]-->
<!--[if IE 6]>
        <link rel="stylesheet" type="text/css" href="http://www.tienganh123.com/static/css/ie6.css">
        <![endif]-->
<!--[if IE 7]>
        <link rel="stylesheet" type="text/css" href="http://www.tienganh123.com/static/css/ie7.css">
        <![endif]-->
<!--[if IE 8]>
        <link rel="stylesheet" type="text/css" href="http://www.tienganh123.com/static/css/ie8.css">
        <![endif]-->
<!--[if IE 9]>
        <link rel="stylesheet" type="text/css" href="http://www.tienganh123.com/static/css/ie9.css">
        <![endif]-->
<!-- Tienganh123 lib -->
<script type="text/javascript"
	src="/file/dungchung/audioPlayer/ubanplayer/swfobject/swfobject.js"></script>
<script src="http://www.tienganh123.com/static/js/libs_audio.js"></script>
<script type="text/javascript"
	src="http://www.tienganh123.com/static/js/audioPlayer/pickle/pickle.js"></script>


</head>
<body>
	<div class="bg_top">&nbsp;</div>
	<div class="bg_center">
		<div id="contents">
			<div class="top_content clear">
				<div class="logo">
					<a href="#"> <img width="230" height="58" src="#" alt="Logo">
					</a>
				</div>
				<div align="right" style="float: right; margin-top: 20px;">
					<a href="../user/logout"><button class="register-cus">ログアウト</button>
					</a>
				</div>
			</div>
			<div class="menus clear">
				<ul>
					<li class="home mn"><a href="#"></a>
					</li>
					<li title="" class="mn first_mn"><a href="#">マイ授業</a>
					</li>
					<li class="mn" title=""><a href="#">授業リスト</a>
					</li>
					<li title="" class="mn "><a href="#">支払い</a>
					</li>
					<li title="" class="mn "><a href="javascript:;">プロファイル</a>
					</li>
					<li title="" class="mn "><a href="#">CommingSoon</a>
					</li>
				</ul>
			</div>
			<div class="des_one_banner clear">
				<a href="#" target="_blank">
				<img width="1000" height="160" src="<?php echo $this->baseUrl().'/public/images/banner_t08vodoi.jpg'; ?>">
				</a>
			</div>
			
				<link rel="stylesheet" type="text/css" href="http://www.tienganh123.com/cpanel/css/profile.css">
				<link href="http://www.tienganh123.com/static/css/group.css" rel="stylesheet" type="text/css">

			<div class="containt_custormer_top clear">
				<div class="left_info_cus">
				</div>
				<div class="right_info_cus">
				<div>
			</div>
			<div class="containt_customer clear"></div>
			<div class="containt_center_bot clear"></div>
			<div class="info_footer"></div>
			<div class="footer"></div>
			<div class="bootom_footer"></div>
		</div>
		
		<div class="bg_bottom">
		</div>
	</div>

</body>
</html>
