<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta http-Equiv="Cache-Control" Content="no-cache">
        <meta http-Equiv="Pragma" Content="no-cache">
        <meta http-Equiv="Expires" Content="0">
    </head>
    <body>
        <div class="bg_top">&nbsp;</div>
        <div class="bg_center">
            <div id="contents">
                <div class="top_content clear">
					<div class="logo">
						<a href="#">
						<img width="230" height="58" src="#" alt="Logo">
						</a>
					</div>
					<div align="right" style="float: right; margin-top: 20px;">
						<a href="../user/logout"><button class="register-cus">ログアウト</button>
						</a>
					</div>
				</div>
                <div class="menus clear">
					<ul>
						<li class="home mn"><a href="#"></a>
						</li>
						<li title="" class="mn first_mn"><a href="#">マイ授業</a>
						</li>
						<li class="mn" title=""><a href="#">授業リスト</a>
						</li>
						<li title="" class="mn "><a href="#">支払い</a>
						</li>
						<li title="" class="mn "><a href="javascript:;">プロファイル</a>
						</li>
						<li title="" class="mn "><a href="#">CommingSoon</a>
						</li>
					</ul>
				</div>
				<div class="des_one_banner clear">
                    <a href="#" target="_blank">
					<img width="1000" height="160" src="<?php echo $this->baseUrl().'/public/images/banner_t08vodoi.jpg'; ?>">
					</a>
                </div>

				<div class="containt_customer_top clear"></div>
				<div class="containt_customer clear">

    <div class="left_info_cus">
                <div class="one">
            <div class="action_customer clear">
                <h3 class="cen"><a class="tk_none" style="word-wrap: break-word;" href="http://www.tienganh123.com/member/1368518" title="Ra trang chủ của mrtuananh91"> mrtuananh91</a></h3>
                <h5 class="off_live cen">Offline</h5>
                <div class="avataCus">
                    <div style="float:left;">
                        <a href="http://www.tienganh123.com/member/1368518" title="Ra trang chủ của mrtuananh91"><img src="http://data.tienganh123.com/images/member/noavatar.gif" width="123" alt=""></a>
                    </div>
                    <div class="pne_avt_rb "></div>
                </div>
                <h4>Thành viên <span class="orange dam">thường </span></h4>


                <div class="arrow_cus"></div>
            </div>
            <div class="thanhtichs">
                <ul style="margin-left:0;">
                    <li class="blue5 dam"><a id="map_learn" data-fancybox-type="iframe" href="http://www.tienganh123.com/pages/modules/basic_english.php?id=1368518" style="color: #0080A0;" >Ti&#7871;ng Anh c&#417; b&#7843;n s&#417; c&#7845;p</a></li>
                    <li>Giới tính : <span class="hong dam">Nam</span></li>
                    <li>Điểm học bạ : <span class="black dam">1</span> </li>
                    <li>Điểm thành tích : <span class="black dam">0</span></li>
                    <li>Bài viết : <span class="blue5 dam">0</span></li>
                    <li>Danh hiệu : <span class="orange dam"><span style="color:#960;">Kiến Gỗ</span></span></li>
                    <li>Sổ học bạ : <span class="blue5 dam"><span style="color:#666;">Đang cố gắng</span></span></li>
                    <li>Tham gia được : <span class="black dam">0 phút</span></li>

                    <li><a href="http://www.tienganh123.com/member/1368518/info" class="blue5 dam"> Xem thông tin cá nhân</a></li>
                </ul>
            </div>

        </div>

        <a class="logout" href="http://www.tienganh123.com/pages/manager.php?act=logout" title="Thoát"> <img src="http://data.tienganh123.com/images/v2/home/pr_bt_logout.png" /></a>

                <div class="two">
            <h4 class="clear">Quản trị</h4>
            <ul style="margin-left:0;">
                <li class="o_1"><a href="http://www.tienganh123.com/member/1368518/account">Thông tin tài khoản</a></li>
                <li class="o_2"><a href="http://www.tienganh123.com/member/1368518/avatar">Thay đổi hình đại diện</a></li>
                <li class="o_3"><a href="http://www.tienganh123.com/member/1368518/sign">Thay đổi chữ kí</a></li>
                <li class="o_4"><a href="http://www.tienganh123.com/member/1368518/pass">Thay đổi mật khẩu</a></li>
            </ul>
        </div>


        <div class="two" style="margin: 15 0 !important;">
            <h4 class="clear">Bài học của thành viên này</h4>
            <ul style="margin-left:0;">
                <li class="c_1"><a href="http://www.tienganh123.com/member/1368518/favorite">Bài học yêu thích</a></li>
                <li class="c_2"><a href="http://www.tienganh123.com/member/1368518/remember">Bài học ghi nhớ</a></li>
                <li class="c_3"><a href="http://www.tienganh123.com/member/1368518/history">Lịch sử học tập</a></li>
                <!--<li class="c_4"><a href="">Danh sách bài dự thi</a></li>-->
                <li class="c_5"><a href="http://www.tienganh123.com/member/1368518/thanhtich">Điểm thành tích</a></li>
                <li class="c_6"><a href="http://www.tienganh123.com/member/1368518/followed_list">Thành viên đang theo dõi</a></li>

            </ul>
        </div>

    </div>


    <div class="right_info_cus">

		<div class="action_cardd">
            <div class="mess_cardd">
                <p class="black-11">授業の更新</p>
            </div>
        </div>


<!---------- ここはサイトの主な内容　-------------------------------------------------->
        <div class="center_info_cus clear">
		<div class="resgg_box">
				<div class="resg_form_row">
					<div class="resg_f_r_left">
						<div class="resg_step_title">
						<div class="resg_step_t_numm resg_num">タイトル</div>
						<div class="resg_step_t_r"></div>
						</div>
					</div>
					<div class="resg_f_r_right">
						<input class="resg_input" type="text" maxlength="30"></input>
					</div>
				</div>
				
					<div class="resg_f_r_right" style="margin: 10px 0 -15px 247px">
						<div class="tag_selected">
						タッグ1, タッグ2
						</div>
						<a href="#"><u>クリア</u></a>
					</div>
				
				<div class="resg_form_row" >
					<div class="resg_f_r_left">
						<div class="resg_step_title">
						<div class="resg_step_t_numm resg_num">タッグ</div>
						<div class="resg_step_t_r"></div>
						</div>
					</div>
					<div class="resg_f_r_right">
						<div class="resg_select" style="margin-right: 40px">
                            <label><select id="#" name="#">
                                        <option value="0">プログラミング</option>

                                        <option value="1">コディング</option>

                                        <option value="2">数学</option>

                                        <option value="3">物理学</option>

                                        <option value="4">科学</option>

                                        <option value="5">文学</option>
							</label></select>
						</div>
						<input type="button" value="追加"></input>
					</div>
				</div>
				<div class="resg_form_row">
					<div class="resg_f_r_left">
						<div class="resg_step_title">
						<div class="resg_step_t_numm resg_num">説明</div>
						<div class="resg_step_t_r"></div>
						</div>
					</div>
					<div class="resg_f_r_right">
						<input class="resg_input_text" type="text" maxlength="300"></input>
					</div>
				</div>
				<div class="resg_form_row">
					<div class="resg_f_r_left">
						<div class="resg_step_title">
						<div class="resg_step_t_numm resg_num">ファイルアップロード</div>
						<div class="resg_step_t_r"></div>
						</div>
					</div>
				</div>

				<div class="resg_box">
					<div class="resg_form_row">
						<div class="resg_f_r_left">
							<div class="resg_step_title">
							<div class="resg_num_file">ファイル名</div>
							</div>
						</div>
						<div class="resg_f_r_right">
							<input class="resg_input_file" type="text" maxlength="30" ></input>
						</div>
					</div>

					<div class="resg_form_row">
						<div class="resg_f_r_left">
							<div class="resg_step_title">
							<div class="resg_num_file">説明</div>
							</div>
						</div>
						<div class="resg_f_r_right">
							<input class="resg_input_text_file" type="text" maxlength="300"></input>
						</div>
					</div>

					<div class="resg_form_row">
						<div class="resg_f_r_left">
							<div class="resg_num_file"><input type="file" name="file1" value="ファイルの選択"></input></div>
						</div>
						<div class="resg_f_r_right">
							<div class="resg_num_file_delete"><input type="button" value="削除"></input></div>
						</div>
					</div>
				</div>

				<div class="resg_box">
					<div class="resg_form_row">
						<div class="resg_f_r_left">
							<div class="resg_step_title">
							<div class="resg_num_file">ファイル名</div>
							</div>
						</div>
						<div class="resg_f_r_right">
							<input class="resg_input_file" type="text" maxlength="30" ></input>
						</div>
					</div>

					<div class="resg_form_row">
						<div class="resg_f_r_left">
							<div class="resg_step_title">
							<div class="resg_num_file">説明</div>
							</div>
						</div>
						<div class="resg_f_r_right">
							<input class="resg_input_text_file" type="text" maxlength="300"></input>
						</div>
					</div>

					<div class="resg_form_row">
						<div class="resg_f_r_left">
							<div class="resg_num_file"><input type="file" name="file2" value="ファイルの選択"></input></div>
						</div>
						<div class="resg_f_r_right">
							<div class="resg_num_file_delete"><input type="button" value="削除"></input></div>
						</div>
					</div>
				</div>


				<div class="resg_form_row">
					<div class="resg_f_r_left">
					&nbsp;<input type="button" value="もう一つ"></input>
					</div>
					<div class="resg_f_r_right_right">
						<a href="#" class="addcourse">&nbsp;</a>
					</div>
				</div>

		</div>

		</div>
				</div>

                <div class="containt_center_bot clear"></div>
                <div class="info_footer">
                    <div class="containt_info"></div>
                </div>
                <div class="footer">
                    <div class="footer_info"></div>
					<div class="line_doc"></div>
                </div>
                <div class="bootom_footer"></div>
            </div>
            <div class="bg_bottom"></div>
        </div>

    </body>
</html>
