<?php echo $this->doctype() ?>
<html>
    <head>   
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <?php echo $this->headTitle() ?>   
        <?php echo $this->headMeta() ?>        
        <?php echo $this->headLink() ?>   
        <?php echo $this->headScript() ?>      
    </head>
    <body>  
        <div>
            <?php
            echo $this->layout()->content;
            ?> 
        </div>
    <center>
        <div class="footer" style="text-align: center;">
            <font style="color: whitesmoke; font-size: 30px; font-weight: bolder; text-align: left;">Elearning システム</font>
        </div>
    </center>
</body>
</html>

