
<div><?php
// TODO session
?>
<div></div>
<div class="line"></div>
<div class="bigBtn"><a class="btn" href="#"><span class="end"><span
	class="label">Chơi ngay lập tức</span></span></a></div>
</div>
<div class="mini-line"></div>
<div class="block_zero center" style="padding-bottom: 8px;">
<div style="margin-bottom: 10px;">

<form action="<?php echo $this->element->getAction();?>"
	method="<?php echo $this->element->getMethod();?>">
<div style="margin-bottom: 10px;">Tên người dùng:<br />
<?php echo $this->element->username;?> <br />
Mật khẩu:<br />
<?php echo $this->element->password;?> <br />
<!-- Button Submit --> <span class="btn"><span class="end"> <?php echo $this->element->submit?>
</span></span></div>
<!-- Đăng ký tài khoản --> <a class="btn" href="register"> <span
	class="end"><span class="label">Đăng ký</span></span> </a> <!--  Quên mật khầu-->
<a class="btn" href="account/lostpass"> <span class="end"><span
	class="label">Quên mật khẩu</span></span> </a></form>
</div>
</div>
</div>


