
<script language="JavaScript">
            <!--
            var dictionaries = "ev_ve";
            // -->
            function loadFile(urls,index_script) {
                for(url in urls)
                {
                    var ga = document.createElement('script'); 
                    ga.type = 'text/javascript'; ga.async = true; 
                    ga.src = urls[url]; 
                    var s = document.getElementsByTagName('script')[index_script]; 
                    s.parentNode.insertBefore(ga, s);
                }
            }
        </script>
<script
	type="text/javascript"
	src="http://www.tienganh123.com/static/js/libraries.js?v=4"></script>
<script
	type="text/javascript"
	src="http://www.tienganh123.com/static/js/jquery_ready.js?v=8"></script>
<!--[if lte IE 10]>
        <link rel="stylesheet" type="text/css" href="http://www.tienganh123.com/static/css/common.css">
        <![endif]-->
<!--[if IE 6]>
        <link rel="stylesheet" type="text/css" href="http://www.tienganh123.com/static/css/ie6.css">
        <![endif]-->
<!--[if IE 7]>
        <link rel="stylesheet" type="text/css" href="http://www.tienganh123.com/static/css/ie7.css">
        <![endif]-->
<!--[if IE 8]>
        <link rel="stylesheet" type="text/css" href="http://www.tienganh123.com/static/css/ie8.css">
        <![endif]-->
<!--[if IE 9]>
        <link rel="stylesheet" type="text/css" href="http://www.tienganh123.com/static/css/ie9.css">
        <![endif]-->
<!-- Tienganh123 lib -->
<!-- AUDIO PLAYER -->
<script
	type="text/javascript"
	src="/file/dungchung/audioPlayer/ubanplayer/swfobject/swfobject.js"></script>
<script
	src="http://www.tienganh123.com/static/js/libs_audio.js"></script>
<script
	type="text/javascript"
	src="http://www.tienganh123.com/static/js/audioPlayer/pickle/pickle.js"></script>

<style type="text/css">
@media screen and (min-width:0\0) {
	.containt_center_cen {
		margin-top: -145px !important;
	}
	.containt_center_top {
		margin-top: -154px !important;
	}
	.containt_customer {
		margin-top: -145px !important;
	}
	.containt_customer_top {
		margin-top: -155px !important;
	}
}
</style>

</head>
<body>
<div class="bg_top">&nbsp;</div>
<div class="bg_center">
<div id="contents">
<div class="top_content clear">
<div class="logo"><a href="http://www.tienganh123.com"> <img width="230"
	height="58" src="http://data.tienganh123.com/images/v2/home/logo.png"
	alt="Logo"> </a></div>
<div class="action">

<ul class="first_notLogin">
	<li class="reg_card">
	<div id="hover_boxdt"><a class="gray"
		href="http://www.tienganh123.com/huong-dan/4668-cach-dat-the-vip-tren-tienganh123.html">Đăng
	ký mua thẻ</a>
	<div class="box_dt_fast">
	<div class="box_dt_ar"></div>
	<div class="box_dt_in"><a
		href="http://www.tienganh123.com/huong-dan/4668-cach-dat-the-vip-tren-tienganh123.html">
	<div class="box_dt_row">Đặt mua thẻ TiếngAnh123 <br />
	(giao tận nơi)</div>
	</a>


	<div class="box_dt_row box_dt_sp"><span>Tư vấn và đặt thẻ qua điện
	thoại: <span class="orange dam">047.305.3868 </span>(8h-21h)</span></div>
	</div>
	</div>
	</div>
	</li>
	<li class="ac_log">
	<div><a href="http://www.tienganh123.com/clogin" class="showlogfromm">Đăng
	nhập</a> <a href="http://www.tienganh123.com/register"
		class="register-cus">Đăng ký thành viên</a></div>
	</li>
</ul>
<div class="other-login"><span>Hoặc đăng nhập bằng:</span> <a
	href="javascript:void(0)" title="Đăng nhập bằng tài khoản Facebook"
	id="icon-fb" class="icon-fb-b"></a> <a identity="g"
	href="javascript:void(0)" title="Đăng nhập bằng tài khoản Gmail"
	class="openid icon-gg-b"></a> <a identity="y" href="javascript:void(0)"
	title="Đăng nhập bằng tài khoản Yahoo" class="openid icon-yh-b"></a></div>


</div>
</div>
<div class="menus clear">
<ul>
	<li class="home mn"><a href="http://www.tienganh123.com"></a></li>
	<li title="" class="mn first_mn"><a
		href="http://www.tienganh123.com/menu/tieng-anh-tre-em">Tiếng Anh trẻ
	em</a>
	<div style="width: 634px; left: -1px" class="sub_mn shadow">
	<div class="col_sub">
	<ul>
		<li><a title="Rocket to English 1"
			href="http://www.tienganh123.com/cambridge-young-learners-english">Rocket
		to English 1</a></li>
		<li><a title="Rocket to English 2"
			href="http://www.tienganh123.com/cambridge-young-learners-english-2">Rocket
		to English 2</a></li>
		<li><a title="Rocket to English 3"
			href="http://www.tienganh123.com/cambridge-young-learners-english-3">Rocket
		to English 3</a></li>
		<li><a title="Tiếng Anh trẻ em  lớp 3"
			href="http://www.tienganh123.com/tieng-anh-tre-em-lop-3">Tiếng Anh
		trẻ em lớp 3</a></li>
		<li><a title="Tiếng Anh trẻ em lớp 4"
			href="http://www.tienganh123.com/tieng-anh-tre-em-lop-4">Tiếng Anh
		trẻ em lớp 4</a></li>
		<li><a title="Tiếng Anh trẻ em lớp 5"
			href="http://www.tienganh123.com/tieng-anh-tre-em-lop-5">Tiếng Anh
		trẻ em lớp 5</a></li>
		<li><a title="Fun Fact Zone"
			href="http://www.tienganh123.com/fun-fact-zone">Fun Fact Zone</a></li>

		<li><a title="The Big Caption"
			href="http://www.tienganh123.com/the-big-caption">The Big Caption</a></li>
		<li><a title="What Happens Next?"
			href="http://www.tienganh123.com/what-happens-next">What Happens
		Next?</a></li>

	</ul>
	</div>
	<div class="col_sub">
	<ul>

		<li><a title="Dictation" href="http://www.tienganh123.com/dictation">Dictation</a></li>
		<li><a title="repetition" href="http://www.tienganh123.com/repetition">Repetition</a></li>
		<li><a title="ScienKids"
			href="http://www.tienganh123.com/science-for-kids">ScienKids</a></li>
		<li><a title="I Can Sing" href="http://www.tienganh123.com/i-can-sing">I
		Can Sing</a></li>


		<li><a title="Funny Q &amp; A"
			href="http://www.tienganh123.com/funny-q-and-a">Funny Q &amp; A</a></li>
		<li><a title="Tongue Twister"
			href="http://www.tienganh123.com/tongue-twister">Tongue Twister</a></li>

		<li><a title="Tiếng Anh Trẻ Em Qua Bài Hát"
			href="http://www.tienganh123.com/tieng-anh-tre-em-qua-bai-hat">Tiếng
		Anh Trẻ Em Qua Bài Hát</a></li>
		<li><a title="Tiếng Anh Trẻ Em Qua Phim"
			href="http://www.tienganh123.com/tieng-anh-tre-em-qua-phim">Tiếng Anh
		Trẻ Em Qua Phim</a></li>

	</ul>
	</div>
	<div class="col_sub last_des">
	<ul>
		<li><a title="Write Me"
			href="http://www.tienganh123.com/write-letter-kids">Write Me</a></li>
		<li><a title="Word Bag" href="http://www.tienganh123.com/word-bag">Word
		Bag</a></li>
		<li><a title="GoldenKids English Contest"
			href="http://www.tienganh123.com/goldenkids-english-contest">GoldenKids
		English Contest</a></li>
		<li><a title="Tiếng Anh Trẻ Em Qua Truyện Kể"
			href="http://www.tienganh123.com/learn-through-stories">Tiếng Anh Trẻ
		Em Qua Truyện Kể</a></li>
		<li><a title="Tiếng Anh trẻ em theo chủ đề"
			href="http://www.tienganh123.com/tieng-anh-tre-em-theo-chu-de">Tiếng
		Anh trẻ em theo chủ đề</a></li>
		<li><a title="Tiếng Anh trẻ em lớp 3 - sách mới"
			href="http://www.tienganh123.com/tieng-anh-tre-em-lop-3-sach-moi">Tiếng
		Anh trẻ em lớp 3 - sách mới</a></li>
		<li><a title="Danh Sách Giáo Viên GoldenKids"
			href="http://www.tienganh123.com/giao-vien-goldenkids">Giáo Viên
		GoldenKids Online</a></li>
		<li class="last_des"><a title="GoldenKids Practice"
			href="http://www.tienganh123.com/goldenkids-practice">GoldenKids
		Practice</a></li>
	</ul>
	</div>

	</div>
	<div id="arrow"></div>
	</li>
	<li class="mn" title=""><a
		href="http://www.tienganh123.com/tieng-anh-pho-thong">Tiếng Anh phổ
	thông </a>
	<div class="sub_mn shadow"
		style="width: 423px; display: none; left: auto; left: -1px">
	<div class="col_sub">
	<ul>
		<li><a href="http://www.tienganh123.com/tieng-anh-pho-thong-lop-6"
			title="Tiếng Anh lớp 6">Tiếng Anh lớp 6</a></li>
		<li><a href="http://www.tienganh123.com/tieng-anh-pho-thong-lop-8"
			title="Tiếng Anh lớp 8">Tiếng Anh lớp 8</a></li>
		<li><a href="http://www.tienganh123.com/tieng-anh-pho-thong-lop-10"
			title="Tiếng Anh lớp 10">Tiếng Anh lớp 10</a></li>
		<li><a href="http://www.tienganh123.com/tieng-anh-pho-thong-lop-12"
			title="Tiếng Anh lớp 12">Tiếng Anh lớp 12</a></li>
	</ul>
	</div>
	<div class="col_sub">
	<ul>
		<li><a href="http://www.tienganh123.com/tieng-anh-pho-thong-lop-7"
			title="Tiếng Anh lớp 7">Tiếng Anh lớp 7</a></li>
		<li><a href="http://www.tienganh123.com/tieng-anh-pho-thong-lop-9"
			title="Tiếng Anh lớp 9">Tiếng Anh lớp 9</a></li>
		<li><a href="http://www.tienganh123.com/tieng-anh-pho-thong-lop-11"
			title="Tiếng Anh lớp 11">Tiếng Anh lớp 11</a></li>
		<li><a href="http://www.tienganh123.com/on-thi-dai-hoc"
			title="Ôn thi đại học">Ôn thi đại học</a></li>
	</ul>
	</div>
	</div>
	<div id="arrow"></div>
	</li>
	<li title="" class="mn "><a
		href="http://www.tienganh123.com/menu/tieng-anh-nguoi-lon">Tiếng Anh
	người lớn</a>
	<div class="sub_mn shadow" w="400">
	<div class="col_sub">
	<ul>
		<li rel="sub_2"><a title="Tiếng Anh Cơ Bản 1"
			href="http://www.tienganh123.com/tieng-anh-co-ban">Tiếng Anh Cơ Bản 1</a></li>
		<li rel="sub_2"><a title="Tiếng Anh Cơ Bản 2"
			href="http://www.tienganh123.com/tieng-anh-co-ban-2">Tiếng Anh Cơ Bản
		2</a></li>
		<li rel="sub_2"><a title="Tiếng anh nâng cao"
			href="http://www.tienganh123.com/tieng-anh-nang-cao">Tiếng Anh nâng
		cao</a></li>
		<li rel="sub_2"><a title="Giao tiếp cơ bản"
			href="http://www.tienganh123.com/giao-tiep-co-ban">Giao tiếp cơ bản</a></li>
		<li rel="sub_2"><a title="Luyện Thi TOEIC"
			href="http://www.tienganh123.com/luyen-thi-toeic-tienganh123">Luyện
		Thi TOEIC</a></li>
		<li rel="sub_2"><a title="Luyện Thi IELTS"
			href="http://www.tienganh123.com/luyen-thi-ielts-tienganh123">Luyện
		Thi IELTS</a></li>
		<li rel="sub_2"><a title="hoc-qua-dich"
			href="http://www.tienganh123.com/hoc-qua-dich">Học qua Dịch</a></li>
		<li rel="sub_3" class="iconSub_3"><a class="a_sub_3" title="Tham khảo"
			href="http://www.tienganh123.com/menu/tham-khao">Tham khảo</a>
		<div class="col_sub sub_3">
		<ul>
			<li><a title="Communication English - tiếng Anh giao tiếp"
				href="http://www.tienganh123.com/communication-english">Communication
			English</a></li>

			<li><a title="Tiếng Anh giao tiếp hàng ngày - Tiếng Anh tình huống"
				href="http://www.tienganh123.com/tieng-anh-hang-ngay">Everyday
			English</a></li>

			<li><a
				title="Tiếng Anh thương mại - Tiếng Anh kinh doanh - Tiếng Anh thương mại online - tiếng Anh thương mại miễn phí"
				href="http://www.tienganh123.com/tieng-anh-thuong-mai">Business
			English</a></li>

			<li><a
				title="Tiếng Anh du lịch - Tiếng Anh du lịch trực tuyến - Tiếng Anh du lịch khách sạn"
				href="http://www.tienganh123.com/tieng-anh-du-lich">Tourism English</a></li>

			<li><a title="Luyện thi IELTS"
				href="http://www.tienganh123.com/luyen-thi-ielts">Luyện thi IELTS</a></li>

			<li class="last_des"><a
				title="Giáo trình streamline - Giáo trình streamline a - Giáo trình streamline english"
				href="http://www.tienganh123.com/streamline-a">Streamline A</a></li>
		</ul>
		</div>
		</li>
	</ul>
	</div>
	</div>
	<div id="arrow"></div>
	</li>
	<li title="" class="mn "><a href="javascript:;">Kỹ năng</a>
	<div style="width: 210px;" class="sub_mn shadow">
	<div class="col_sub last_des">
	<ul>
		<li><a
			title="Phát âm tiếng Anh - Học phát âm tiếng Anh - Phát âm chuẩn tiếng Anh - Học phát âm tiếng Anh qua video"
			href="http://www.tienganh123.com/menu/hoc-phat-am-tieng-anh">Phát âm
		tiếng Anh</a></li>
		<li><a
			title="Ngữ pháp tiếng Anh - Học ngữ pháp tiếng Anh - English Grammar"
			href="http://www.tienganh123.com/menu/ngu-phap-tieng-anh">Ngữ pháp
		tiếng Anh</a></li>
		<li><a
			title="Từ vựng tiếng Anh - Từ vựng tiếng Anh theo chủ đề - Học từ vựng tiếng Anh"
			href="http://www.tienganh123.com/tu-vung-tieng-anh">Từ vựng tiếng Anh</a></li>
		<li><a
			title="Nghe tiếng Anh - Luyện nghe tiếng Anh - Nghe tiếng Anh online - Nghe tiếng Anh trực tuyến - Nghe tiếng Anh giao tiếp"
			href="http://www.tienganh123.com/nghe-tieng-anh">Nghe</a></li>
		<li><a title="Nói tiếng Anh - Học nói tiếng Anh - Hội thoại tiếng Anh"
			href="http://www.tienganh123.com/hoc-noi-tieng-anh">Nói</a></li>
		<li><a
			title="Đọc tiếng Anh - Học đọc tiếng Anh - Đọc hiểu tiếng Anh - Kỹ năng đọc tiếng Anh"
			href="http://www.tienganh123.com/menu/hoc-doc-tieng-anh">Đọc</a></li>
		<li><a
			title="Học viết tiếng Anh - Viết tiếng Anh -  Viết tiếng Anh theo chủ đề - Viết tiếng Anh tốt - Kỹ năng viết tiếng Anh"
			href="http://www.tienganh123.com/hoc-viet-tieng-anh">Viết</a></li>
	</ul>
	</div>
	</div>
	<div id="arrow"></div>
	</li>
	<li title="" class="mn "><a
		href="http://www.tienganh123.com/menu/hoc-qua-clip">Học qua Video</a>
	<div class="sub_mn shadow" style="left: -92px;" w="595">
	<div class="col_sub">
	<ul>
		<li rel="sub_3" class="iconSub_3"><a class="a_sub_3"
			title="Luyện nghe tiếng Anh"
			href="http://www.tienganh123.com/menu/Video">Luyện nghe tiếng Anh</a>
		<div class="col_sub sub_3" style="width: 360px !important;">
		<ul style="float: left; width: 170px;">

			<li><a title="Arts" href="http://www.tienganh123.com/video-arts">Arts</a></li>

			<li><a title="Business"
				href="http://www.tienganh123.com/video-business">Business</a></li>

			<li><a title="Interview"
				href="http://www.tienganh123.com/video-interview">Interview</a></li>

			<li><a title="Travel" href="http://www.tienganh123.com/video-travel">Travel</a></li>

			<li><a title="Opinion"
				href="http://www.tienganh123.com/video-opinion">Opinion</a></li>

			<li><a title="Technology"
				href="http://www.tienganh123.com/video-technology">Technology</a></li>

			<li><a title="Entertainment"
				href="http://www.tienganh123.com/video-entertainment">Entertainment</a></li>

			<li><a title="Environment"
				href="http://www.tienganh123.com/video-environment">Environment</a></li>

		</ul>
		<ul style="float: right; width: 170px;">
			<li><a title="Health" href="http://www.tienganh123.com/video-health">Health</a></li>

			<li><a title="Living" href="http://www.tienganh123.com/video-living">Living</a></li>

			<li><a title="Sports" href="http://www.tienganh123.com/video-sports">Sports</a></li>

			<li><a title="Weather"
				href="http://www.tienganh123.com/video-weather">Weather</a></li>
			<li><a href="http://www.tienganh123.com/video-animals"
				title="Animals">Animals</a></li>
			<li><a href="http://www.tienganh123.com/video-finance"
				title="Finance">Finance</a></li>
			<li><a href="http://www.tienganh123.com/video-news" title="News">News</a></li>
			<li class="last_des"><a title="Science"
				href="http://www.tienganh123.com/video-science">Science</a></li>
		</ul>
		</div>
		</li>
		<li rel="sub_2"><a title="Học tiếng Anh qua CNN - Nghe CNN"
			href="http://www.tienganh123.com/hoc-tieng-anh-qua-cnn">Học tiếng Anh
		qua CNN</a></li>
		<li rel="sub_2"><a title="Học tiếng Anh qua BBC news"
			href="http://www.tienganh123.com/hoc-tieng-anh-qua-bbc">Học tiếng Anh
		qua BBC</a></li>
		<li rel="sub_2"><a title="Học tiếng Anh qua Video VOA"
			href="http://www.tienganh123.com/luyen-nghe-tieng-anh-qua-video-voa">Học
		tiếng Anh qua Video VOA</a></li>
		<li rel="sub_2"><a title="Học tiếng Anh với người nổi tiếng"
			href="http://www.tienganh123.com/menu/hoc-tieng-anh-voi-nguoi-noi-tieng">Học
		tiếng Anh với người nổi tiếng</a></li>
		<li rel="sub_2"><a title="Học tiếng Anh qua Youtube"
			href="http://www.tienganh123.com/hoc-tieng-anh-qua-youtube">Học tiếng
		Anh qua Youtube</a></li>
		<li rel="sub_2"><a title="Học tiếng Anh qua Video TED"
			href="http://www.tienganh123.com/luyen-nghe-voi-video-ted">Học tiếng
		Anh qua Video TED</a></li>
	</ul>
	</div>
	</div>
	<div id="arrow"></div>
	</li>
	<li title="" class="mn "><a
		href="http://www.tienganh123.com/menu/hoc-va-choi">Học & chơi</a>
	<div style="width: 210px; left: auto; right: -40px"
		class="sub_mn shadow">
	<div class="col_sub">
	<ul>
		<li><a title="Học tiếng Anh qua bài hát"
			href="http://www.tienganh123.com/hoc-tieng-anh-qua-bai-hat">Học tiếng
		Anh qua bài hát</a></li>
		<li><a title="Học tiếng Anh qua phim Trailer"
			href="http://www.tienganh123.com/hoc-tieng-anh-qua-phim-trailer">Học
		tiếng Anh qua phim Trailer</a></li>
		<li><a title="Học tiếng Anh qua truyện cười - truyện cười tiếng Anh"
			href="http://www.tienganh123.com/hoc-tieng-anh-qua-truyen-cuoi">Học
		tiếng Anh qua truyện cười</a></li>
		<li><a title="Thi Hát tiếng Anh Online"
			href="http://www.tienganh123.com/thi-hat-tieng-anh">Thi Hát tiếng Anh
		Online</a></li>
		<li><a title="Trò chơi tiếng Anh - English Game"
			href="http://www.tienganh123.com/menu/tro-choi-tieng-anh">Trò chơi
		tiếng Anh</a></li>
		<li><a title="Danh ngôn tiếng Anh"
			href="http://www.tienganh123.com/danh-ngon-tieng-anh">Danh ngôn tiếng
		Anh</a></li>
		<li class="last_des"><a title="What're your words?"
			href="http://www.tienganh123.com/what-are-your-words">What're your
		words?</a></li>
	</ul>
	</div>
	</div>
	<div id="arrow"></div>
	</li>
	<li title="" class="mn "><a
		href="http://www.tienganh123.com/menu/bai-test">Bài test</a>
	<div style="width: 210px; left: auto; right: -40px"
		class="sub_mn shadow">
	<div class="col_sub">
	<ul>
		<li><a title="Kiểm tra trình độ"
			href="http://www.tienganh123.com/kiem-tra-trinh-do">Kiểm tra trình độ</a></li>
		<li><a title="Pronunciation Test"
			href="http://www.tienganh123.com/pronunciation-test">Pronunciation
		Test</a></li>
		<li><a title="Grammar Test"
			href="http://www.tienganh123.com/bai-tap-ngu-phap-tieng-anh">Grammar
		Quiz</a></li>
		<li><a title="Vocabulary Test"
			href="http://www.tienganh123.com/flash-test">Flash Test</a></li>
		<li><a title="Thi đấu tiếng Anh"
			href="http://www.tienganh123.com/thi-dau">Thi đấu tiếng Anh</a></li>
	</ul>
	</div>
	</div>
	<div id="arrow"></div>
	</li>
	<li class="mn" title=""><a
		href="http://www.tienganh123.com/menu/chamdiem">Chấm điểm</a>
	<div class="sub_mn shadow"
		style="width: 423px; display: none; left: auto; right: -40px;">
	<div class="col_sub">
	<ul>
		<li><a href="http://www.tienganh123.com/dich-anh-viet"
			title="Dịch Anh - Việt (dễ)">Dịch Anh - Việt (dễ)</a></li>
		<li><a href="http://www.tienganh123.com/dich-viet-anh"
			title="Dịch Việt - Anh (dễ)">Dịch Việt - Anh (dễ)</a></li>
		<li><a href="http://www.tienganh123.com/viet-qua-tranh-de"
			title="Viết qua tranh (dễ)">Viết qua tranh (dễ)</a></li>
		<li><a href="http://www.tienganh123.com/viet-essay"
			title="Viết luận ngắn">Viết luận ngắn</a></li>
		<li><a href="http://www.tienganh123.com/luyen-noi-tieng-anh"
			title="Luyện nói tiếng Anh">Luyện nói tiếng Anh</a></li>
		<li><a href="http://www.tienganh123.com/listening-and-writing-easy"
			title="Nghe và Viết lại (dễ)">Nghe và Viết lại (dễ)</a></li>
	</ul>
	</div>
	<div class="col_sub">
	<ul>
		<li><a href="http://www.tienganh123.com/dich-anh-viet-inter"
			title="Dịch Anh - Việt (inter)">Dịch Anh - Việt (inter)</a></li>
		<li><a href="http://www.tienganh123.com/dich-viet-anh-inter"
			title="Dịch Việt - Anh (inter)">Dịch Việt - Anh (inter)</a></li>
		<li><a href="http://www.tienganh123.com/hoc-viet-tieng-anh-qua-tranh"
			title="Viết qua tranh (inter)">Viết qua tranh (inter)</a></li>
		<li><a href="http://www.tienganh123.com/viet-thu-phan-hoi"
			title="Viết thư phản hồi">Viết thư phản hồi</a></li>
		<li><a href="http://www.tienganh123.com/luyen-doc-doan-van"
			title="Luyện đọc đoạn văn">Luyện đọc đoạn văn</a></li>
		<li><a
			href="http://www.tienganh123.com/listening-and-writing-advanced"
			title="Nghe và Viết lại (inter)">Nghe và Viết lại (inter)</a></li>
	</ul>
	</div>
	</div>
	<div id="arrow"></div>
	</li>
	<li title="" class="mn "><a
		href="http://www.tienganh123.com/menu/hoc-offline">Học Offline</a>
	<div style="width: 210px; left: auto; right: -40px;"
		class="sub_mn shadow">
	<div class="col_sub">
	<ul>
		<li><a title="Lịch khai giảng"
			href="http://www.tienganh123.com/lich-khai-giang">Lịch khai giảng</a></li>
		<li class="last_des"><a title="Danh Sách Giáo Viên TiếngAnh123"
			href="http://www.tienganh123.com/giao-vien-tienganh123">Giáo Viên
		TiếngAnh123</a></li>
	</ul>
	</div>
	</div>
	<div id="arrow"></div>
	</li>
	<li title="" class="no_arown mn"><a
		href="http://forum.tienganh123.com/index.php">Diễn đàn</a></li>
</ul>
</div>
<div class="des_one_banner clear"><a
	href="http://www.tienganh123.com/tin-tuc-tienganh123/10872-khuyen-mai-chao-mung-xuan-giap-ngo-2014.html"
	target="_blank"><img width="1000" height="160"
	src="http://data.tienganh123.com/images/popup/banner_tet2014.jpg"></a>
</div>

<div class="containt_center_top clear"></div>
<div class="containt_center_cen clear">
<table cellpadding="0" cellspacing="0" border="0">
	<tr>
		<td valign="top" class="containt_center_cen_left">
		<style type="text/css">
#form_comment_area {
	display: none;
}
</style>

		<div class="navigations clear">
		<ul>
			<li class="child_r"><a class="nav_home" href="#">&nbsp;</a></li>
			<li class="child_c_2" style="z-index: 9999;">
			<div class="child_nav_left_c"><a
				href="http://www.tienganh123.com/quang-cao"
				title="Thẻ học tiếng anh trực tuyến">Thẻ học tiếng anh trực tuyến</a>
			</div>
			<div class="child_nav_right_c">&nbsp;</div>
			</li>
		</ul>
		</div>
		<div class="comment_bai_hoc clear">




		<div class="vd_box">

		<div class="stt_detail_video">
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<link rel="stylesheet" type="text/css"
			href="http://www.tienganh123.com/static/css/datthe_huongdan.css">
		<script language="javascript" type="text/javascript"
			src="/file/dungchung/function.js"></script> <script
			type="text/javascript">                        
            var page_current_df = 1;
            var setI = setInterval(function(){fixNo(10)},5000)
            function autoNext(page_current_df,countItemSlide){
                $('.vb_slide_content').hide();                                    
                $('.vb_slide_page').removeClass('vb_slide_page_active')
                $('.vb_slide_page[alt='+ page_current_df +']').addClass('vb_slide_page_active')
                $('.vb_slide_content[alt='+ page_current_df +']').fadeIn();                
            }
            function fixNo(countItemSlide){
                if(page_current_df < countItemSlide)
                {                
                    page_current_df += 1;                          
                }
                else
                    page_current_df = 1;  

                autoNext(page_current_df,countItemSlide);
            }
            $(function(){ 
                $(".vb_slide_content").mouseover(function(){
                    clearInterval(setI);
                }).mouseout(function(){
                    setI = setInterval(function(){fixNo(10)},5000)
                });
                /*(".vb_slide_content").mouseover(function(){
                clearInterval(setI);
                })*/               
                //Slide 1
                var countItemSlide = $('.vb_slide_content').length;                
                //Default item show                                                
                $('.vb_slide_content:first').show();

                for(var i = 1 ; i <= countItemSlide ; i++){
                    $('#vb_range_slide').append('<span class="vb_slide_page" alt="'+ i +'"></span>');
                }
                $('.vb_slide_page:first').addClass('vb_slide_page_active');
                //Event change page
                $('.vb_slide_page').click(function(){                    
                    var pageCurrent = $(this).attr('alt');
                    page_current_df = pageCurrent;
                    $('.vb_slide_content').hide();
                    $('.vb_slide_content[alt='+ pageCurrent +']').fadeIn();
                    //remove active and add active
                    $('.vb_slide_page').removeClass('vb_slide_page_active')
                    $(this).addClass('vb_slide_page_active')
                })
                //Event next back
                $('.vb_slide_next').click(function(){
                    $('.vb_slide_content').hide();
                    if(page_current_df < countItemSlide)
                        page_current_df ++;                          
                    else
                        page_current_df = 1;

                    $('.vb_slide_page').removeClass('vb_slide_page_active')
                    $('.vb_slide_page[alt='+ page_current_df +']').addClass('vb_slide_page_active')
                    $('.vb_slide_content[alt='+ page_current_df +']').fadeIn();
                })
                $('.vb_slide_pre').click(function(){
                    $('.vb_slide_content').hide();
                    if(page_current_df > 1)
                        page_current_df --;                          
                    else
                        page_current_df = countItemSlide;
                    $('.vb_slide_page').removeClass('vb_slide_page_active')
                    $('.vb_slide_page[alt='+ page_current_df +']').addClass('vb_slide_page_active')
                    $('.vb_slide_content[alt='+ page_current_df +']').fadeIn();
                })
                //Slide 2
                $('.vb_slide_2 li').hover(function(){
                    if($(this).attr('alt') != 'acti'){
                        $(this).addClass('vb_slide_acti_hover')
                        $(this).find('span[id=vb_item_slide]').removeClass('vb_slide_arrow_noacti_down').addClass('vb_slide_arrow_acti_down')   
                    }                    
                    },function(){
                        if($(this).attr('alt') != 'acti'){
                            $(this).removeClass('vb_slide_acti_hover')
                            $(this).find('span[id=vb_item_slide]').removeClass('vb_slide_arrow_acti_down').addClass('vb_slide_arrow_noacti_down')
                        }
                })
                //Event click
                $('.vb_slide_2 ul li span[id=vb_item_slide]').click(function(){
                    if($(this).parent().attr('alt') != 'acti'){
                        $('.vb_slide_2 li').attr('alt','').removeClass('vb_slide_acti_hover');
                        $(this).parent().attr('alt','acti').addClass('vb_slide_acti_hover');
                        $('.vb_slide_2 li span[id=vb_item_slide]').removeClass('vb_slide_arrow_acti_up').addClass('vb_slide_arrow_noacti_down')
                        $(this).removeClass('vb_slide_arrow_acti_down').addClass('vb_slide_arrow_acti_up')
                        $('.vb_slide_2_content').stop().slideUp(300)                        
                    }
                    else{
                        $(this).parent().attr('alt','');                        
                        $(this).removeClass('vb_slide_arrow_acti_up').addClass('vb_slide_arrow_acti_down')
                    }
                    $(this).parent().find('div[class=vb_slide_2_content]').stop().slideToggle(300)
                })
                 $(".vb_action_submit input").hover(function(){
                    $(this).attr('src','http://data.tienganh123.com/images/quyenloithanhvien/20_Dat_mua_the_hover.gif');
                },function(){
                    $(this).attr('src','http://data.tienganh123.com/images/quyenloithanhvien/20_Dat_mua_the.gif');
                })
            })
        </script>

		<DIV id=tickerbg style="POSITION: absolute"></DIV>
		<DIV id=ticker style="POSITION: absolute"></DIV>
		<script language="javascript" type="text/javascript">
dk=1;
</script>

		<div class="vb_quyen-loi-thanh-vien">
		<div class="vb_banner"><img
			src="http://data.tienganh123.com/images/quyenloithanhvien/1_banner_07.jpg"
			alt="Quyền lợi thành viên"></div>
		<div class="vb_contents-descript-child">
		<h3 class="vb_title-1">Bạn có biết?</h3>
		<div class="vb_box-1"><span class="vb_bold">Chỉ học tiếng Anh trên lớp
		</span>chắc chắn không đủ. <span class="vb_bold">Bạn hãy tự học thêm</span>
		và khuyến khích người thân của mình tự học. <span class="vb_bold"><br>
		TiếngAnh123.com</span> là website học tiếng Anh online <span
			class="vb_bold vb_orange">hàng đầu Việt Nam</span>, là công cụ rất
		tốt cho việc tự học và luyện tập thêm tiếng Anh ở mọi trình độ.</div>
		<h3 class="vb_title-2">Một số giải thưởng <span class="vb_green">TiếngAnh123.com</span>
		đã đạt được</h3>
		<div class="vb_box-2">
		<div class="vb_giaithuong vb_right-margin17">
		<div class="vb_saokhue">
		<div class="vb_textsaokhue">Đạt danh hiệu <a
			href="http://www.tienganh123.com/tin-tuc-tienganh123/9218-tienganh123-nhan-danh-hieu-sao-khue-2013.html"
			title="TiếngAnh123 nhận danh hiệu Sao Khuê 2013" target="_blank">Sao
		Khuê 2013</a> do Hiệp hội phần mềm và Dịch vụ CNTT Việt Nam trao tặng
		</div>
		</div>
		</div>
		<div class="vb_giaithuong">
		<div class="vb_top50">
		<div class="vb_texttop50"><a
			href="http://www.tienganh123.com/tin-tuc-tienganh123/7908-tin%20thang%2010-2012.html"
			title="TiếngAnh123 lọt vào TOP 50 sản phẩm tin cậy do người tiêu dùng bình chọn"
			target="_blank">TOP 50 sản phẩm tin cậy</a> do người tiêu dùng bình
		chọn năm 2012</div>
		</div>
		</div>
		</div>
		<h3 class="vb_title-2">Một vài con số về <span class="vb_green">TiếngAnh123.com</span>
		</h3>
		<div class="vb_box-3">
		<div class="vb_box-left vb_border-right">
		<div class="vb_box-3-item1 vb_border-bottom">
		<div class="vb_box-3-item-ct">
		<div class="vb_box-3-item-ct-text">Là website <span class="vb_bold">
		đầu tiên và duy nhất</span> <span class="vb_green">cho phép học viên
		gửi bài để được chấm điểm online</span> bởi các giáo viên giàu kinh
		nghiệm.</div>
		</div>
		</div>
		<div class="vb_box-3-item2">
		<div class="vb_box-3-item-ct">
		<div class="vb_box-3-item-ct-text">Là số <span class="vb_green"> lượt
		truy cập trong <span class="vb_bold">1 ngày</span></span> trên
		TiếngAnh123.com tương đương với hơn 2.4 triệu lượt truy cập 1 tháng.</div>
		</div>
		</div>
		</div>
		<div class="vb_box-left">
		<div class="vb_box-3-item3 vb_border-bottom">
		<div class="vb_box-3-item-ct">
		<div class="vb_box-3-item-ct-text">Là một trong <span class="vb_bold">200</span>
		<span class="vb_green">website</span> được truy cập nhiều nhất ở Việt
		Nam (đứng thứ <span class="vb_bold">164</span>) theo xếp hạng của
		Alexa.</div>
		</div>
		</div>
		<div class="vb_box-3-item4">
		<div class="vb_box-3-item-ct">
		<div class="vb_box-3-item-ct-text">Là số thành <span class="vb_green">thành
		viên</span> đã, đang theo học và chia sẻ kinh nghiệm.</div>
		</div>
		</div>
		</div>
		</div>
		</div>
		<div class="vb_banner"><img
			src="http://data.tienganh123.com/images/quyenloithanhvien/2_banner_2.jpg"
			alt="Quyền lợi thành viên"></div>
		<div class="vb_contents-descript">
		<div class="vb_contents-descript-child">
		<div class="vb_box-4">
		<div class="vb_box-4-item vb_right-margin26 vb_bg-dolla">
		<h3 class="vb_blue-1">Chi phí thấp - hiệu quả cao</h3>
		Thay vì bỏ ra <span class="vb_bold">hàng triệu đồng</span> để tới các
		trung tâm. Học online với TiếngAnh123.com bạn chỉ cần bỏ ra <span
			class="vb_bold vb_orange-1">250.000đ/năm</span> - bạn sẽ thấy hiệu
		quả rõ rệt.</div>
		<div class="vb_box-4-item vb_bg-clock">
		<h3 class="vb_green-1">Chủ động về thời gian, địa điểm</h3>
		Chỉ cần máy tính, smart phone hoặc máy tính bảng của bạn có kết nối
		internet. Bạn có thể học, gửi bài và ôn lại bài bất cứ nơi đâu, bất cứ
		khi nào (24/24 và 7/7).</div>
		</div>
		<div class="vb_box-4">
		<div class="vb_box-4-item vb_right-margin26 vb_bg-play">
		<h3 class="vb_orange-2">Hệ thống bài học thông minh, phong phú & liên
		tục được cập nhật</h3>
		Các bài học tương tác thông minh, dễ hiểu, dễ nhớ, các loại hình phong
		phú (video, nhạc, audio âm thanh chuẩn, hình ảnh chất lượng cao) và
		liên tục được cập nhật mới.</div>
		<div class="vb_box-4-item vb_bg-pen">
		<h3 class="vb_orange-3">Gửi bài để nhận điểm và đánh giá trực tiếp từ
		các giáo viên</h3>
		Đội ngũ giáo viên trình độ cao sẽ liên tục hỗ trợ, đánh giá, chấm điểm
		bài học, sửa sai và giúp bạn tiến bộ từng ngày.</div>
		</div>
		<div class="vb_box-4">
		<div class="vb_box-4-item vb_right-margin26 vb_bg-star">
		<h3 class="vb_orange-3">Ôn tập và học lại kiến thức theo trình độ của
		mình</h3>
		Bạn có thể chọn giáo trình phù hợp để học, ghi nhớ, ôn tập lại và hoàn
		thành các giáo trình một cách hoàn toàn chủ động.</div>
		<div class="vb_box-4-item vb_bg-peple">
		<h3 class="vb_blue-1">Chia sẻ, học hỏi và thi đua với cộng đồng thành
		viên TiếngAnh123.com</h3>
		Kết bạn, giao lưu, chia sẻ kinh nghiệm và thi đấu tiếng Anh với <span
			class="vb_bold">hơn 1,1 triệu thành viên</span> khác.</div>
		</div>
		<div class="vb_quyenloithanhvien">Quyền lợi khi sử dụng <span
			class="vb_orange vb_bold">thẻ học tiếng Anh VIP card (thành viên VIP)</span>
		trị giá <span class="vb_orange vb_bold">250.000đ/năm</span> trên
		TiếngAnh123.com :</div>
		</div>
		<div class="vb_box-5 vb_box-5-step1">
		<div class="vb_contents-descript-child-2">
		<div class="vb_box-5-item vb_title_step1">Ôn tập và học lại tiếng Anh
		từ đầu qua mục bài <span style="cursor: default;"
			onmouseout="hideticker(this)"
			onmouseover="showmessage('Chương trình tiếng Anh cơ bản 1 dành cho những bạn muốn học và ôn tập tiếng Anh từ đầu một cách có hệ thống.',this)">
		<a href="http://www.tienganh123.com/tieng-anh-co-ban" target="_blank">Tiếng
		Anh Cơ Bản 1</a></span> <span class="vb_bold">và</span> <span
			style="cursor: default;" onmouseout="hideticker(this)"
			onmouseover="showmessage('Chương trình tiếng Anh cơ bản 2 dành cho những bạn đã học qua tiếng Anh cơ bản 1.',this)"><a
			href="http://www.tienganh123.com/tieng-anh-co-ban-2" target="_blank">
		Tiếng Anh cơ bản 2</a></span>. Với những bài giảng về từ vựng, ngữ
		pháp, phát âm, nghe, nói, đọc hiểu và viết từ đầu, chúng sẽ giúp bạn
		ôn tập và lấp được những lỗ hổng kiến thức và nâng cao khả năng tiếng
		Anh của mình từ từ nhưng chắc chắn.</div>
		</div>
		</div>
		<div class="vb_box-6 vb_box-6-step2">
		<div class="vb_contents-descript-child-2">
		<div class="vb_box-6-item-1 vb_title_step2">Lần đầu tiên, TiếngAnh123
		đưa ra cách <span style="cursor: default;"
			onmouseout="hideticker(this)"
			onmouseover="showmessage('Với những bài luyện nghe và các mục luyện nói được soạn bởi các giáo viên bản ngữ giọng Anh Mỹ, sẽ giúp các bạn làm các bài tập luyện nghe và nói trực tuyến đầy thú vị. Các bài học được soạn từ dễ đến khó - và bạn phải qua bài này mới sang được bài khác. Giáo viên sẽ chấm điểm và nhận xét cho học sinh.',this)"><a
			href="http://www.tienganh123.com/giao-tiep-co-ban" target="_blank">học
		tiếng Anh giao tiếp trực tuyến</a></span> đầy thú vị với những bài
		luyện nghe và các mục luyện nói được soạn bởi các giáo viên bản ngữ
		giọng Anh Mỹ. Bạn phải cố gắng nghe hết những gì trong các đoạn hội
		thoại và đóng vai các nhân vật để luyện nói.</div>
		</div>
		</div>
		<div class="vb_box-5 vb_box-5-step3">
		<div class="vb_contents-descript-child-2">
		<div class="vb_box-5-item vb_title_step3">Đặc biệt nhất, bạn sẽ được
		gửi bài để giáo viên chấm điểm và nhận xét trong các phần: <span
			style="cursor: default;" onmouseout="hideticker(this)"
			onmouseover="showmessage('Học viết tiếng Anh qua tranh - có một bức ảnh - bạn phải viết 1 câu tiếng Anh nói về bức ảnh đó.',this)"><a
			href="http://www.tienganh123.com/hoc-viet-tieng-anh-qua-tranh"
			target="_blank">Học viết tiếng Anh qua tranh</a></span>, <span
			style="cursor: default;" onmouseout="hideticker(this)"
			onmouseover="showmessage('Học viết thư tiếng Anh - Có 1 bức thư bằng tiếng Anh, bạn phải đóng vai là người nhận để viết lại 1 bức thư khác để trả lời bức thư đó.',this)"><a
			href="http://www.tienganh123.com/viet-thu-phan-hoi" target="_blank">Học
		viết thư tiếng Anh</a></span>, <span style="cursor: default;"
			onmouseout="hideticker(this)"
			onmouseover="showmessage('Bạn nhận được 1 chủ đề, bạn cần viết 1 bài luận (essay) có khoảng 100 đến 250 từ bàn luận về chủ đề đó.',this)"><a
			href="http://www.tienganh123.com/viet-essay" target="_blank">Học viết
		bài luận bằng tiếng Anh </a><i>(essay)</i> </span>, <span
			style="cursor: default;" onmouseout="hideticker(this)"
			onmouseover="showmessage('Có 1 đoạn text bằng tiếng Anh, bạn phải gửi bài dịch tiếng Việt của đoạn text đó để giáo viên chấm điểm - có 2 trình độ dễ và khó.',this)"><a
			href="http://www.tienganh123.com/dich-anh-viet" target="_blank">dịch
		Anh - Việt</a></span>,<span style="cursor: default;"
			onmouseout="hideticker(this)"
			onmouseover="showmessage('Có 1 đoạn text bằng tiếng Việt, bạn phải gửi bài dịch tiếng Anh của đoạn text đó để giáo viên chấm điểm và nhận xét - có 2 trình độ dễ và khó.',this)">
		<a href="http://www.tienganh123.com/dich-viet-anh" target="_blank">dịch
		Việt - Anh</a></span>. Học viết và học dịch là cách giúp bạn nhớ được
		cấu trúc câu và từ vựng hiệu quả nhất. Lần đầu tiên ở Việt Nam, có
		giáo viên online chấm điểm bằng tay và sửa sai trực tiếp cho các bạn.
		</div>
		</div>
		</div>
		<div class="vb_box-6 vb_box-6-step4">
		<div class="vb_contents-descript-child-2">
		<div class="vb_box-6-item-1 vb_title_step4">Truy cập toàn bộ các bài
		học <span style="cursor: default;" onmouseout="hideticker(this)"
			onmouseover="showmessage('Chương trình học và luyện tập thêm dành cho học sinh phổ thông từ lớp 6 đến lớp 12.',this)">
		<a href="http://www.tienganh123.com/tieng-anh-pho-thong"
			target="_blank">tiếng Anh phổ thông</a></span> lớp <a
			href="http://www.tienganh123.com/tieng-anh-pho-thong-lop-6"
			title="Tiếng Anh lớp 6" target="_blank">6</a>, <a
			href="http://www.tienganh123.com/tieng-anh-pho-thong-lop-7"
			title="Tiếng Anh lớp 7" target="_blank">7</a>, <a
			href="http://www.tienganh123.com/tieng-anh-pho-thong-lop-8"
			title="Tiếng Anh lớp 8" target="_blank">8</a>, <a
			href="http://www.tienganh123.com/tieng-anh-pho-thong-lop-9"
			title="Tiếng Anh lớp 9" target="_blank">9</a>, <a
			href="http://www.tienganh123.com/tieng-anh-pho-thong-lop-10"
			title="Tiếng Anh lớp 10" target="_blank">10</a>, <a
			href="http://www.tienganh123.com/tieng-anh-pho-thong-lop-11"
			title="Tiếng Anh lớp 11" target="_blank">11</a>, <a
			href="http://www.tienganh123.com/tieng-anh-pho-thong-lop-12"
			title="Tiếng Anh lớp 11" target="_blank">12</a> và <a
			href="http://www.tienganh123.com/on-thi-dai-hoc"
			title="Ôn thi đại học môn tiếng Anh" target="_blank">Ôn thi Đại Học
		môn tiếng Anh</a>. Phần tiếng Anh phổ thông này được biên soạn bám sát
		theo khung giáo trình tiếng Anh đang được giảng dạy trong các trường
		phổ thông cơ sở và trung học trên toàn quốc, nhưng được trình bày sinh
		động, dễ hiểu, với đầy đủ audio, video - giúp các bạn học sinh luyện
		tập thi học kỳ, thi tốt nghiệp và thi đại học một cách tốt nhất.</div>
		</div>
		</div>
		<div class="vb_box-5 vb_box-5-step4">
		<div class="vb_contents-descript-child-2">
		<div class="vb_box-5-item vb_title_step5">Mục <span
			style="cursor: default;" onmouseout="hideticker(this)"
			onmouseover="showmessage('TOEIC (Test Of English for International Communication) - Chứng chỉ hàng đầu về đánh giá khả năng tiếng Anh trong công việc văn phòng và các công ty nước ngoài cũng như là một điều kiện bắt buộc để nhận bằng tốt nghiệp của nhiều trường ĐH & Cao Đẳng trên cả nước.',this)"><a
			href="http://www.tienganh123.com/luyen-thi-toeic-tienganh123"
			target="_blank">luyện thi TOEIC online</a></span> (Chứng chỉ tiếng
		Anh giao tiếp quốc tế của Mỹ) với những bài học từ vựng dễ hiểu, bài
		nghe phong phú và các mẹo, thủ thuật làm bài thi TOEIC sẽ giúp bạn có
		được điểm cao nhất trong kỳ thi chứng chỉ nổi tiếng này. Bên cạnh đó
		còn có hàng trăm <span style="cursor: default;"
			onmouseout="hideticker(this)"
			onmouseover="showmessage('Luyện tập Part 1 - Photographs.',this)"><a
			href="http://www.tienganh123.com/luyen-tap-part-1-photographs"
			target="_blank">bài luyện tập có ghi điểm</a></span> giúp bạn theo
		dõi được sự tiến bộ của mình. Ngoài ra bạn cũng có thể thi thử với
		những <span style="cursor: default;" onmouseout="hideticker(this)"
			onmouseover="showmessage('Đề thi thử TOEIC online.',this)"><a
			href="http://www.tienganh123.com/de-thi-thu-full" target="_blank">đề
		thi thử TOEIC online </a></span>để biết kết quả luôn.</div>
		</div>
		</div>
		<div class="vb_box-6 vb_box-6-step5">
		<div class="vb_contents-descript-child-2">
		<div class="vb_box-6-item-1 vb_title_step6">Thông qua phần nói miêu tả
		tranh <span style="cursor: default;" onmouseout="hideticker(this)"
			onmouseover="showmessage('Luyện nói tiếng Anh qua tranh - bạn phải miêu tả 1 bức tranh - giúp bạn sử dụng từ vựng, mẫu câu và biết cách miêu tả, kể lại 1 câu truyện rất tốt.',this)">
		<a href="http://www.tienganh123.com/luyen-noi-tieng-anh"
			target="_blank"> (picture description)</a></span>, <span
			style="cursor: default;" onmouseout="hideticker(this)"
			onmouseover="showmessage('Nghe và nhắc lại 1 đoạn text. Bạn được nghe mẫu 1 đoạn text - sau đó bạn phải nói lại đoạn đó - giúp bạn luyện đọc tiếng Anh thành thạo.',this)"><a
			href="http://www.tienganh123.com/luyen-doc-doan-van" target="_blank">
		phần nghe và nhắc lại (listen & repetition)</a></span>. Bạn ghi âm bài
		nói của mình rồi đưa lên website, được giáo viên chấm điểm và nhận
		xét. Hơn nữa bạn sẽ được học phát âm cơ bản từ đầu thông qua mục <span
			style="cursor: default;" onmouseout="hideticker(this)"
			onmouseover="showmessage('Học phát âm tiếng Anh từ đầu.',this)"><a
			href="http://www.tienganh123.com/phat-am-tieng-anh-co-ban"
			target="_blank">phát âm cơ bản</a></span> .</div>
		</div>
		</div>
		<div class="vb_box-5 vb_box-5-step6">
		<div class="vb_contents-descript-child-2">
		<div class="vb_box-5-item vb_title_step7">Học qua các bài học Ngữ
		Pháp, Từ Vựng từ các thầy giáo trên thế giới thông qua Youtube: <span
			style="cursor: default;" onmouseout="hideticker(this)"
			onmouseover="showmessage('TiếngAnh123 sẽ cung cấp cho bạn lời nói và dịch nghĩa cho các bạn các lời nói đó bên cạnh. Bạn sẽ hiểu hoàn toàn thầy giáo nước ngoài nói gì. Điều này sẽ luyện cho bạn kỹ năng nghe hiểu, từ vựng cực kỳ tốt. Coi như các bạn đang ở Việt nam mà có thể tham gia và hiểu được các bài giảng của các giáo viên nước ngoài trên Youtube.',this)"><a
			href="http://www.tienganh123.com/hoc-tieng-anh-qua-youtube"
			target="_blank"> Học Tiếng Anh qua video Youtube </a></span>hoặc <span
			style="cursor: default;" onmouseout="hideticker(this)"
			onmouseover="showmessage('Học ngữ pháp qua video Youtube.',this)"><a
			href="http://www.tienganh123.com/hoc-ngu-phap-tieng-anh-qua-youtube"
			target="_blank">Học ngữ pháp qua video Youtube</a></span> Các mục: <span
			style="cursor: default;" onmouseout="hideticker(this)"
			onmouseover="showmessage('Với 1000 từ vựng cơ bản tiếng Anh được sử dụng nhiều nhất - các bạn đã có thể sử dụng tiếng Anh một cách khá cơ bản. Phần này có 100 bài, mỗi bài 10 từ, nếu chăm chỉ 3 tháng sau vốn từ vựng của  bạn sẽ được cải thiện rất nhiều.',this)"><a
			href="http://www.tienganh123.com/1000-tu-vung-tieng-anh-co-ban"
			target="_blank">1000 từ vựng tiếng Anh cơ bản</a></span>, <span
			style="cursor: default;" onmouseout="hideticker(this)"
			onmouseover="showmessage('6000 từ tiếng Anh thông dụng.',this)"><a
			href="http://www.tienganh123.com/6000-tu-tieng-anh-thong-dung"
			target="_blank">6000 từ tiếng Anh thông dụng </a></span> giúp bạn ôn
		và luyện tập từ vựng, mẫu câu cơ bản nhất của tiếng Anh.<br>
		Khi gặp từ mới, bạn chỉ cần click đúp vào từ đó để tra nghĩa ngay lập
		tức trên website.</div>
		</div>
		</div>
		<div class="vb_box-6 vb_box-6-step7">
		<div class="vb_contents-descript-child-2">
		<div class="vb_box-6-item-1 vb_title_step8">Thông qua các video tiếng
		Anh có phụ đề tiếng Anh và lời dịch tiếng Việt gồm nhiều thể loại từ <span
			style="cursor: default;" onmouseout="hideticker(this)"
			onmouseover="showmessage('Những video này với giọng Anh Mỹ chuẩn, vừa giúp các bạn cập nhật kiến thức lại vừa giúp các bạn làm quen với giọng nói, phong cách của người nước ngoài thật sự. Nó cũng sẽ giúp các bạn học được những từ vựng thực tế và phong phú. Đặc biệt video này hỗ trợ nghe trên các thiết bị di động thông minh smartphone, máy tính bảng như iPhone, iPad, và các thiết bị chạy trên hệ điều hành Android.',this)"><a
			href="http://www.tienganh123.com/menu/Video" target="_blank">giải
		trí, kinh doanh, sức khỏe đến công nghệ, du lịch thể thao, môi
		trường...</a></span> bạn sẽ được làm quen với các mẫu câu, từ vựng
		tiếng Anh đa dạng, phong phú trong thực tế. Không cần phải ra nước
		ngoài bạn cũng có một môi trường để học và nghe tiếng Anh thú vi.</div>
		</div>
		</div>
		<div class="vb_box-5 vb_box-5-step8">
		<div class="vb_contents-descript-child-2">
		<div class="vb_box-5-item vb_title_step9">Với giọng Anh Mỹ chuẩn, tốc
		độ chậm, dễ nghe của phần luyện nghe qua <span
			style="cursor: default;" onmouseout="hideticker(this)"
			onmouseover="showmessage('Giọng Anh Mỹ chuẩn, tốc độ tự nhiên, phần này sẽ giúp các bạn luyện nghe giọng Anh - Mỹ để chuẩn bị các kỳ thi TOEIC hay giao tiếp sau này.',this)"><a
			href="http://www.tienganh123.com/luyen-nghe-tieng-anh-qua-voa-tv-video"
			target="_blank">VOA (Voice of America)</a></span>, dí dỏm, linh hoạt
		của <span style="cursor: default;" onmouseout="hideticker(this)"
			onmouseover="showmessage('Những bản tin của CNN dành cho sinh viên được dịch - các bạn không những được cập nhật tin tức trên thế giới mà còn học cách dùng từ ngữ sinh động và thực tế nhất. Video được đặt tại server ở Việt Nam nên giúp các bạn xem được chất lượng tốt. Lại có lời hội thoại ở bên phải giúp các bạn theo dõi được trong video nói gì. Hãy học tiếng Anh thực tế - đừng dừng lại tiếng Anh trên sách vở. Xem CNN cũng rất có ích cho các bạn muốn luyện thi TOEIC vì đây là giọng Anh Mỹ.',this)"><a
			href="http://www.tienganh123.com/hoc-tieng-anh-qua-cnn"
			target="_blank">CNN</a></span>, hay thời sự và chính luận của <span
			style="cursor: default;" onmouseout="hideticker(this)"
			onmouseover="showmessage('Học tiếng Anh qua bản tin BBC.',this)"><a
			href="http://www.tienganh123.com/hoc-tieng-anh-qua-bbc"
			target="_blank">BBC</a></span> (tất cả đều có lời hội thoại ở bên
		phải giúp bạn theo dõi được trong video nói gì) sẽ không chỉ giúp bạn
		cập nhật các tin tức trên thế giới mà còn học cách dùng từ ngữ sinh
		động và thực tế nhất.</div>
		</div>
		</div>
		<div class="vb_box-6 vb_box-6-step9">
		<div class="vb_contents-descript-child-2">
		<div class="vb_box-6-item-1 vb_title_step10">Bạn sẽ được xem, nghe và
		hiểu được nội dung những bài phỏng vấn, diễn thuyết, phát biểu hay
		tranh luận của những người nổi tiếng trên thế giới như <span
			style="cursor: default;" onmouseout="hideticker(this)"
			onmouseover="showmessage('Học tiếng Anh với người nổi tiếng.',this)"><a
			href="http://www.tienganh123.com/hoc-tieng-anh-voi-nguoi-noi-tieng"
			target="_blank"> Bill Gates, Steven Jobs, Barack Obama</a> </span>và
		<span style="cursor: default;" onmouseout="hideticker(this)"
			onmouseover="showmessage('Học tiếng Anh qua các bài phỏng vấn, nói chuyện với những người nổi tiếng khác như David Beckham, Michael Jackson, Hillary Clinton etc...',this)"><a
			href="http://www.tienganh123.com/Nh%E1%BB%AFng%20ng%C6%B0%E1%BB%9Di%20n%E1%BB%95i%20ti%E1%BA%BFng%20kh%C3%A1c"
			target="_blank">những người nổi tiếng khác như: David Beckham,
		Michael Jackson, Hillary Clinton ... </a></span></div>
		</div>
		</div>
		<div class="vb_box-5 vb_box-5-step10">
		<div class="vb_contents-descript-child-2">
		<div class="vb_box-5-item vb_title_step11">Vừa học vừa giải trí,
		TiếngAnh123 sẽ giúp bạn rèn khả năng tiếng Anh của mình để hiểu được
		nội dung nguyên gốc khi <span style="cursor: default;"
			onmouseout="hideticker(this)"
			onmouseover="showmessage('TiếngAnh123.Com cố gắng tìm những trích đoạn bộ phim hay nhất, có ý nghĩa nhất - là các film trailer để mọi người có thể xem, nghe, hiểu và học cách biểu cảm trong giao tiếp. Đây là cách học tiếng Anh giao tiếp khá hiệu quả vì các bạn sẽ thấy được trong đời thường người bản ngữ sử dụng ngôn ngữ ra sao - Lời hội thoại được dịch bên cạnh giúp bạn hiểu một cách dễ dàng. Bạn có thể tạm dừng hay tua lại.',this)"><a
			href="http://www.tienganh123.com/hoc-tieng-anh-qua-phim-trailer"
			target="_blank">xem trích đoạn giới thiệu một bộ phim (film trailer)</a></span>,
		nghe một <span style="cursor: default;" onmouseout="hideticker(this)"
			onmouseover="showmessage('Học tiếng Anh qua bài hát - có lời dịch, bài tập điền từ và giải thích nghĩa 1 số câu thường dùng.',this)"><a
			href="http://www.tienganh123.com/hoc-tieng-anh-qua-bai-hat"
			target="_blank">bài hát</a></span> hay đọc những mẩu <span
			style="cursor: default;" onmouseout="hideticker(this)"
			onmouseover="showmessage('Thông qua các câu truyện cười có audio và lời dịch- các bạn vừa giải trí vừa học từ vựng và mẫu câu hay dùng hàng ngày.',this)"><a
			href="http://www.tienganh123.com/hoc-tieng-anh-qua-truyen-cuoi"
			target="_blank">truyện cười</a></span>. Đây là một trong những nhu
		cầu giải trí rất thường xuyên của bất kỳ người nào.</div>
		</div>
		</div>
		<div class="vb_box-6 vb_box-6-step11">
		<div class="vb_contents-descript-child-2">
		<div class="vb_box-6-item-1 vb_title_step12">Trong mục <a
			href="http://www.tienganh123.com/hoc-qua-dich" target="_blank"
			title="Học tiếng Anh qua dịch">học tiếng Anh qua dịch</a>, thông qua
		việc phân tích cặn kẽ những câu tiếng Anh trong các video từng từ,
		từng cấu trúc nhỏ nhất, giáo viên sẽ giúp bạn hiểu cặn kẽ chức năng và
		thể loại các từ và cấu trúc trong một câu tiếng Anh.</div>
		</div>
		</div>
		<div class="vb_contents-descript-child"><img
			src="http://data.tienganh123.com/images/quyenloithanhvien/16_van_van_conratnhieu.gif"
			alt="">
		<div class="vb_slide_hocvien">
		<div id="vb_slide_content" class="vb_slide_content" alt='1'>
		<div class="vb_slide_avata"><img
			src="http://www.tienganh123.com/file/news/huongdan/bai10/images/lbn_img_avatars2.jpg"
			alt=""></div>
		<div class="vb_slide_nhanxet">Khi đăng ký thành viên và học thử những
		bài học trên trang web này, tôi quyết định mua thẻ để trở thành thành
		viên VIP và TiếngAnh123.com đã thực sự làm thay đổi việc học tiếng Anh
		của tôi kể từ lúc đó.Quả thật TiếngAnh123.com là trang web học tiếng
		anh hiệu quả nhất mà tôi từng được biết. Với giao diện website được
		thiết kế bắt mắt, rõ ràng, các bài học được sắp xếp rõ rằng theo một
		cấu trúc chặt chẽ giúp học viên có thể tìm thấy một cách nhanh chóng.
		<div class="vb_address">
		<h3>PHẠM THỊ XUÂN DUNG</h3>
		<span>97 Bàu Cát 4, P.14, Q.Tân Bình, TP Hồ Chí Minh</span></div>
		</div>
		</div>
		<div id="vb_slide_content" class="vb_slide_content" alt='2'>
		<div class="vb_slide_avata"><img
			src="http://www.tienganh123.com/file/news/huongdan/bai10/images/lbn_img_avatars1.jpg"
			alt=""></div>
		<div class="vb_slide_nhanxet">Một lần tình cờ biết được trang web
		TiếngAnh123.com, tôi đã vào học thử. Ban đầu chỉ với ý nghĩ rằng:
		"chắc cũng giống như vài website đã học qua", nhưng tôi thực sự ngạc
		nhiên về các cấu trúc bài bản mà các giáo viên TiếngAnh123.com đã dày
		công biên soạn, có đủ các phần, từ các bài học trên lớp theo khối học
		đến phần tiếng Anh cơ bản, tiếng Anh giao tiếp, luyện nghe, luyện đọc,
		được thi thử TOEIC… đối với tôi, trang web quá tuyệt vời !
		<div class="vb_address">
		<h3>LÊ THỊ DUYÊN</h3>
		<span>Thôn 14A-xã Đăkpet-huyện Đăkglei-tỉnh Kon Tum</span></div>
		</div>
		</div>
		<div id="vb_slide_content" class="vb_slide_content" alt='3'>
		<div class="vb_slide_avata"><img
			src="http://www.tienganh123.com/file/news/huongdan/bai10/images/lbn_img_avatars.jpg"
			alt=""></div>
		<div class="vb_slide_nhanxet">Một lần, mình lướt web và gặp
		TiếngAnh123 và thấy phần viết luận, các bạn tham gia rất nhiệt tình và
		viết rất hay, mình vui lắm, quyết định mua thẻ vip và bắt đầu quá
		trình học của mình. Lúc đầu đến với TiếngAnh123 chỉ vì muốn cải thiện
		writing thôi, nhưng càng ngày, càng tìm hiểu thêm về web, mình cảm
		thấy hứng thú hơn vì có tất cả các kỹ năng cần thiết khác. Grammar đầy
		đủ những gì mình cần, phong phú, đa dạng và đặc biệt mình rất thích
		các slide bài giảng ngộ nghĩnh, dễ thương và có thêm phần âm thanh
		nữa.
		<div class="vb_address">
		<h3>HOÀNG THU THỦY</h3>
		<span>71/11B Lý Tự Trọng – Q.Ninh Kiều – TP Cần Thơ.</span></div>
		</div>
		</div>
		<div id="vb_slide_content" class="vb_slide_content" alt='4'>
		<div class="vb_slide_avata"><img
			src="http://www.tienganh123.com/file/news/huongdan/bai10/images/lbn_img_avatars4.jpg"
			alt=""></div>
		<div class="vb_slide_nhanxet">Trang web được thiết kế khá bắt mắt và
		rất hay làm cho những người khác có ấn tượng sâu sắc khi tiếp xúc lần
		đầu với trang tienganh123.com. Việc thiết kế đẹp, có khoa học cũng cho
		thấy trang web có chất lượng cao, phản ánh mức độ tâm huyết cao, sự tỉ
		mỉ của các thành viên sáng lập nhằm đem lại môi trường học tập hiệu
		quả cho các học viên khi đến với trang web.
		<div class="vb_address">
		<h3>PHẠM THỊ HỒNG ĐÀO</h3>
		<span>180, ấp 5, xã Chánh Phú Hòa, huyện Bến Cát, tỉnh Bình Dương.</span>
		</div>
		</div>
		</div>
		<div id="vb_slide_content" class="vb_slide_content" alt='5'>
		<div class="vb_slide_avata"><img
			src="http://www.tienganh123.com/file/news/huongdan/bai10/images/lbn_img_avatars5.jpg"
			alt=""></div>
		<div class="vb_slide_nhanxet">Tôi đến với TiếngAnh123.com một cách rất
		tình cờ. Khi lên Google để tìm kiếm một số bài hát để dạy cách phát âm
		bảng chữ cái tiếng Anh cho bé yêu, tôi đã gặp "người bạn" có tên
		TiếngAnh123.com. Những video clip nhỏ đã làm tôi cảm thấy thích thú,
		bé yêu thì khoái chí vừa đọc, vừa nhún nhảy theo nhạc. Vốn bản tính tò
		mò của dân chuyên ngoại ngữ, tôi khám phá và hoàn toàn bị cuốn theo
		những bài học cũng như những bài Test phong phú của TiếngAnh123.com.
		<div class="vb_address">
		<h3>CHẾ THỊ THANH HUYỀN</h3>
		<span>Số 1A Hẻm 29/70/16, phố Khương Hạ, Khương Đình, Thanh Xuân, Hà
		Nội.</span></div>
		</div>
		</div>
		<div id="vb_slide_content" class="vb_slide_content" alt='6'>
		<div class="vb_slide_avata"><img
			src="http://www.tienganh123.com/file/news/huongdan/bai10/images/lbn_img_avatars6.jpg"
			alt=""></div>
		<div class="vb_slide_nhanxet">Nếu bạn là một người chưa nắm rõ về
		tiếng Anh, bị mất căn bản, bạn có thể học TiếngAnh123 qua các Bài học
		cơ bản. Nếu kĩ năng nghe của bạn còn yếu và muốn khắc phục nó, mỗi
		ngày bạn có thể nghe các bài học luyện nghe trên TiếngAnh123. Tôi tin
		là kĩ năng nghe của bạn sẽ không ngừng được cải thiện và nâng cao. Bởi
		tôi đã thực hiện nó và tôi đã đạt được cái mà tôi muốn.
		<div class="vb_address">
		<h3>LƯƠNG THỊ KIỀU TRINH</h3>
		<span>788/77B, Nguyễn Kiệm, Phường 3, Quận Gò Vấp, TP HCM.</span></div>
		</div>
		</div>
		<div id="vb_slide_content" class="vb_slide_content" alt='7'>
		<div class="vb_slide_avata"><img
			src="http://www.tienganh123.com/file/news/huongdan/bai10/images/lbn_img_avatars7.jpg"
			alt=""></div>
		<div class="vb_slide_nhanxet">Bây giờ nói đến bản thân mình chút nhé!
		Mình học với TiếngAnh123.com cũng được một thời gian rồi. Tuy là ngắn
		nhưng mình cũng nhận thấy được sự tiến bộ. Học tập và công viêc bộn bề
		nên mình không dành nhiều thời gian cho việc học tiếng anh được. Nhưng
		mình thấy mỗi ngày mình càng hứng thú hơn với ngôn ngữ này. Có lẽ cảm
		giác đó chính là do TiếngAnh123.com mang lại. Mình luôn chia sẻ với
		những người bạn muốn học tiếng anh website này.
		<div class="vb_address">
		<h3>NGUYỄN THỊ DOAN</h3>
		<span>Phòng 19 nhà 3 ktx ĐH Kinh Tế Quốc Dân</span></div>
		</div>
		</div>
		<div id="vb_slide_content" class="vb_slide_content" alt='8'>
		<div class="vb_slide_avata"><img
			src="http://www.tienganh123.com/file/news/huongdan/bai10/images/lbn_img_avatars8.jpg"
			alt=""></div>
		<div class="vb_slide_nhanxet">Từ ngày tham gia học TiếngAnh123, tôi
		như một nhân viên tiếp thị, quảng cáo. Gặp ai tôi cũng động viên họ
		học tiếng Anh vì lợi ích này hoặc vì lợi ích kia, rồi thì khuyên họ
		đăng ký vào thành viên của lớp học, bày cho họ cách đăng ký để nạp
		thẻ, rồi hướng dẫn cho họ học thế nào để đạt hiệu quả cao nhất.
		<div class="vb_address">
		<h3>VÕ THỊ HUỆ</h3>
		<span>104 Quang Trung, Thị trấn Phước An, huyện Krông Păc,Tỉnh Đaklak.</span>
		</div>
		</div>
		</div>
		<div id="vb_slide_content" class="vb_slide_content" alt='9'>
		<div class="vb_slide_avata"><img
			src="http://www.tienganh123.com/file/news/huongdan/bai10/images/lbn_img_avatars9.jpg"
			alt=""></div>
		<div class="vb_slide_nhanxet">TiếngAnh123 đã giúp tôi hết sợ khi học
		môn này và tôi đã thích học Tiếng Anh vì tôi đã giỏi lên rồi mà, chẳng
		có gì phải sợ. Trang web này khác xa những trang web Tiếng Anh khác.
		Nó có đầy đủ các phần học hơn, còn website Tiếng Anh khác thì làm cho
		những người xem khó hiểu, nó không có phần gì để mà học cả, nhiều
		người vào xem nói chỉ là những cái nhảm nhí, không giúp gì được cho
		việc học Tiếng Anh.
		<div class="vb_address">
		<h3>VÕ QUỐC CƯỜNG</h3>
		<span>Tổ 3, ấp 3, xã Sông Xoài, huyện Tân Thành, tỉnh BRVT. Tiệm
		internet Quốc Cường.</span></div>
		</div>
		</div>
		<div id="vb_slide_content" class="vb_slide_content" alt='10'>
		<div class="vb_slide_avata"><img
			src="http://www.tienganh123.com/file/news/huongdan/bai10/images/lbn_img_avatars10.jpg"
			alt=""></div>
		<div class="vb_slide_nhanxet">Theo em thì TiếngAnh123 rất sáng tạo.Đưa
		những hình ảnh để giúp chúng em học hiểu hơn,rồi có đủ các phần rèn
		luyện cho mọi lứa tuổi.Đưa ra phần test kiểm tra trình độ và có những
		cấp khác như kiến gỗ,kiến thép,kiến bạc,…để chúng em cố gắng học
		hơn.Trương trình còn có thành viên vip,goldenkisd làm nhiều bài tập
		hay và khó hơn còn được tham gia vào những cuộc thi đầy thú vị.
		<div class="vb_address">
		<h3>MAI THỊ HÀ TRANG</h3>
		<span>Xóm 2 Hậu Trạch - Xã Nga Thạch-Huyện Nga Sơn-Tỉnh Thanh Hoá</span>
		</div>
		</div>
		</div>
		<div class="vb_pagging"><span class="vb_slide_pre"></span> <span
			id="vb_range_slide"> </span> <span class="vb_slide_next"></span></div>
		</div>
		<div class="vb_baochi">
		<div class="vb_videobaochi">
		<div class="vb_video_des"><iframe width="320" height="206"
			src="http://www.youtube.com/embed/z7Bd0EMe9Eo?rel=0" frameborder="0"
			allowfullscreen></iframe> <span>Chương trình <span class="vb_bold">“10
		phút cập nhật”</span> trên VTC2 nói về lợi ích của việc học tiếng Anh
		trực tuyến trên website TiếngAnh123.com </span></div>
		<div class="vb_video_des1">
		<ul>
			<li class="vb_video_des1_dantri"><a
				href="http://dantri.com.vn/giao-duc-khuyen-hoc/website-tienganh123com-nhan-danh-hieu-sao-khue-2013-722431.htm"
				title="TiếngAnh123 nhận danh hiệu Sao Khuê 2013" target="_blank">Website
			TiếngAnh123.Com nhận danh hiệu Sao Khuê 2013</a> <br>
			<span class="vb_orange-3">dantri.com.vn</span></li>
			<li class="vb_video_des1_geck"><a
				href="http://kenh14.vn/hoc-duong/hoc-tieng-anh-hieu-qua-khong-nham-chan-voi-tienganh123com-20120731082513347.chn"
				title="Học tiếng Anh – Hiệu quả, không nhàm chán với TiengAnh123.com "
				target="_blank">Học tiếng Anh – Hiệu quả, không nhàm chán với
			TiengAnh123.com </a> <br>
			<span class="vb_orange-3">kenh14.vn</span></li>
			<li class="vb_video_des1_k14"><a
				href="http://genk.vn/internet/tienganh123com-nang-cap-thay-doi-giao-dien-va-chuan-bi-don-thanh-vien-thu-1-trieu-20130304122434456.chn"
				title="TiếngAnh123 đón thành viên thứ 1 triệu" target="_blank">TiếngAnh123.Com
			nâng cấp, thay đổi giao diện và chuẩn bị đón thành viên thứ 1 triệu</a>
			<br>
			<span class="vb_orange-3">Genk.vn</span></li>
		</ul>
		</div>
		</div>
		</div>
		<div class="vb_tip">Hơn 1.1 triệu người đã lựa chọn và đã gặt hái
		những hiệu quả rõ rệt trong việc học tiếng Anh trực tuyến. <span
			class="vb_orange vb_bold">Bạn còn chờ gì nữa? Đặt mua thẻ VIP (trị
		giá <strike>250.000 VNĐ</strike> 200,000 VNĐ - giảm 20% từ 6/2 đến hết
		28/2/2014 trong chương trình khuyến mại "Chào Xuân Giáp Ngọ 2014")
		ngay hôm nay </span>để bắt đầu khám phá những hiệu quả bất ngờ mà
		TiếngAnh123 sẽ đem lại cho bạn. <br>
		<br>
		Hãy tưởng tượng chỉ với <span class="vb_orange vb_bold">~ 20.000 VNĐ
		mỗi tháng (tương đương với 1 ly cafe)</span> bạn đã là thành viên VIP
		của TiếngAnh123.com với những quyền lợi vượt trội. Chẳng còn khoản đầu
		tư nào tốt, có ích và hiệu quả hơn đâu các bạn ạ. Tiếng Anh sẽ làm
		thay đổi số phận bạn và TiếngAnh123.com sẽ thay đổi cách bạn học tiếng
		Anh.</div>
		<div class="vb_tip1">
		<div class="vb_tit_cachmuathe"><a href="" title="..." target="_blank">Cách
		mua thẻ học tiếng Anh trực tuyến VIP Card</a> <img
			src="http://data.tienganh123.com/images/quyenloithanhvien/19_VIP_Card_1.png"
			alt=""></div>
		</div>
		<div class="vb_tip2">Thẻ học tiếng Anh trực tuyến <span
			class="vb_bold">VIP card</span> trị giá <span
			class="vb_orange vb_bold"><strike>250.000 VNĐ</strike> 200,000 VNĐ -
		giảm 20% từ 6/2 đến hết 28/2/2014</span> giúp bạn trở thành <span
			class="vb_orange vb_bold">thành viên VIP</span> trên TiếngAnh123.com
		trong <span class="vb_orange vb_bold">1 năm (365 ngày)</span> tính từ
		ngày các bạn nạp mã thẻ vào tài khoản.</div>
		<div class="vb_form_the">
		<div class="vb_box-7">
		<h3 class="vb_form_the_title" id="formDatThe">Bạn hãy điền đầy đủ
		thông tin vào mẫu dưới đây và kích vào nút "Đặt Mua Thẻ":</h3>
		<form class="vb__form_dat_the" action="/dat-the/vip" method="POST">
		<div class="vb__row-1">
		<div class="vb__field vb__field_margin_right30">
		<h4>Họ và tên:</h4>
		<input class="vb__input_text" type="text" name="fullname"></div>
		<div class="vb__field">
		<h4>Số điện thoại:</h4>
		<input class="vb__input_text" type="text" name="phone"></div>
		</div>
		<div class="vb__row-1">
		<div class="vb__field">
		<h4>Địa chỉ nhận thẻ:</h4>
		<textarea class="vb_textarea" name="address" cols="62" rows="2"></textarea>
		</div>
		</div>
		<div class="vb_action_submit"><input type="image"
			src="http://data.tienganh123.com/images/quyenloithanhvien/20_Dat_mua_the.gif"
			name="card_order" value="Đặt mua thẻ"></div>
		</form>

		<center><img
			src="http://data.tienganh123.com/images/popup/popup_tet2014.jpg"></center>
		<h3 class="vb_note_km">(Từ 6/2 đến hết 28/2/2014 TiếngAnh123 giảm 20%
		giá thẻ cho tất cả các khách hàng trong chương trình khuyến mại "Chào
		Xuân Giáp Ngọ 2014").</h3>
		<ul class="vb_itemkm">
			<li>Thẻ <span class="vb_orange">VIP</span> còn <span
				class="vb_orange">200,000 VNĐ</span>/1 năm</li>
			<li>Thẻ <span class="vb_orange">GoldenKids</span> còn <span
				class="vb_orange">240,000 VNĐ</span>/1 năm.</li>
		</ul>


		<div class="vb_note_card">
		<div class="vb__content_note"><span class="vb_orange-1 vb_bold">Thẻ sẽ
		được giao miễn phí.</span> Nếu bạn ở Hà Nội thì nhân viên của
		TiếngAnh123.com sẽ mang thẻ đến tận nơi trong vòng 24h. <br>
		<br>
		<span class="vb_bold">Còn nếu bạn ở tp Hồ Chí Minh và các tỉnh khác</span>
		thì thẻ sẽ được gửi qua dịch vụ <span class="vb_orange-1 vb_bold">chuyển
		phát nhanh EMS của bưu điện</span>. Trong vòng <span
			class="vb_orange-1 vb_bold">2 đến 3 ngày</span> bạn sẽ nhận được thẻ.
		<br>
		<br>
		Giá của thẻ VIP là <span class="vb_orange-1 vb_bold"><strike>250.000
		VNĐ</strike> - 200,000 VNĐ - giảm 20% từ 6/2 đến hết 28/2/2014</span>
		<span class="vb_bold">đã bao gồm thuế VAT và mọi chi phí vận chuyển</span>
		- bạn <span class="vb_orange-1 vb_bold">KHÔNG</span> phải thêm bất kỳ
		một phí gì khác. Khi nhận thẻ <span class="vb_bold">bạn chỉ cần trả số
		tiền</span> <span class="vb_orange-1 vb_bold">200.000 VNĐ</span> cho
		người giao thẻ của TiếngAnh123.Com hoặc nhân viên bưu điện.</div>
		</div>
		<h3 class="vb_title-12">Một số câu hỏi thường gặp?</h3>
		</div>
		</div>
		<div class="vb_slide_2">
		<ul>
			<li><span id='vb_item_slide' class="vb_slide_arrow_noacti_down">Cách
			sử dụng thẻ VIP trên TiếngAnh123.com?</span>
			<div class="vb_slide_2_content"><span class="vb_bold">Bước 1</span>:
			<a href="http://www.tienganh123.com/register" target="_blank"
				class="vb_blue-1">Đăng ký thành viên trên</a> TiếngAnh123.com nếu
			bạn chưa có tài khoản.<br>
			<br>

			<span class="vb_bold">Bước 2</span>: Nhận thẻ và cào nhẹ lớp tráng
			bạc phía sau mặt thẻ để biết 16 chữ số mã thẻ<br>
			<br>

			<span class="vb_bold">Bước 3</span>: Đăng nhập vào website với tên
			đăng nhập và mật khẩu đã đăng ký<br>
			<br>

			<span class="vb_bold">Bước 4</span>: Nhấn vào nút nạp thẻ ở phía trên<br>
			<br>

			<span class="vb_bold">Bước 5</span>: Điền mã thẻ vào ô mã thẻ và nhấn
			nút nạp thẻ để hoàn tất<br>
			<br>

			<span class="vb_bold vb_orange">Lưu ý:</span><br>
			<br>

			<i> - Ngay sau khi có thông báo nạp thẻ thành công, bạn đã trở thành
			thành viên VIP trong <span class="vb_bold">365 ngày và không phải nạp
			lại thẻ nữa.</span><br>
			- Bạn chỉ có thể nạp tiếp thẻ khi thời hạn VIP của bạn còn <span
				class="vb_bold"><90 ngày</span>. (Bạn sẽ được cộng thêm 365 ngày khi
			nạp tiếp thẻ vào thời gian này) </i></div>
			</li>
			<li><span id='vb_item_slide' class="vb_slide_arrow_noacti_down">Tôi
			không có tiền để đăng ký mua thẻ VIP - phải làm sao?</span>
			<div class="vb_slide_2_content">Đúng là các bạn học sinh thì chưa có
			tiền. Nhưng các bạn hãy nói chuyện đó với người thân của mình và hỏi
			xem 250 nghìn có xứng đáng để đầu tư cho các bạn học tiếng Anh 1 năm
			hay không? Nếu giỏi tiếng Anh, bạn sẽ có 1 mức thu nhập gấp 2, 3 thậm
			chí 10 lần khi bạn không biết tiếng Anh.</div>
			</li>
			<li><span id='vb_item_slide' class="vb_slide_arrow_noacti_down">Sao
			tôi đã đăng ký lâu (>1 ngày) rồi mà không nhận được tin gì từ
			TiếngAnh123?</span>
			<div class="vb_slide_2_content">Chắc chắn chúng tôi đã cố gắng liên
			hệ với bạn nhưng có thể lúc đó bạn tắt máy, hay không nghe máy hoặc
			cũng có thể số điện thoại bạn ghi sai, trong trường hợp này bạn hãy
			gọi điện trực tiếp cho số điện thoại 0436628077 trong giờ hành chính
			để đặt hàng trực tiếp.</div>
			</li>
			<li><span id='vb_item_slide' class="vb_slide_arrow_noacti_down">Thẻ
			VIP khác thẻ GoldenKids ở điểm nào?</span>
			<div class="vb_slide_2_content">Trên TiếngAnh123.Com có 2 loại thẻ -
			Thẻ VIP dành cho học sinh phổ thông từ lớp 6 đến lớp 12, sinh viên và
			người đi làm. Thẻ GoldenKids dành cho trẻ em từ 4 đến 12 tuổi. Nếu
			quan tâm đến thẻ GoldenKids mời bạn truy cập vào <a
				href="http://www.tienganh123.com/huong-dan/2138-chuong-trinh-hoc-tieng-anh-tre-em-online-goldenkids.html"
				title="Thẻ GoldenKids" target="_blank">link này để biết thêm chi
			tiết</a>.</div>
			</li>
		</ul>
		</div>
		<div class="vb_box-7">
		<div class="vb__hotline"><span class="vb_green"> Số hotline trợ giúp</span>:
		<span class="vb_bold vb_orange-1">0919434830</span> (8 a.m. - 9 p.m.
		-7/7) <br>
		<span class="vb_green">Hoặc số điện thoại cố định</span>: <span
			class="vb_bold vb_orange-1">0473053868 - 0436628077</span> (8 a.m. -
		9 p.m. -7/7) <br>
		<span class="vb___other">(Ở nước ngoài - bạn có thể nhờ người thân ở
		Việt Nam nhận giúp rồi gửi (đọc) mã số thẻ)</span></div>
		<div class="vb__end"><img
			src="http://data.tienganh123.com/images/quyenloithanhvien/23_cat_jpg_250.gif"
			alt=""></div>
		</div>
		</div>
		</div>
		</div>
		<img
			src="http://data.tienganh123.com/images/quyenloithanhvien/20_Dat_mua_the_hover.gif"
			alt="" width="0" height="0"></img></div>
		</div>


		</div>



		<div class="space5"></div>
		<div class="lik_box">
		<div class="lik_box_l"></div>
		<div class="like" style="width: 96%">
		<div class="ghinho"><a href="javascript:;" title="Ghi nhớ bài học"
			onclick="remember_lesson('L3F1YW5nLWNhby85NzcwLWFkbGl0ZS5odG1s','remember');">Ghi
		nhớ bài học</a></div>
		<div class="dsyeuthich ghinho"><a href="javascript:;"
			title="Đưa vào danh sách yêu thích"
			onclick="remember_lesson('L3F1YW5nLWNhby85NzcwLWFkbGl0ZS5odG1s','favorite');">Đưa
		vào danh sách yêu thích</a></div>
		<div id="fblike" class="fb-like" data-href="" data-send="false"
			data-layout="button_count" data-width="90" data-show-faces="false"></div>
		</div>
		<div class="lik_box_r"></div>
		<div id="show_less_option"></div>
		</div>
		<div class="space5"></div>


		<div id="comment_other">
		<div class="compo_left_gr"><script type="text/javascript">   
    function load_comment_pages_news(page,agrm,mem,ft){
        var offset = $(agrm).attr('id');
        var limit = $(agrm).attr('class');
        var gv = $(agrm).attr('gv');                
        
        $(".pagging_comment a").removeAttr("style")
        var url = 'http://www.tienganh123.com/mod/load_comment_pages.php';
        url = url+'?url='+page+'&of='+offset+'&lm='+limit+'&cid='+Math.random()+"";       
        //Neu la more theo fillter
        if(mem != '')
            url = url+'&mem='+mem;
        if(ft != '')
            url = url+'&ft='+ft;
            
        $.get(url, function(data){            
            if(data == ''){
                        alert('Trang này không có dữ liệu nào');
                        return false;
            }
            data = jQuery.parseJSON(data)                        
            
            if(gv != undefined)
               {
                   $(agrm).css('color','red'); 
                   $('#listcomm').html(data.content);
                    var postCm = $(".lik_count_comment").offset()
                    $('html, body').animate({scrollTop:postCm.top},300);
               } 
            else    
                {                    
                    var postCm = $(agrm).offset()
                        $('html, body').animate({scrollTop:postCm.top},300);
                    if(data.more)
                       $(agrm).attr('id',data.more.offset); 
                    else
                       $(agrm).parent().hide();
                    $('.info_cus_box').append(data.content);
                }            
            
            init_comment();                        
            
            if(data.content.indexOf('.mp3')>0 || data.content.indexOf('.MP3')>0){
                $('.jquery_jplayer_comment').each(function(i){		
                    addAudioLong(this,i,isIOS);					
		      });
            }
        });   
        return false;
    }
    function utf8_decode (str_data) {
  // http://kevin.vanzonneveld.net
  // +   original by: Webtoolkit.info (http://www.webtoolkit.info/)
  // +      input by: Aman Gupta
  // +   improved by: Kevin van Zonneveld (http://kevin.vanzonneveld.net)
  // +   improved by: Norman "zEh" Fuchs
  // +   bugfixed by: hitwork
  // +   bugfixed by: Onno Marsman
  // +      input by: Brett Zamir (http://brett-zamir.me)
  // +   bugfixed by: Kevin van Zonneveld (http://kevin.vanzonneveld.net)
  // +   bugfixed by: kirilloid
  // *     example 1: utf8_decode('Kevin van Zonneveld');
  // *     returns 1: 'Kevin van Zonneveld'

  var tmp_arr = [],
    i = 0,
    ac = 0,
    c1 = 0,
    c2 = 0,
    c3 = 0,
    c4 = 0;

  str_data += '';

  while (i < str_data.length) {
    c1 = str_data.charCodeAt(i);
    if (c1 <= 191) {
      tmp_arr[ac++] = String.fromCharCode(c1);
      i++;
    } else if (c1 <= 223) {
      c2 = str_data.charCodeAt(i + 1);
      tmp_arr[ac++] = String.fromCharCode(((c1 & 31) << 6) | (c2 & 63));
      i += 2;
    } else if (c1 <= 239) {
      // http://en.wikipedia.org/wiki/UTF-8#Codepage_layout
      c2 = str_data.charCodeAt(i + 1);
      c3 = str_data.charCodeAt(i + 2);
      tmp_arr[ac++] = String.fromCharCode(((c1 & 15) << 12) | ((c2 & 63) << 6) | (c3 & 63));
      i += 3;
    } else {
      c2 = str_data.charCodeAt(i + 1);
      c3 = str_data.charCodeAt(i + 2);
      c4 = str_data.charCodeAt(i + 3);
      c1 = ((c1 & 7) << 18) | ((c2 & 63) << 12) | ((c3 & 63) << 6) | (c4 & 63);
      c1 -= 0x10000;
      tmp_arr[ac++] = String.fromCharCode(0xD800 | ((c1>>10) & 0x3FF));
      tmp_arr[ac++] = String.fromCharCode(0xDC00 | (c1 & 0x3FF));
      i += 4;
    }
  }

  return tmp_arr.join('');
}

    function comment_filter(page){
        var url = 'http://www.tienganh123.com/mod/comment_filter.php';        
        var ft = document.getElementById("cm_filter_list").value;	
        var member = document.getElementById("com_search").value;        
        url=url+"?ft="+ft;
        url=url+"&mem="+member;
        url=url+"&page="+page;
        url=url+"&cid="+Math.random();       
        url=url+"";    
        
        var postCm = $(".lik_count_comment").offset()
            $('html, body').animate({scrollTop:postCm.top},300);   
        
        $.get(url, function(data) {
            data = jQuery.parseJSON(data)            
            $('#show_comment').html(utf8_decode(data.content));        
            
            init_comment();
            
             if(data.content.indexOf('.mp3')>0 || data.content.indexOf('.MP3')>0){
                $('.jquery_jplayer_comment').each(function(i){        
                    addAudioLong(this,i,isIOS);                    
                    });
             }
        });
        
        /*$.ajax({
                    type : "GET",
                    url: url,
                    dataType: 'html',
                    success : function(data){
                        data = jQuery.parseJSON(data)            
            $('#show_comment').html(utf8_decode(data.content));        
            
            init_comment();
            
             if(data.content.indexOf('.mp3')>0 || data.content.indexOf('.MP3')>0){
                $('.jquery_jplayer_comment').each(function(i){        
                    addAudioLong(this,i,isIOS);                    
                    });
             }
                    }
                });*/        
        return false;
    }
    
    function edit_mycomment(page_comment,mem_id)
    {
    	$.post('http://www.tienganh123.com/ajax/comment/edit',{page_comment:page_comment, content:$("#edit_sendcms").val(), score:$("#edit_score").val()}, function(data) {
			var obj = jQuery.parseJSON(data);
			if(obj.status == 'yes')
			{
				$("#edit_form_mycomment_area").hide();
				$("#show_msg_my_comment").css('color','#01DF01');
				$("#show_msg_my_comment").html("Sửa phản hồi thành công.");
				$("#com_"+mem_id+" .vbv2_rsNum").html($("#edit_score").val());
				$("#com_"+mem_id+" .s_content").html($("#edit_sendcms").val());
			}
			else
			{
				$("#show_error_msg").css('color','#FF0000');
				$("#show_error_msg").html(obj.msg);
			}
		});
    }
</script>

		<div class="comment">
		<div class="space10"></div>
		<a
			href="http://www.tienganh123.com/huong-dan/4668-cach-dat-the-vip-tren-tienganh123.html"
			target="_blank"> <img
			src="http://www.tienganh123.com/images/Untitledassss.png"
			alt="Quảng cáo" /> </a>
		<h3 class="font_weight" style="text-align: right; font-size: 11px">Tư
		vấn và đặt mua thẻ qua điện thoại : <strong>0473053868</strong>
		(8h-21h)</h3>

		<div id="form_comment_area">




		<div class="form_send_comment">
		<div class="lik_title_comment">ĐĂNG PHẢN HỒI CỦA BẠN CHO BÀI HỌC NÀY</div>
		<div class="comment_ico_title">
		<div id="emt_icon" class="comment_ico_img"><img
			src="http://www.tienganh123.com/images/comment_smile_ico.png"></div>
		<div class="comment_ico_text">Chèn biểu tượng cảm xúc</div>
		</div>




		<div class="tbao_status_comment textarea_comment"
			style="border: 1px solid #cecece;"><span style='color: red'>Bạn phải
		đăng nhập để sử dụng chức năng này</span></div>




		<span id="show_error_msg"></span></div>
		<div class="form_send_comment_bt"><img
			src="http://www.tienganh123.com/images/bt_comment_invi.png" /></div>

		</div>





		<span id="show_msg_my_comment"
			style="text-align: left; float: left; font-weight: bold;"></span>
		<div class="lik_count_comment">CÁC Ý KIẾN BÌNH LUẬN - PHẢN HỒI VỀ BÀI
		HỌC NÀY</div>


		<form id="form1" name="form1" method="post" action="#">
		<table width="100%" style="clear: both; line-height: 12px">
			<tr>
				<td width="23%">Đăng bởi thành viên</td>
				<td width="26%"><input name="f_s_name" class="f_search_name"
					type="text" id="com_search"></td>
				<td width="11%">Xếp theo</td>
				<td width="22%"><select style="height: 22px;" name="cm_filter_list"
					id="cm_filter_list" class="f_s_select comment_selectop" size="1">
					<option value="new">Bài mới nhất</option>
					<option value="old">Bài cũ nhất</option>

				</select></td>
				<td valign="middle"><input type="image"
					src="http://data.tienganh123.com/images/v2/home/bt_search.jpg"
					style="border: medium none;"
					onClick="return comment_filter('/quang-cao/9770-adlite.html',this);"></td>
			</tr>
		</table>
		</form>

		<div id="show_comment">
		<div class="info_cus_box">

		<div class="lik_box" id="li_comm_3256822">
		<div class="lik_info_box_ct">
		<div class="lik_info_box_top">
		<div class="lik_info_box_img"><a
			href="http://www.tienganh123.com/member/1235849"><img
			src="http://data.tienganh123.com/images/member/cb4.gif" /></a></div>
		<div class="lik_info_r">
		<div class="avt_info_name"><a
			href="http://www.tienganh123.com/member/1235849" class="tk_username">ADRAGON
		</a>
		<div></div>
		</div>
		<div class="lik_info_te blue"><a
			onclick="return hs.htmlExpand(this, { objectType: 'iframe', width: 510, height: 410 } )"
			style="font-weight: 100; color: #0081A1"
			href="http://www.tienganh123.com/pages/modules/basic_english.php?id=822362"
			class=" "> Tiếng Anh cơ bản sơ cấp </a></div>
		<div class="lik_info_te">Ngày tham gia: 10-10-2013</div>
		<div class="lik_info_te">Bài viết: <b>1</b></div>
		</div>
		<div class="lik_info_right">
		<div class="lik_i_list">• Danh hiệu: <span class="orange"><span
			style="color: #960;">Kiến Gỗ</span></span> <a
			title="Danh hiệu là gì?"
			onclick="return hs.htmlExpand(this, { objectType: 'iframe', width: 300, height: 150 } )"
			style="font-weight: 100"
			href="http://www.tienganh123.com/pages/modules/danhhieu.html"
			class=" "> <img src="/images/home/lik_faq.png"> </a></div>
		<div class="lik_i_list ">• Điểm thành tích: 0 <a
			title="Điểm thành tích là gì?"
			onclick="return hs.htmlExpand(this, { objectType: 'iframe', width: 300, height: 250 } )"
			style="font-weight: 100"
			href="http://www.tienganh123.com/pages/modules/diemthanhtich.html"
			class=" "> <img src="/images/home/lik_faq.png"> </a></div>
		<div class="lik_i_list">• Sổ học bạ: <span style="color: #666;">Đang
		cố gắng</span></div>
		<div class="lik_i_list">• Điểm học bạ: 4 <a title="Điểm học bạ là gì?"
			onclick="return hs.htmlExpand(this, { objectType: 'iframe', width: 300, height: 200 } )"
			style="font-weight: 100"
			href="http://www.tienganh123.com/pages/modules/diemhocba.html"> <img
			src="/images/home/lik_faq.png"> </a></div>
		</div>
		</div>
		<div class="lik_ar_d"></div>
		<div class="lik_info_box_bot" id="com_1235849"><span class="s_content">cũng
		hay hay</span></div>
		<div class="lik_date_l"></div>
		<div class="lik_date_r">
		<div class="lik_date_r_f"></div>
		<div class="lik_date_r_l">Gửi lúc: 19:38:26 ngày 08-12-2013</div>
		</div>
		<div class="lik_chuky"></div>


		</div>
		<div class="lik_box_bottom"></div>
		<a title="" target="_blank" href="">
		<div class="lsf_rb "></div>
		</a></div>

		<div class="lik_box" id="li_comm_3249116">
		<div class="lik_info_box_ct">
		<div class="lik_info_box_top">
		<div class="lik_info_box_img"><a
			href="http://www.tienganh123.com/member/909724"><img
			src="http://upload.tienganh123.com/thumbnail/thumb_909724_avatar.jpg" /></a></div>
		<div class="lik_info_r">
		<div class="avt_info_name"><a
			href="http://www.tienganh123.com/member/909724" class="tk_username">sakurata2
		</a>
		<div><a
			href='http://www.tienganh123.com//huong-dan/214-quyen-loi-thanh-vien-vip-cua-tienganh123.html'
			target='_blank'><span><img width="20" height="9"
			src='http://www.tienganh123.com//images/icons/vip.png' /> </span></a></div>
		</div>
		<div class="lik_info_te blue"><a
			onclick="return hs.htmlExpand(this, { objectType: 'iframe', width: 510, height: 410 } )"
			style="font-weight: 100; color: #0081A1"
			href="http://www.tienganh123.com/pages/modules/basic_english.php?id=822362"
			class=" "> Tiếng Anh cơ bản hoàn thành </a></div>
		<div class="lik_info_te">Ngày tham gia: 09-12-2012</div>
		<div class="lik_info_te">Bài viết: <b>304</b></div>
		</div>
		<div class="lik_info_right">
		<div class="lik_i_list">• Danh hiệu: <span class="orange"><span
			style="color: #F00;">Kiến Kim Cương</span></span> <a
			title="Danh hiệu là gì?"
			onclick="return hs.htmlExpand(this, { objectType: 'iframe', width: 300, height: 150 } )"
			style="font-weight: 100"
			href="http://www.tienganh123.com/pages/modules/danhhieu.html"
			class=" "> <img src="/images/home/lik_faq.png"> </a></div>
		<div class="lik_i_list ">• Điểm thành tích: 28 <a
			title="Điểm thành tích là gì?"
			onclick="return hs.htmlExpand(this, { objectType: 'iframe', width: 300, height: 250 } )"
			style="font-weight: 100"
			href="http://www.tienganh123.com/pages/modules/diemthanhtich.html"
			class=" "> <img src="/images/home/lik_faq.png"> </a></div>
		<div class="lik_i_list">• Sổ học bạ: <span style="color: #F00;">Học
		sinh ưu tú</span></div>
		<div class="lik_i_list">• Điểm học bạ: 347 <a
			title="Điểm học bạ là gì?"
			onclick="return hs.htmlExpand(this, { objectType: 'iframe', width: 300, height: 200 } )"
			style="font-weight: 100"
			href="http://www.tienganh123.com/pages/modules/diemhocba.html"> <img
			src="/images/home/lik_faq.png"> </a></div>
		</div>
		</div>
		<div class="lik_ar_d"></div>
		<div class="lik_info_box_bot" id="com_909724"><span class="s_content">thích
		quá đi thôi!<img class="symbol_comment"
			src="http://data.tienganh123.com/icon/smh_10.gif" /><img
			class="symbol_comment"
			src="http://data.tienganh123.com/icon/smh_43.gif" /></span></div>
		<div class="lik_date_l"></div>
		<div class="lik_date_r">
		<div class="lik_date_r_f"></div>
		<div class="lik_date_r_l">Gửi lúc: 13:52:59 ngày 06-12-2013</div>
		</div>
		<div class="lik_chuky"></div>


		</div>
		<div class="lik_box_bottom"></div>
		<a title="Xem quyền lợi của thành viên Vip" target="_blank"
			href="http://www.tienganh123.com//huong-dan/214-quyen-loi-thanh-vien-vip-cua-tienganh123.html">
		<div class="lsf_rb avt_rb_v"></div>
		</a></div>

		<div class="lik_box" id="li_comm_3247619">
		<div class="lik_info_box_ct">
		<div class="lik_info_box_top">
		<div class="lik_info_box_img"><a
			href="http://www.tienganh123.com/member/942548"><img
			src="http://upload.tienganh123.com/thumbnail/thumb_942548_avatar.jpg" /></a></div>
		<div class="lik_info_r">
		<div class="avt_info_name"><a
			href="http://www.tienganh123.com/member/942548" class="tk_username">longaibikchimheo
		</a>
		<div><a
			href='http://www.tienganh123.com//huong-dan/214-quyen-loi-thanh-vien-vip-cua-tienganh123.html'
			target='_blank'><span><img width="20" height="9"
			src='http://www.tienganh123.com//images/icons/vip.png' /> </span></a></div>
		</div>
		<div class="lik_info_te blue"><a
			onclick="return hs.htmlExpand(this, { objectType: 'iframe', width: 510, height: 410 } )"
			style="font-weight: 100; color: #0081A1"
			href="http://www.tienganh123.com/pages/modules/basic_english.php?id=822362"
			class=" "> Tiếng Anh cơ bản hoàn thành </a></div>
		<div class="lik_info_te">Ngày tham gia: 12-01-2013</div>
		<div class="lik_info_te">Bài viết: <b>70</b></div>
		</div>
		<div class="lik_info_right">
		<div class="lik_i_list">• Danh hiệu: <span class="orange"><span
			style="color: #F60;">Kiến Thép</span></span> <a
			title="Danh hiệu là gì?"
			onclick="return hs.htmlExpand(this, { objectType: 'iframe', width: 300, height: 150 } )"
			style="font-weight: 100"
			href="http://www.tienganh123.com/pages/modules/danhhieu.html"
			class=" "> <img src="/images/home/lik_faq.png"> </a></div>
		<div class="lik_i_list ">• Điểm thành tích: 29 <a
			title="Điểm thành tích là gì?"
			onclick="return hs.htmlExpand(this, { objectType: 'iframe', width: 300, height: 250 } )"
			style="font-weight: 100"
			href="http://www.tienganh123.com/pages/modules/diemthanhtich.html"
			class=" "> <img src="/images/home/lik_faq.png"> </a></div>
		<div class="lik_i_list">• Sổ học bạ: <span style="color: #069;">Hăng
		say phát biểu</span></div>
		<div class="lik_i_list">• Điểm học bạ: 131 <a
			title="Điểm học bạ là gì?"
			onclick="return hs.htmlExpand(this, { objectType: 'iframe', width: 300, height: 200 } )"
			style="font-weight: 100"
			href="http://www.tienganh123.com/pages/modules/diemhocba.html"> <img
			src="/images/home/lik_faq.png"> </a></div>
		</div>
		</div>
		<div class="lik_ar_d"></div>
		<div class="lik_info_box_bot" id="com_942548"><span class="s_content">hay
		ưaaaaaaaa</span></div>
		<div class="lik_date_l"></div>
		<div class="lik_date_r">
		<div class="lik_date_r_f"></div>
		<div class="lik_date_r_l">Gửi lúc: 21:18:17 ngày 05-12-2013</div>
		</div>
		<div class="lik_chuky"></div>


		</div>
		<div class="lik_box_bottom"></div>
		<a title="Xem quyền lợi của thành viên Vip" target="_blank"
			href="http://www.tienganh123.com//huong-dan/214-quyen-loi-thanh-vien-vip-cua-tienganh123.html">
		<div class="lsf_rb avt_rb_v"></div>
		</a></div>

		<div class="lik_box" id="li_comm_3241196">
		<div class="lik_info_box_ct">
		<div class="lik_info_box_top">
		<div class="lik_info_box_img"><a
			href="http://www.tienganh123.com/member/1070849"><img
			src="http://upload.tienganh123.com/thumbnail/thumb_1070849_avatar.jpg" /></a></div>
		<div class="lik_info_r">
		<div class="avt_info_name"><a
			href="http://www.tienganh123.com/member/1070849" class="tk_username">yenlypupu
		</a>
		<div><a
			href='http://www.tienganh123.com//huong-dan/214-quyen-loi-thanh-vien-vip-cua-tienganh123.html'
			target='_blank'><span><img width="20" height="9"
			src='http://www.tienganh123.com//images/icons/vip.png' /> </span></a></div>
		</div>
		<div class="lik_info_te blue"><a
			onclick="return hs.htmlExpand(this, { objectType: 'iframe', width: 510, height: 410 } )"
			style="font-weight: 100; color: #0081A1"
			href="http://www.tienganh123.com/pages/modules/basic_english.php?id=822362"
			class=" "> Tiếng Anh cơ bản hoàn thành </a></div>
		<div class="lik_info_te">Ngày tham gia: 28-05-2013</div>
		<div class="lik_info_te">Bài viết: <b>78</b></div>
		</div>
		<div class="lik_info_right">
		<div class="lik_i_list">• Danh hiệu: <span class="orange"><span
			style="color: #F96;">Kiến Đồng</span></span> <a
			title="Danh hiệu là gì?"
			onclick="return hs.htmlExpand(this, { objectType: 'iframe', width: 300, height: 150 } )"
			style="font-weight: 100"
			href="http://www.tienganh123.com/pages/modules/danhhieu.html"
			class=" "> <img src="/images/home/lik_faq.png"> </a></div>
		<div class="lik_i_list ">• Điểm thành tích: 27 <a
			title="Điểm thành tích là gì?"
			onclick="return hs.htmlExpand(this, { objectType: 'iframe', width: 300, height: 250 } )"
			style="font-weight: 100"
			href="http://www.tienganh123.com/pages/modules/diemthanhtich.html"
			class=" "> <img src="/images/home/lik_faq.png"> </a></div>
		<div class="lik_i_list">• Sổ học bạ: <span style="color: #09F;">Chăm
		học</span></div>
		<div class="lik_i_list">• Điểm học bạ: 81 <a
			title="Điểm học bạ là gì?"
			onclick="return hs.htmlExpand(this, { objectType: 'iframe', width: 300, height: 200 } )"
			style="font-weight: 100"
			href="http://www.tienganh123.com/pages/modules/diemhocba.html"> <img
			src="/images/home/lik_faq.png"> </a></div>
		</div>
		</div>
		<div class="lik_ar_d"></div>
		<div class="lik_info_box_bot" id="com_1070849"><span class="s_content">yeah,
		wonderful!!!<img class="symbol_comment"
			src="http://data.tienganh123.com/icon/smh_39.gif" />:b3</span></div>
		<div class="lik_date_l"></div>
		<div class="lik_date_r">
		<div class="lik_date_r_f"></div>
		<div class="lik_date_r_l">Gửi lúc: 20:17:48 ngày 03-12-2013</div>
		</div>
		<div class="lik_chuky">
		<div class="mem_sign">I am dark.</div>
		</div>


		</div>
		<div class="lik_box_bottom"></div>
		<a title="Xem quyền lợi của thành viên Vip" target="_blank"
			href="http://www.tienganh123.com//huong-dan/214-quyen-loi-thanh-vien-vip-cua-tienganh123.html">
		<div class="lsf_rb avt_rb_v"></div>
		</a></div>

		<div class="lik_box" id="li_comm_3238187">
		<div class="lik_info_box_ct">
		<div class="lik_info_box_top">
		<div class="lik_info_box_img"><a
			href="http://www.tienganh123.com/member/1050287"><img
			src="http://data.tienganh123.com/images/member/doll4.gif" /></a></div>
		<div class="lik_info_r">
		<div class="avt_info_name"><a
			href="http://www.tienganh123.com/member/1050287" class="tk_username">nymph_1999
		</a>
		<div><a
			href='http://www.tienganh123.com//huong-dan/214-quyen-loi-thanh-vien-vip-cua-tienganh123.html'
			target='_blank'><span><img width="20" height="9"
			src='http://www.tienganh123.com//images/icons/vip.png' /> </span></a></div>
		</div>
		<div class="lik_info_te blue"><a
			onclick="return hs.htmlExpand(this, { objectType: 'iframe', width: 510, height: 410 } )"
			style="font-weight: 100; color: #0081A1"
			href="http://www.tienganh123.com/pages/modules/basic_english.php?id=822362"
			class=" "> Tiếng Anh cơ bản cấp độ 5 </a></div>
		<div class="lik_info_te">Ngày tham gia: 08-05-2013</div>
		<div class="lik_info_te">Bài viết: <b>160</b></div>
		</div>
		<div class="lik_info_right">
		<div class="lik_i_list">• Danh hiệu: <span class="orange"><span
			style="color: #F0F;">Kiến Bạc</span></span> <a
			title="Danh hiệu là gì?"
			onclick="return hs.htmlExpand(this, { objectType: 'iframe', width: 300, height: 150 } )"
			style="font-weight: 100"
			href="http://www.tienganh123.com/pages/modules/danhhieu.html"
			class=" "> <img src="/images/home/lik_faq.png"> </a></div>
		<div class="lik_i_list ">• Điểm thành tích: 5 <a
			title="Điểm thành tích là gì?"
			onclick="return hs.htmlExpand(this, { objectType: 'iframe', width: 300, height: 250 } )"
			style="font-weight: 100"
			href="http://www.tienganh123.com/pages/modules/diemthanhtich.html"
			class=" "> <img src="/images/home/lik_faq.png"> </a></div>
		<div class="lik_i_list">• Sổ học bạ: <span style="color: #069;">Hăng
		say phát biểu</span></div>
		<div class="lik_i_list">• Điểm học bạ: 117 <a
			title="Điểm học bạ là gì?"
			onclick="return hs.htmlExpand(this, { objectType: 'iframe', width: 300, height: 200 } )"
			style="font-weight: 100"
			href="http://www.tienganh123.com/pages/modules/diemhocba.html"> <img
			src="/images/home/lik_faq.png"> </a></div>
		</div>
		</div>
		<div class="lik_ar_d"></div>
		<div class="lik_info_box_bot" id="com_1050287"><span class="s_content">wa
		tuyet va rat bo ich<br />
		</span></div>
		<div class="lik_date_l"></div>
		<div class="lik_date_r">
		<div class="lik_date_r_f"></div>
		<div class="lik_date_r_l">Gửi lúc: 15:54:00 ngày 02-12-2013</div>
		</div>
		<div class="lik_chuky">
		<div class="mem_sign">hay tron cach song het mk de ko hoai phi mot
		ngay</div>
		</div>


		</div>
		<div class="lik_box_bottom"></div>
		<a title="Xem quyền lợi của thành viên Vip" target="_blank"
			href="http://www.tienganh123.com//huong-dan/214-quyen-loi-thanh-vien-vip-cua-tienganh123.html">
		<div class="lsf_rb avt_rb_v"></div>
		</a></div>

		</div>

		<div class="vb_cm_line"><a href="javascript:;"
			onclick="load_comment_pages_news('/quang-cao/9770-adlite.html',this,'','');"
			id="0" class="5">Hiển thị thêm</a></div>

		</div>
		</div>


		</div>
		<div class="baihoc">

		<div class="space10"></div>
		<div class="lik_baihoc_new">
		<div class="lik_baihoc_title">Cùng thể loại</div>
		<ul class="lik_list_other">

			<li class="lik_short"><a
				href="http://www.tienganh123.com/tin-tuc-tienganh123"
				title="Tin tức từ TiếngAnh123">Tin tức từ TiếngAnh123</a></li>

			<li class="lik_short"><a
				href="http://www.tienganh123.com/kinh-nghiem-hoc-tap"
				title="Kinh nghiệm học tập">Kinh nghiệm học tập</a></li>

			<li class="lik_short"><a href="http://www.tienganh123.com/huong-dan"
				title="Hướng dẫn">Hướng dẫn</a></li>

			<li class="lik_short"><a href="http://www.tienganh123.com/bai-viet"
				title="Bài viết">Bài viết</a></li>

			<li class="lik_short"><a
				href="http://www.tienganh123.com/giao-luu-truc-tuyen"
				title="Giao lưu trực tuyến">Giao lưu trực tuyến</a></li>

			<li class="lik_short"><a href="http://www.tienganh123.com/nhanvat"
				title="Nhân vật">Nhân vật</a></li>

		</ul>
		</div>


		</div>
		</div>
		</td>
		<td valign="top" class="containt_center_cen_right">
		<div class="search clear">
		<form action="http://www.tienganh123.com/search.html"><input
			type="hidden" name="cx" value="018190178346521003272:szsvnrednru" />
		<input type="hidden" name="cof" value="FORID:10" /> <input
			type="hidden" name="ie" value="UTF-8" /> <input type="text" name="q"
			class="input_search" value="Tìm kiếm bài học" /> <input class="btnsm"
			name="sa" style="width: 37px; height: 38px;" type="image"
			src="http://data.tienganh123.com/images/v2/home/bg_search_right.jpg">
		</form>
		<script type="text/javascript" src="/static/js/brand.js"></script></div>
		<a
			href="http://www.tienganh123.com/dictionary/tra-cuu-tu-dien-online.html"
			title="Tra từ điển"><img
			src="http://data.tienganh123.com/images/tudien_small.jpg" width="225"
			height="41" border="0"></a>
		<div class="dic font_weight">Để tra nghĩa một từ, bạn hãy click chuột
		hai lần vào từ đó.</div>
		<div class="tongdai font_weight">Tổng đài hỗ trợ trực tuyến <br>
		<span class="size_lon"> 047.305.3868</span> (8h-21h)</div>
		<a title="Đăng ký mua thẻ VIP - GOLDENKIDS trên TiếngAnh123.com"
			href="/huong-dan/4668-cach-dat-the-vip-tren-tienganh123.html"><img
			width="225" height="127"
			src="http://data.tienganh123.com/images/v2/home/button_dk.jpg" /></a>



		<script>
function hoidap_top()
{
	toPos(".hoidapnhanh");
}
</script>

		<div class="hoidapnhanh"></div>

		<div class="content_hoidapnhanh"><span class="font_weight red">Bạn
		phải đăng nhập mới được đặt câu hỏi hoặc trả lời.</span>




		<div class="RsCus">
		<ul id="rsHoiDapNhanh">
			<li class="ques" id="ch150183"><a class="tk_username"
				href="/member/1350747" class="">coganglen_nhe</a> <a
				href='http://www.tienganh123.com/huong-dan/214-quyen-loi-thanh-vien-vip-cua-tienganh123.html'
				target='_blank'><span class='spanVipKid'><img width="20" height="9"
				src='http://www.tienganh123.com/images/icons/vip.png' /></span> </a><a
				href='http://www.tienganh123.com/huong-dan/2138-chuong-trinh-hoc-tieng-anh-tre-em-online-goldenkids.html'
				target='_blank'><span class='spanVipKid'><img width="9" height="10"
				class='kidwithvip'
				src='http://www.tienganh123.com/images/icons/kids.png' /></span> </a>
			: <span class="font_weight">F.A là viết tắt của Forever Alone à mấy
			pan</span>
			<div class="action_hoidapnhanh"><a href="javascript:;" id="id_150183"
				class="font_weight replay"><span class="blue1">Trả lời : </span><b>1</b></a>

			</div>
			<div class="info_replay" id="show_id_150183">
			<div class="info_top"></div>
			<div class="info_cen">
			<div class="nano">
			<div class="content"><span class="error150183"></span>
			<ul>
				<li id="258748"><a class="tk_username" href="/member/1348570">luongsonvuee26</a>
				<a
					href='http://www.tienganh123.com/huong-dan/214-quyen-loi-thanh-vien-vip-cua-tienganh123.html'
					target='_blank'><span class='spanVipKid'><img width="20" height="9"
					src='http://www.tienganh123.com/images/icons/vip.png' /></span> </a>
				: <span class="font_weight">Chuẩn rồi bạn, còn có người định nghĩa
				nó là forbidden angels nữa :))</span>
				<h4><a class="voteup" id="258748" up="258748" rel="150183"
					href="javascript:;" title="Vote Up">0</a>&nbsp; <a class="votedown"
					id="258748" down="258748" rel="150183" href="javascript:;"
					title="Vote Down">0</a></h4>

				</li>

			</ul>
			</div>
			</div>

			</div>
			<div class="info_bot"></div>
			</div>
			</li>


			<li class="ques" id="ch150182"><a class="tk_username"
				href="/member/269888" class="">blackorwhite_0507</a> <a
				href='http://www.tienganh123.com/huong-dan/214-quyen-loi-thanh-vien-vip-cua-tienganh123.html'
				target='_blank'><span class='spanVipKid'><img width="20" height="9"
				src='http://www.tienganh123.com/images/icons/vip.png' /></span> </a>
			: <span class="font_weight">thưa cô,từ "cat" đọc gần gần giống như
			"ke t" hay đọc giống như "két t" ạ,mong cô giải đáp giùm em.</span>
			<div class="action_hoidapnhanh"><a href="javascript:;" id="id_150182"
				class="font_weight replay"><span class="blue1">Trả lời : </span><b>0</b></a>

			</div>
			<div class="info_replay" id="show_id_150182">
			<div class="info_top"></div>
			<div class="info_cen">
			<div class="nano">
			<div class="content"><span class="error150182"></span>
			<ul>

			</ul>
			</div>
			</div>

			</div>
			<div class="info_bot"></div>
			</div>
			</li>


			<li class="ques" id="ch150181"><a class="tk_username"
				href="/member/796950" class="">minhdathp94</a> <a
				href='http://www.tienganh123.com/huong-dan/214-quyen-loi-thanh-vien-vip-cua-tienganh123.html'
				target='_blank'><span class='spanVipKid'><img width="20" height="9"
				src='http://www.tienganh123.com/images/icons/vip.png' /></span> </a>
			: <span class="font_weight">symbol và simple phát âm có gì khac
			nhau???</span>
			<div class="action_hoidapnhanh"><a href="javascript:;" id="id_150181"
				class="font_weight replay"><span class="blue1">Trả lời : </span><b>0</b></a>

			</div>
			<div class="info_replay" id="show_id_150181">
			<div class="info_top"></div>
			<div class="info_cen">
			<div class="nano">
			<div class="content"><span class="error150181"></span>
			<ul>

			</ul>
			</div>
			</div>

			</div>
			<div class="info_bot"></div>
			</div>
			</li>


			<li class="ques" id="ch150180"><a class="tk_username"
				href="/member/981590" class="">vingocdiep</a> <a
				href='http://www.tienganh123.com/huong-dan/214-quyen-loi-thanh-vien-vip-cua-tienganh123.html'
				target='_blank'><span class='spanVipKid'><img width="20" height="9"
				src='http://www.tienganh123.com/images/icons/vip.png' /></span> </a>
			: <span class="font_weight">cat-alog và govern-mantal nghĩa là gì ạ?</span>
			<div class="action_hoidapnhanh"><a href="javascript:;" id="id_150180"
				class="font_weight replay"><span class="blue1">Trả lời : </span><b>0</b></a>

			</div>
			<div class="info_replay" id="show_id_150180">
			<div class="info_top"></div>
			<div class="info_cen">
			<div class="nano">
			<div class="content"><span class="error150180"></span>
			<ul>

			</ul>
			</div>
			</div>

			</div>
			<div class="info_bot"></div>
			</div>
			</li>


			<li class="ques" id="ch150179"><a class="tk_username"
				href="/member/1333940" class="">huyenphuongtam0249</a> <a
				href='http://www.tienganh123.com/huong-dan/214-quyen-loi-thanh-vien-vip-cua-tienganh123.html'
				target='_blank'><span class='spanVipKid'><img width="20" height="9"
				src='http://www.tienganh123.com/images/icons/vip.png' /></span> </a>
			: <span class="font_weight">bye bye cả nhà nha , mình đi ngủ đây</span>
			<div class="action_hoidapnhanh"><a href="javascript:;" id="id_150179"
				class="font_weight replay"><span class="blue1">Trả lời : </span><b>0</b></a>

			</div>
			<div class="info_replay" id="show_id_150179">
			<div class="info_top"></div>
			<div class="info_cen">
			<div class="nano">
			<div class="content"><span class="error150179"></span>
			<ul>

			</ul>
			</div>
			</div>

			</div>
			<div class="info_bot"></div>
			</div>
			</li>


			<li class="ques" id="ch150177"><a class="tk_username"
				href="/member/1333940" class="">huyenphuongtam0249</a> <a
				href='http://www.tienganh123.com/huong-dan/214-quyen-loi-thanh-vien-vip-cua-tienganh123.html'
				target='_blank'><span class='spanVipKid'><img width="20" height="9"
				src='http://www.tienganh123.com/images/icons/vip.png' /></span> </a>
			: <span class="font_weight">http://www.tienganh123.com/hat-tieng-anh/10847/1333940
			ủng hộ nha</span>
			<div class="action_hoidapnhanh"><a href="javascript:;" id="id_150177"
				class="font_weight replay"><span class="blue1">Trả lời : </span><b>0</b></a>

			</div>
			<div class="info_replay" id="show_id_150177">
			<div class="info_top"></div>
			<div class="info_cen">
			<div class="nano">
			<div class="content"><span class="error150177"></span>
			<ul>

			</ul>
			</div>
			</div>

			</div>
			<div class="info_bot"></div>
			</div>
			</li>


			<li class="ques" id="ch150176"><a class="tk_username"
				href="/member/1190568" class="">hientai</a> <a
				href='http://www.tienganh123.com/huong-dan/214-quyen-loi-thanh-vien-vip-cua-tienganh123.html'
				target='_blank'><span class='spanVipKid'><img width="20" height="9"
				src='http://www.tienganh123.com/images/icons/vip.png' /></span> </a>
			: <span class="font_weight">valentine của mình năm nay là 1 valentine
			vừa chia tay với người yêu, camư giác có bùn, nhớ nên chả zui gì cả,
			chỉ đau lòng thôi à</span>
			<div class="action_hoidapnhanh"><a href="javascript:;" id="id_150176"
				class="font_weight replay"><span class="blue1">Trả lời : </span><b>5</b></a>

			</div>
			<div class="info_replay" id="show_id_150176">
			<div class="info_top"></div>
			<div class="info_cen">
			<div class="nano">
			<div class="content"><span class="error150176"></span>
			<ul>
				<li id="258747"><a class="tk_username" href="/member/796950">minhdathp94</a>
				<a
					href='http://www.tienganh123.com/huong-dan/214-quyen-loi-thanh-vien-vip-cua-tienganh123.html'
					target='_blank'><span class='spanVipKid'><img width="20" height="9"
					src='http://www.tienganh123.com/images/icons/vip.png' /></span> </a>
				: <span class="font_weight">my valentine is just break up with
				beautiful girl friend. I feel very sad not fun,only pain in my
				core...mình dịch đúng chưa? hj</span>
				<h4><a class="voteup" id="258747" up="258747" rel="150176"
					href="javascript:;" title="Vote Up">0</a>&nbsp; <a class="votedown"
					id="258747" down="258747" rel="150176" href="javascript:;"
					title="Vote Down">0</a></h4>

				</li>

				<li id="258746"><a class="tk_username" href="/member/1073035">dodangthuyduong</a>
				<a
					href='http://www.tienganh123.com/huong-dan/2138-chuong-trinh-hoc-tieng-anh-tre-em-online-goldenkids.html'
					target='_blank'><span class='spanVipKid'><img width="9" height="10"
					src='http://www.tienganh123.com/images/icons/kids.png' /></span> </a>
				: <span class="font_weight">uk,fa</span>
				<h4><a class="voteup" id="258746" up="258746" rel="150176"
					href="javascript:;" title="Vote Up">1</a>&nbsp; <a class="votedown"
					id="258746" down="258746" rel="150176" href="javascript:;"
					title="Vote Down">0</a></h4>

				</li>

				<li id="258745"><a class="tk_username" href="/member/1333940">huyenphuongtam0249</a>
				<a
					href='http://www.tienganh123.com/huong-dan/214-quyen-loi-thanh-vien-vip-cua-tienganh123.html'
					target='_blank'><span class='spanVipKid'><img width="20" height="9"
					src='http://www.tienganh123.com/images/icons/vip.png' /></span> </a>
				: <span class="font_weight">mình buồn kinh khủng luôn</span>
				<h4><a class="voteup" id="258745" up="258745" rel="150176"
					href="javascript:;" title="Vote Up">0</a>&nbsp; <a class="votedown"
					id="258745" down="258745" rel="150176" href="javascript:;"
					title="Vote Down">0</a></h4>

				</li>

				<li id="258742"><a class="tk_username" href="/member/978951">chemgio_2001123</a>
				<a
					href='http://www.tienganh123.com/huong-dan/214-quyen-loi-thanh-vien-vip-cua-tienganh123.html'
					target='_blank'><span class='spanVipKid'><img width="20" height="9"
					src='http://www.tienganh123.com/images/icons/vip.png' /></span> </a>
				: <span class="font_weight">Thế là anh em ta lại về cùng 1 đội (đội
				FA)</span>
				<h4><a class="voteup" id="258742" up="258742" rel="150176"
					href="javascript:;" title="Vote Up">0</a>&nbsp; <a class="votedown"
					id="258742" down="258742" rel="150176" href="javascript:;"
					title="Vote Down">0</a></h4>

				</li>

				<li id="258739"><a class="tk_username" href="/member/231359">thám tử
				Conan tài ba</a> <a
					href='http://www.tienganh123.com/huong-dan/214-quyen-loi-thanh-vien-vip-cua-tienganh123.html'
					target='_blank'><span class='spanVipKid'><img width="20" height="9"
					src='http://www.tienganh123.com/images/icons/vip.png' /></span> </a>
				: <span class="font_weight">tội bạn :'( mình hiểu mà</span>
				<h4><a class="voteup" id="258739" up="258739" rel="150176"
					href="javascript:;" title="Vote Up">1</a>&nbsp; <a class="votedown"
					id="258739" down="258739" rel="150176" href="javascript:;"
					title="Vote Down">0</a></h4>

				</li>

			</ul>
			</div>
			</div>

			</div>
			<div class="info_bot"></div>
			</div>
			</li>


			<li class="ques" id="ch150175"><a class="tk_username"
				href="/member/1176441" class="">nguyenhalinh1999</a> <a
				href='http://www.tienganh123.com/huong-dan/214-quyen-loi-thanh-vien-vip-cua-tienganh123.html'
				target='_blank'><span class='spanVipKid'><img width="20" height="9"
				src='http://www.tienganh123.com/images/icons/vip.png' /></span> </a>
			: <span class="font_weight">cô ơi cho em hỏi câu này:"Everyone knows
			that he has been in a serious car accident." chuyển sang bị động thì
			em nghĩ là:" He has been known to be in a serious car accident." ạ.
			Nhưng đáp án lại là:" He is known to have been in a serious car
			accident." Vì sao lại thế ạ???</span>
			<div class="action_hoidapnhanh"><a href="javascript:;" id="id_150175"
				class="font_weight replay"><span class="blue1">Trả lời : </span><b>1</b></a>

			</div>
			<div class="info_replay" id="show_id_150175">
			<div class="info_top"></div>
			<div class="info_cen">
			<div class="nano">
			<div class="content"><span class="error150175"></span>
			<ul>
				<li id="258737"><a class="tk_username" href="/member/795219">HOANGNGAN99</a>
				<a
					href='http://www.tienganh123.com/huong-dan/214-quyen-loi-thanh-vien-vip-cua-tienganh123.html'
					target='_blank'><span class='spanVipKid'><img width="20" height="9"
					src='http://www.tienganh123.com/images/icons/vip.png' /></span> </a>
				: <span class="font_weight">cau chu dong dong tu chinh o thoi hien
				tai don ma.</span>
				<h4><a class="voteup" id="258737" up="258737" rel="150175"
					href="javascript:;" title="Vote Up">1</a>&nbsp; <a class="votedown"
					id="258737" down="258737" rel="150175" href="javascript:;"
					title="Vote Down">1</a></h4>

				</li>

			</ul>
			</div>
			</div>

			</div>
			<div class="info_bot"></div>
			</div>
			</li>


		</ul>
		<div class="pagging"><a href="javascript:;" onclick="hoidap_top()"
			class="vbv2_back">&nbsp;</a> <span class="vbv2_current" limit="8">8</span>
		<a href="javascript:;" onclick="hoidap_top()" class="vbv2_next">&nbsp;</a>


		</div>
		</div>
		<div class="fanpage"><a target="_blank"
			href="http://www.facebook.com/pages/Tieng-Anh-123/174446175978225?sk=likes"><img
			width="220" height="121"
			src="http://data.tienganh123.com/images/v2/home/Untitleds.png"
			title="Cộng đồng TiếngAnh123 trên Facebook"></a></div>
		<div style="text-align: center; width: 231px; margin-left: -11px;">
		<div class="nhanbaihoc"></div>
		<div class="font_weight nhandiachiemail">Nhập địa chỉ Email của bạn :</div>

		<form action="http://feedburner.google.com/fb/a/mailverify"
			method="post" target="popupwindow"
			onSubmit="window.open('http://feedburner.google.com/fb/a/mailverify?uri=tienganh123', 'popupwindow', 'scrollbars=yes,width=230,height=230');return true">
		<input type="text" name="email" class="input_nhanbaihoc"> <input
			type="hidden" value="tienganh123" name="uri" /> <input type="hidden"
			name="loc" value="en_US" /> <input type="submit" class="btnsm1"
			value="Đăng ký"></form>

		<a href="http://feeds.feedburner.com/tienganh123" target="_blank"> <img
			src="http://feeds.feedburner.com/~fc/tienganh123?bg=FF9900&amp;fg=444444&amp;anim=1&amp;label=listeners"
			height="26" width="88" style="border: 0" alt="" /> </a>

		<div class="font_weight nhandiachiemail">Sau khi đăng ký bạn hãy mở
		email <br>
		để kích hoạt</div>
		</div>
		<div class="thongke"></div>
		<table class="linethongke">
			<tr>
				<td>Tổng số thành viên: 1.354.225</td>
			</tr>
			<tr>
				<td colspan="2">Thành viên mới nhất: <br>
				<a class="blue1" href="http://www.tienganh123.com/member/1355454"
					target="_blank" title="Xem thông tin">BabyGhost999</a></td>
			</tr>
			<tr>
				<td>Đang trực tuyến: 153</td>
			</tr>
		</table>
		<div id="histats_counter"></div>
		<div class="mem_vip_reg">
		<h3>Chúc mừng 5 thành viên</h3>
		<h3>VIP, GoldenKid mới nhất:</h3>
		<ul>
			<li><a class="tk_username" href="/member/1355439">corefiness&nbsp;<a
				href='http://www.tienganh123.com/huong-dan/214-quyen-loi-thanh-vien-vip-cua-tienganh123.html'
				target='_blank'><span class='spanVipKid'><img width="20" height="9"
				src='http://www.tienganh123.com/images/icons/vip.png' /></span> </a></a>
			<div style="clear: both"></div>
			</li>

			<li><a class="tk_username" href="/member/1355427">Tommiu&nbsp;<a
				href='http://www.tienganh123.com/huong-dan/214-quyen-loi-thanh-vien-vip-cua-tienganh123.html'
				target='_blank'><span class='spanVipKid'><img width="20" height="9"
				src='http://www.tienganh123.com/images/icons/vip.png' /></span> </a></a>
			<div style="clear: both"></div>
			</li>

			<li><a class="tk_username" href="/member/1355432">KeHieu&nbsp;<a
				href='http://www.tienganh123.com/huong-dan/214-quyen-loi-thanh-vien-vip-cua-tienganh123.html'
				target='_blank'><span class='spanVipKid'><img width="20" height="9"
				src='http://www.tienganh123.com/images/icons/vip.png' /></span> </a></a>
			<div style="clear: both"></div>
			</li>

			<li><a class="tk_username" href="/member/1355419">sunshinesunshine&nbsp;<a
				href='http://www.tienganh123.com/huong-dan/214-quyen-loi-thanh-vien-vip-cua-tienganh123.html'
				target='_blank'><span class='spanVipKid'><img width="20" height="9"
				src='http://www.tienganh123.com/images/icons/vip.png' /></span> </a></a>
			<div style="clear: both"></div>
			</li>

			<li><a class="tk_username" href="/member/1350195">nguyenvanthuan87&nbsp;<a
				href='http://www.tienganh123.com/huong-dan/214-quyen-loi-thanh-vien-vip-cua-tienganh123.html'
				target='_blank'><span class='spanVipKid'><img width="20" height="9"
				src='http://www.tienganh123.com/images/icons/vip.png' /></span> </a></a>
			<div style="clear: both"></div>
			</li>

		</ul>
		</div>
		</div>
		</td>
	</tr>
</table>
</div>

<div class="containt_center_bot clear"></div>
<div class="info_footer">
<div class="containt_info"><!-- Tin tuc -->
<ul>
	<li class="row"><a href="/menu/tin-tuc"> Tin tức</a></li>
	<li class="font_weight"><a href="/tin-tuc-tienganh123"> Tin tức từ
	TiếngAnh123</a></li>
	<li class="font_weight"><a href="/kinh-nghiem-hoc-tap"> Kinh nghiệm học
	tập</a></li>
	<li class="font_weight"><a href="/huong-dan"> Hướng dẫn sử dụng</a></li>
	<li class="font_weight"><a href="/all_comment"> Nhận xét mới nhất</a></li>
</ul>
<!-- Tieng anh tre em -->
<ul>
	<li class="row"><a href="/menu/tieng-anh-tre-em"> Tiếng Anh trẻ em</a></li>
	<li class="font_weight"><a>Rocket to English </a> <a
		href="/cambridge-young-learners-english">1</a> <a>-</a> <a
		href="/cambridge-young-learners-english-2">2</a> <a>-</a> <a
		href="/cambridge-young-learners-english-3">3</a></li>
	<li class="font_weight"><a>Tiếng Anh lớp </a> <a
		href="/tieng-anh-tre-em-lop-3">3</a> <a>-</a> <a
		href="/tieng-anh-tre-em-lop-4">4</a> <a>-</a> <a
		href="/tieng-anh-tre-em-lop-5">5</a></li>
	<li class="font_weight"><a href="/learn-through-stories"> Tiếng Anh trẻ
	em qua truyện kể</a></li>
	<li class="font_weight"><a href="/tieng-anh-tre-em-qua-bai-hat"> Tiếng
	Anh trẻ em qua bài hát</a></li>
</ul>
<!-- Tieng anh pho thong -->
<ul>
	<li class="row"><a href="/tieng-anh-pho-thong"> Tiếng Anh phổ thông</a></li>
	<li class="font_weight"><a>Tiếng Anh lớp </a> <a
		href="/tieng-anh-pho-thong-lop-6">6</a> <a>-</a> <a
		href="/tieng-anh-pho-thong-lop-7">7</a> <a>-</a> <a
		href="/tieng-anh-pho-thong-lop-8">8</a> <a>-</a> <a
		href="/tieng-anh-pho-thong-lop-9">9</a></li>
	<li class="font_weight"><a>Tiếng Anh lớp </a> <a
		href="/tieng-anh-pho-thong-lop-10">10</a> <a>-</a> <a
		href="/tieng-anh-pho-thong-lop-11">11</a> <a>-</a> <a
		href="/tieng-anh-pho-thong-lop-12">12</a></li>
	<li class="font_weight"><a href="/on-thi-dai-hoc"> Ôn thi đại học</a></li>
</ul>
<!-- Tieng anh nguoi lon -->
<ul>
	<li class="row"><a href="/bai-hoc-moi/tieng-anh-nguoi-lon"> Tiếng Anh
	người lớn</a></li>
	<li class="font_weight"><a href="/luyen-thi-toeic-tienganh123"> Luyện
	thi TOEIC</a></li>
	<li class="font_weight"><a>Học tiếng Anh qua </a> <a
		href="/hoc-tieng-anh-qua-cnn">CNN</a> <a>-</a> <a
		href="/hoc-tieng-anh-qua-bbc">BBC</a></li>
	<li class="font_weight"><a href="/nghe-tieng-anh-theo-chu-de"> Luyện
	nghe video theo chủ đề</a></li>
	<li class="font_weight"><a href="/hoc-qua-dich"> Học qua dịch</a></li>
</ul>
<!-- Cham diem online -->
<ul>
	<li class="row"><a href="/menu/chamdiem"> Chấm điểm online </a></li>
	<li class="font_weight"><a href="/viet-qua-tranh-de"> Viết qua tranh
	(dễ)</a></li>
	<li class="font_weight"><a href="/viet-essay"> Viết bài luận</a></li>
	<li class="font_weight"><a href="/luyen-doc-doan-van"> Luyện đọc đoạn
	văn</a></li>
	<li class="font_weight"><a href="/listening-and-writing-easy"> Nghe và
	viết lại</a></li>
	<!--
        <li class="row"><a href="/menu/hoc-offline"> Lớp học offline </a></li>
        <li class="font_weight"><a href="/lich-khai-giang"> Lịch khai giảng</a></li>
        <li class="font_weight"><a href="/giao-vien-tienganh123"> Giáo viên TiếngAnh123</a></li>
        -->
</ul>
</div>
</div>
<div class="footer">
<div class="footer_info">
<p><strong>TiếngAnh123.Com - a product of BeOnline Co., Ltd.</strong></p>

<div class="font_weight">Giấy phép ĐKKD số: 0102852740 cấp bởi Sở Kế
hoạch và Đầu tư Hà Nội.<br>
Giấy phép đào tạo tiếng Anh số: 9816/QĐ-SGD&ĐT cấp bởi Sở Giáo dục và
Đào tạo Hà Nội.<br>
Giấy xác nhận cung cấp dịch vụ mạng xã hội học tiếng Anh trực tuyến số:
36/GXN-TTĐT cấp bởi Bộ Thông tin & Truyền thông. <br>
Địa chỉ: <span class="black1"> số nhà 15-23, ngõ 259/9 phố Vọng, Đồng
Tâm, Hai Bà Trưng, Hà Nội.<br />
Tel: 0473053868 - 0436628077.</span> <a
	href="mailto:lophoc@tienganh123.com" class="blue1">Email:
lophoc@tienganh123.com </a><br>
</div>
</div>
<div class="line_doc"></div>
<div class="reg_news">

<div class="ft_partners">Partners:<br />
<a><img
	src="http://data.tienganh123.com/images/v2/home/f_pn_newworktimes.png" /></a>
<a><img
	src="http://data.tienganh123.com/images/v2/home/f_pn_vietnamnews.png" /></a>
<a><img src="http://data.tienganh123.com/images/v2/home/f_pn_voa.png" /></a>
<a><img src="http://data.tienganh123.com/images/v2/home/f_pn_abc.png" /></a>
</div>
<div class="ft_partners">Awards:<br />
<div class="awards_item">
<div class="awards_img"><a
	href="http://www.tienganh123.com/tin-tuc-tienganh123/9218-tienganh123-nhan-danh-hieu-sao-khue-2013.html"><img
	src="http://data.tienganh123.com/images/v2/home/f_aw_saokhue.png" /></a>
</div>
<div class="awards_text"><a
	href="http://www.tienganh123.com/tin-tuc-tienganh123/9218-tienganh123-nhan-danh-hieu-sao-khue-2013.html">Danh
hiệu <br />
Sao Khuê 2013</a></div>
</div>
<div class="awards_item">
<div class="awards_img"><a
	href="http://www.tienganh123.com/tin-tuc-tienganh123/7908-tin%20thang%2010-2012.html"><img
	src="http://data.tienganh123.com/images/v2/home/f_aw_top50.png" /></a>
</div>
<div class="awards_text"><a
	href="http://www.tienganh123.com/tin-tuc-tienganh123/7908-tin%20thang%2010-2012.html">Top
50 sp<br />
năm 2012</a></div>
</div>
<div class="awards_item">
<div class="awards_img"><a
	href="http://www.tienganh123.com/tin-tuc-tienganh123/10433-TiengAnh123-dat-giai-khuyen-khich-nhan-tai-dat-viet-2013.html"><img
	src="http://data.tienganh123.com/images/v2/home/f_aw_ntdv.png" /></a></div>
<div class="awards_text"><a
	href="http://www.tienganh123.com/tin-tuc-tienganh123/10433-TiengAnh123-dat-giai-khuyen-khich-nhan-tai-dat-viet-2013.html">Nhân
tài<br />
Đất Việt 2013</a></div>
</div>
</div>
</div>

</div>
<div class="bootom_footer"></div>
</div>
<div class="bg_bottom"></div>
</div>
<script type="text/javascript">  
            //load Social 
            $(window).load(function () {
                loadSocial();
            });
        </script>

<!-- Google Code for Th&#7867; ti&#7871;p th&#7883; l&#7841;i -->
<script type="text/javascript">
            /* <![CDATA[ */
            var google_conversion_id = 1007657942;
            var google_conversion_label = "E_3PCILMwQQQ1se-4AM";
            var google_custom_params = window.google_tag_params;
            var google_remarketing_only = true;
            /* ]]> */
        </script>
<script type="text/javascript"
	src="//www.googleadservices.com/pagead/conversion.js">
        </script>
<noscript>
<div style="display: inline;"><img height="1" width="1"
	style="border-style: none;" alt=""
	src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/1007657942/?value=0&amp;label=E_3PCILMwQQQ1se-4AM&amp;guid=ON&amp;script=0" />
</div>
</noscript>



<script language="javascript" type="text/javascript"> var f_n_post = document.getElementById('new_post_forum'); var f_n_home = document.getElementById('f_s_home'); if((f_n_post != null) && (f_n_home != null)){ forum_new_post(); }else if(f_n_post != null){ f_n_post.innerHTML = '<div class="content_box">[<a href="javascript:forum_new_post();">Hiển thị</a>]</div>'; } if(typeof hideNonPaidMember == 'function') { hideNonPaidMember(); } if(typeof hide_ads == 'function') { hide_ads(); } </script>
<!-- Google analytics -->
<script type="text/javascript">  var _gaq = _gaq || []; _gaq.push(['_setAccount', 'UA-12122297-2']); _gaq.push(['_trackPageview']); (function() { var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true; ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js'; var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s); })(); </script>
<!-- PopUp -->
<div id="boxes">
<div id="dialogie" class="window">
<div class="popup_box_ie">
<div class="popup_download"><span><a
	href="http://download.cdn.mozilla.net/pub/mozilla.org/firefox/releases/19.0.1/win32/vi/Firefox%20Setup%2019.0.1.exe"
	target="_blank"><img width="86" height="86"
	src="http://www.tienganh123.com/images/icon_ff.jpg" /></a></span> <span><a
	href="http://dl.google.com/chrome/install/1364.97/chrome_installer.exe"
	target="_blank"><img width="86" height="86"
	src="http://www.tienganh123.com/images/icon_ch.jpg" /></a></span> <span><a
	href="http://download.microsoft.com/download/F/8/8/F8871EEC-61E7-4C8C-9A8D-4B61AE5743A6/IE8-WindowsXP-x86-VIT.exe"
	target="_blank"><img width="86" height="86"
	src="http://www.tienganh123.com/images/icon_ie.jpg" /></a></span></div>
<div class="popup_skip"><a href="javascript:;"><img width="77"
	height="21" title="Bỏ qua"
	src="http://www.tienganh123.com/images/bt_skip.png"
	style="margin-top: 0;" class="close" /></a></div>
</div>
</div>
<div id="mask"></div>
</div>

<div id="boxes">
<div id="dialog" class="window"><a
	href="http://www.tienganh123.com/tin-tuc-tienganh123/10872-khuyen-mai-chao-mung-xuan-giap-ngo-2014.html"
	target="_blank"> <img
	src="http://data.tienganh123.com/images/popup/popup_tet2014.jpg"
	height="390" width="580"> </a> <img title="Đóng" width="68" height="25"
	src="http://www.tienganh123.com/images/close_popup.png" align="right"
	class="close" /></div>
<div id="mask"></div>
</div>
<input type="hidden" id="ie_memid" value="">
<input type="hidden" id="is_vipkid" value="">
<input type="hidden" id="pathname" value="/quang-cao/9770-adlite.html">


<!-- Chat 123 -->
<script language="javascript">        
            //Load file
            var urls_load = new Array(                
                "http://www.tienganh123.com/static/js/audio_ddn.js",            
                "http://www.tienganh123.com/static/js/libs_async.js?v=6"            
            );
            loadFile(urls_load,0);
            var url_chat = "http://chat.tienganh123.com/chat/";
            var syn_chat_data = '';
        </script>
<!--<script type="text/javascript" src="http://www.tienganh123.com/static/js/chat_123.js"></script>
        <link rel="stylesheet" type="text/css" href="http://chat.tienganh123.com/assets/css/chat_123.css"/>-->
<!-- Chat 123 -->