
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/public/css/common-style.css"); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/public/css/ta123_style.css"); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/public/css/ta123_style2.css"); ?>
<?php $this->headScript()->appendFile($this->baseUrl('/public/js/jquery.min.js')); ?>
<?php echo $this->render('admin-layout.phtml') ?>
<style>
<!--

-->
td .normal-button{
 width: 80px;
 margin-right: 5px;
}
</style>
<script type="text/javascript">
    $(document).ready(function(){
        $(".btn-delete").click(function(){
            if (confirm("このユーザを削除するのを同意しますか？")) {
                window.top.location = "<?php echo $this->baseUrl()."/admin/user/delete-admin?user_id=".$this->adminInfo[Admin_Model_Admin::$ID]; ?>";
            }
        });
    });
</script>

<div style="width: 1000px; margin: 0px auto;">
    
    <div class="detail_layout">
        <div class="detail_layout_title">
            <div class="detail_title_left title_left_1">I</div>
            <div class="detail_title_center title_center_1">個人情報</div>
            <div class="detail_title_right title_right_1"></div>
        </div>
        <div class="detail_layout_content">
            <?php foreach ($this->messages as $message) { ?>
            <div style="color: green"><?php echo $message; ?></div>
            <?php } ?>
            <?php foreach ($this->errorMessages as $errorMessage) { ?>
            <div style="color: red"><?php echo $errorMessage; ?></div>
            <?php } ?>
            <div style="color: red">
                <?php if (isset($this->errorMessage)) {echo $this->errorMessage;} ?>
            </div>
            <?php if ($this->adminInfo != null) { ?>
            <table>
                <tr>
                    <td><span class="span_text_1" style="width: 100px;">ユーザ名</span></td>
                    <td>: <?php echo $this->adminInfo[Admin_Model_Admin::$USERNAME] ?></td>
                </tr>
                <tr>
                    <td><span class="span_text_1" style="width: 100px;">作成した人</span></td>
                    <td>: <?php echo $this->adminInfo["created"] ?></td>
                </tr>
            </table>
            <button class="normal-button btn-delete">削除</button>
            <a href="<?php echo $this->baseUrl()?>/admin/user/change-admin?user_id=<?php echo $this->adminId?>"><button class="normal-button ">変更</button></a>
            <?php } ?>
        </div>

        <?php if ($this->adminInfo != null) { ?>
        <div class="detail_layout_title">
            <div class="detail_title_left title_left_1">II</div>
            <div class="detail_title_center title_center_1">ログインできるIPリスト</div>
            <div class="detail_title_right title_right_1"></div>
        </div>
        <div class="detail_layout_content">
            <table>
                <?php 
                    if ($this->allowedIp) {
                        foreach ($this->allowedIp as $ip) { 
                ?>
                <tr>
                    <td width="120"><span class="ip"><?php echo $ip['ip'] ?></span></td>
                    <td><button ip_id = "<?php echo $ip["id"] ?>" class = "okChange normal-button" style ="display: none">同意</button><button ip_id = "<?php echo $ip["id"] ?>" class = "changeIp normal-button">変更</button><button class="cancel normal-button" style = "display : none " >キャンセル</button></td>
                	<td><a href="<?php echo $this->baseUrl()."/admin/account/delete-ip?id=".$ip['id']; ?>" style="color: red;" onclick ="return confirm('そのIPアドレスを削除する？')">X</a></td>
                </tr>
                <?php   }
                    } else {
                        ?>
                <tr>
                    <td style="color: red">ログインできるIPがない</td>
                </tr>
                <?php
                    }
                ?>
            </table>
            <a href="<?php echo $this->baseUrl()."/admin/user/add-ip?user_id=".$this->adminInfo[Admin_Model_Admin::$ID]; ?>"><button class="normal-button">IP追加</button></a>
        </div>
        <?php } ?>
    </div>
    
    <?php echo $this->render("right-banner.phtml") ?>
</div>
<script>

   $(".changeIp").click(function(){
		var ipSpan = $(this).parent().parent().find(".ip").get(0);
		var ip = $(ipSpan).text();
		$(ipSpan).replaceWith("<input type = 'text' value='" + ip + "' style = 'width : 120px' ip ='"+ ip+"' >");
		$(this).parent().find(".cancel").show();
		$(this).hide();
		$(this).parent().find(".okChange").show();
	});
   $(".cancel").click(function(){
	   	var input = $(this).parent().parent().find("input").get(0);
		var ip = $(input).attr("ip");
		$(input).replaceWith("<span class='ip' >"+ ip +"</span>");
		$(this).hide();
		$(this).parent().find(".okChange").hide();
		$(this).parent().find(".changeIp").show();
	});
   $(".okChange").click(function(){
	   var $this = $(this);
	   	var input = $(this).parent().parent().find("input").get(0);
		var ip = $.trim($(input).val());
		var oldIp = $(input).attr("ip");
		if(ip ==""){
				alert("IPアドレスを入力してください");
				return false;
		}
		var id = $(this).attr("ip_id");
		$.ajax({
			url:"<?php echo $this->baseUrl() ?>/admin/account/change-ip/id/"+id,
			type : "post",
			data : {'ip' : ip},
			success: function(){
				$(input).replaceWith("<span class='ip' >"+ ip +"</span>");
				$this.parent().find(".cancel").hide();
				$this.hide();
				$this.parent().find(".changeIp").show();
			},
			error: function(){
				alert("エラーがあります");
				$(input).replaceWith("<span class='ip' >"+ oldIp +"</span>");
				$this.parent().find(".cancel").hide();
				$this.hide();
				$this.parent().find(".changeIp").show();
			}
			});
		
		
	});
</script>