
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/public/css/common-style.css"); ?>
<?php echo $this->render('admin-layout.phtml') ?>
<center>
    <form style="width: 700px; margin: 0px auto;" action="" method="post">
        <div class="resg_box">
            <div class="yellow_title_bottom"></div>
            <div class="res_step_title">
                <div class="res_step_t_num res_num1">管理者追加</div>
                <div class="res_step_t_r"></div>
            </div>
            <div class="res_form_row" style="color: red;">
                <?php if (isset($this->errorMessage)) {echo $this->errorMessage;} ?>
            </div>
            <div class="res_form_row">
                <div class="res_f_r_left">
                    <div class="res_f_r_left_up">
                        <b>ユーザ名</b>: <span class="red">*</span>
                    </div>
                    <!--<div class="res_f_r_left_down">xxx.yyy.zzz.ttt</div>-->
                </div>
                <div class="res_f_r_right">
                    <input type="text" name="username"  value="<?php echo $this->admin["username"]?>" class="res_input" maxlength="30">                            
                    <div id="er_username" class="res_f_note"></div>
                </div>
            </div>
            <div class="res_form_row" style="margin-left:250px;">
                <input type="submit" name="submit" id="submit" value="変更"  style="float: left">
                <a href="<?php echo $this->baseUrl()."/admin/user/admin-info?user_id=",$this->admin["id"]; ?>"><input type="button" class="register-cus" value="キャンセル"> </a>
            </div>
        </div>
        <div style="color: red"><?php echo $this->errorMessage; ?></div>
    </form>
    
</center>