
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/public/css/admin-common-style.css"); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/public/css/ta123_style.css"); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/public/css/ta123_style2.css"); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/public/css/common-style.css"); ?>

<?php echo $this->render('admin-layout.phtml') ?>

<div style="width: 1000px; margin: 20px auto">
    <div class="detail_layout">
        <div class="detail_layout_title">
            <div class="detail_title_left title_left_1">I</div>
            <div class="detail_title_center title_center_1">ユーザの個人情報</div>
            <div class="detail_title_right title_right_1"></div>
        </div>
        <div class="detail_layout_content">
            <table>
                <tr>
                    <td width="200">ユーザ名</td>
                    <td><?php echo $this->user[Admin_Model_User::$USERNAME] ?></td>
                    <td></td>
                </tr>
                <tr>
                    <td>名前</td>
                    <td><?php echo $this->user[Admin_Model_User::$NAME] ?></td>
                    <td></td>
                </tr>
                <tr>
                    <td>生年月日</td>
                    <td><?php echo $this->user[Admin_Model_User::$BIRTHDAY] ?></td>
                    <td></td>
                </tr>
                <tr>
                    <td>住所</td>
                    <td><?php echo $this->user[Admin_Model_User::$ADDRESS] ?></td>
                    <td></td>
                </tr>
                <tr>
                    <td>電話番号</td>
                    <td><?php echo $this->user[Admin_Model_User::$PHONE] ?></td>
                    <td></td>
                </tr>
                <tr>
                    <td>クレジットカード情報</td>
                    <td><?php echo $this->user[Admin_Model_User::$BANK_ACCOUNT] ?></td>
                    <td></td>
                </tr>
                <tr>
                    <td>ステータス</td>
                    <td><?php 
                        if ($this->user[Admin_Model_User::$STATUS] == Admin_Model_User::$USER_STATUS_AVAILABLE) {
                            echo "可用";
                        } else {
                            echo "許可を待っている";
                        }
                    ?></td>
                    <?php if ($this->user[Admin_Model_User::$STATUS] == Admin_Model_User::$USER_STATUS_WAITING) { ?>
                    <td><button class="normal-button">許可をする</button></td>
                    <?php } ?>
                </tr>
            </table>
        </div>
        <div class="detail_layout_content">
            <div style="width: 520px; margin: 0px auto">
                <button class="normal-button" style="width: 150px; margin: 0px 10px">パースワードリセット</button>
                <button class="normal-button" style="width: 150px; margin: 0px 10px">「Verifycode」リセット</button>
                <button class="normal-button" style="width: 150px; margin: 0px 10px">ユーザを削除</button>
            </div>
        </div>
    </div>
    <?php echo $this->render("right-banner.phtml") ?>
</div>