<?php
$vars = $this->getVars(); 
$username = $vars['username'];
$birthday = $vars['birthday'];
$createdAdmin = $vars['created_admin'];
$ipList = $vars['ip_list'];
?>


    <div class="detail_layout">
        <div class="detail_layout_title">
            <div class="detail_title_left title_left_1">I</div>
            <div class="detail_title_center title_center_1">個人情報</div>
            <div class="detail_title_right title_right_1"></div>
        </div>
        <div class="detail_layout_content">
            <table>
                <tr>
                    <td><span class="span_text_1" style="width: 100px;">ユーザ名</span></td>
                    <td>: <?php echo $username?></td>
                </tr>
                <tr>
                    <td><span class="span_text_1" style="width: 100px;">作成した日</span></td>
                    <td>: <?php echo $birthday?></td>
                </tr>
                <tr>
                    <td><span class="span_text_1" style="width: 100px;">作成した人</span></td>
                    <td>:<?php echo $createdAdmin?></td>
                </tr>
            </table>
            <button class="normal-button">パースワード更新</button>
            <button class="normal-button">秘密質問更新</button>
        </div>

        <div class="detail_layout_title">
            <div class="detail_title_left title_left_1">II</div>
            <div class="detail_title_center title_center_1">ログインできるIPリスト</div>
            <div class="detail_title_right title_right_1"></div>
        </div>
        <div class="detail_layout_content">
            <table>
                <?php
                foreach ($ipList as $ip) {
                ?>
                    <tr>
                        <td><?php echo $ip?></td>
                        <td style="color: red">X</td>
                    </tr>
                <?php
                }
                ?>
            </table>
            <button class="normal-button">追加</button>
        </div>
    </div>
