<div class="bg_top" style="height: 200px">&nbsp;</div>
<div class="bg_center">
    <div id="contents">
        <div class="top_content clear">
            <div class="logo">
                <a href="<?php echo $this->baseUrl("admin/user") ?>">
                    <img width="600" height="80" src="<?php echo $this->baseUrl("/public/images/T08-banner.png"); ?>" alt="Logo">
                </a>
            </div>
            <div align="right" style="float: right; margin-top: 20px;">
                <a href="<?php echo $this->baseUrl("admin/account/logout") ?>"><button class="register-cus">ログアウト</button>
                </a>
            </div>
        </div>
        <div class="menus clear">
            <ul>
                <li class="home mn"><a href="<?php echo $this->baseUrl("admin/user") ?>"></a>
                </li>
                <li title="" class="mn"><a href="<?php echo $this->baseUrl("admin/user") ?>">ユーザ管理</a>
                </li>
                <li class="mn" title=""><a href="<?php echo $this->baseUrl("admin/lesson") ?>">ファイル</a>
                </li>
                <li title="" class="mn "><a href="<?php echo $this->baseUrl("admin/index/maintain") ?>">保守</a>
                </li>
                <li title="" class="mn "><a href="<?php echo $this->baseUrl("admin/index/payment-info") ?>">支払い情報</a>
                </li>
                <li title="" class="mn "><a href="<?php echo $this->baseUrl("admin/account") ?>">個人情報</a>
                </li>
            </ul>
        </div>
    </div>
</div>