<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

$vars = $this->getVars(); 
$currentPage = $vars['page'];
$totalPage = $vars['total'];
$nextLink = $vars['next'];
$preLink = $vars['pre'];
?>
<div style="width: 100%; padding: 5px;">
    <div style="width: 400px; margin: 0px auto">
        <div style="width: 50px; text-align: center; float: left;"><a href="<?php echo $preLink ?>">Pre</a></div>
        <div style="width: 300px; text-align: center; float: left;"><?php echo "Page ".$currentPage.'/'.$totalPage ?></div>
        <div style="width: 50px; text-align: center; float: left;"><a href="<?php echo $nextLink ?>">Next</a></div>
    </div>
</div>