<?php if ($this->pageCount): ?>
    <?php
    $params = array();
    if (isset($this->tagId)) {
        $params['tagId'] = $this->tagId;
    }
    if (isset($this->lessonId)) {
        $params['lessonId'] = $this->lessonId;
    }
    if (isset($this->searchText)) {
        $params['searchText'] = $this->searchText;
    }
    if (isset($this->copyright)) {
        $params['copyright'] = $this->copyright;
    }
    
    if (isset($this->previous)) {
        ?>
        <div class="paging-item paging-next-prev">
            <a href="<?php 
                $params['page'] = $this->previous;
                echo $this->url( $params ); ?>">前</a> 
        </div>
        <?php
    }
    foreach ($this->pagesInRange as $page) {
        if ($page != $this->current) {
            ?>
            <a href="<?php 
                    $params['page'] = $page;
                    echo $this->url($params);
                ?>">
                <div class="paging-item"><?php echo $page ?></div>
            </a>
            <?php
        } else {
            ?>
            <a href="">
                <div class="paging-item paging-item-curr"><?php echo $page; ?>
                </div>
            </a>
            <?php
        }
    }
    if (isset($this->next)) {
        ?>
        <div class="paging-item paging-next-prev">
            <a href="<?php 
                    $params['page'] = $this->next;
                    echo $this->url($params);
                ?>">次</a>
        </div>     
        <?php
    }
    ?>
<?php endif; ?>