
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/public/css/admin-common-style.css"); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/public/css/ta123_style.css"); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/public/css/ta123_style2.css"); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/public/css/common-style.css"); ?>

<?php echo $this->render('admin-layout.phtml') ?>
<style type="text/css">
    .detail_layout_content td, .detail_layout_content input {
        padding: 5px;
    }
    .detail_layout_content button {
        margin: 10px 0px;
    }
    .backup-file {
        border-top: 1px solid gray;
    }
    .file-name {
        width: 70%;
        padding: 10px;
        float: left;
    }
    .restore-btn {
    }
    .off {
        color: red;
        display: none;
    }
    .on, .off {
        font-weight: bold;
    }
    .on {
        color: blue;
    }
    td {
        vertical-align: top;
    }
    .backup-input input {
        width: 100px; 
    }
</style>
<div style="width: 1000px; margin: 20px auto">
    <div class="detail_layout">
        <div class="detail_layout_title">
            <div class="detail_title_left title_left_1"></div>
            <div class="detail_title_center title_center_1">マスタデータ</div>
            <div class="detail_title_right title_right_1"></div>
        </div>
        <div class="detail_layout_content">
            <?php if ($this->message) { ?>
                <div style="color: blue"><?php echo $this->message; ?></div>
            <?php } ?>
            <?php if ($this->errorMessage) { ?>
                <div style="color: red"><?php echo $this->errorMessage; ?></div>
            <?php } ?>
            <form method="post" action>
                <table width="690">
                    <tr>
                        <td width="80">１回の受講料</td>
                        <td width="120"><input type="text" name="coma_price" value="<?php echo $this->masterData[Admin_Model_Master::$KEY_COMA_PRICE] ?>"/>
                            <b>ドン</b>
                        </td>

                    </tr>
                    <tr>
                        <td width="80">報酬％</td>
                        <td width="120"><input type="text" name="teacher_fee_rate" value="<?php echo $this->masterData[Admin_Model_Master::$KEY_TEACHER_FEE_RATE] ?>" />
                            <b>%</b>
                        </td>
                    </tr>
<!--                    <tr>
                        <td>授業のファイルを格納フォールダ</td>
                        <td width="120"><input type="text" name="file_location" value="<?php echo $this->masterData[Admin_Model_Master::$KEY_FILE_LOCATION] ?>" /></td>
                    </tr>-->
                    <tr>
                        <td>受講可能時間</td>
                        <td width="120">
                            <input type="text" name="lesson_deadline" value="<?php echo $this->masterData[Admin_Model_Master::$KEY_LESSON_DEADLINE] ?>" />
                            <b>日</b>
                        </td>
                    </tr>
                    <tr>
                        <td>ログイン誤り回</td>
                        <td width="120"><input type="text" name="lock_count" value="<?php echo $this->masterData[Admin_Model_Master::$KEY_LOCK_COUNT] ?>" />
                            <b>回</b>
                        </td>
                    </tr>
                    <tr>
                        <td>ロック時間</td>
                        <td width="120"><input type="text" name="login_fail_lock_time" value="<?php echo $this->masterData[Admin_Model_Master::$KEY_LOGIN_FAIL_LOCK_TIME] ?>" />
                            <b>秒</b>
                        </td>
                    </tr>
                    <tr>
                        <td>自動セション終了時間</td>
                        <td width="120"><input type="text" name="session_time" value="<?php echo $this->masterData[Admin_Model_Master::$KEY_SESSION_TIME] ?>" />
                            <b>秒</b>
                        </td>
                    </tr>
                    <tr>
                        <td>違犯できる回数</td>
                        <td width="120"><input type="text" name="violation_time" value="<?php echo $this->masterData[Admin_Model_Master::$KEY_VIOLATION_TIME] ?>" />
                            <b>回</b>
                        </td>
                    </tr>
                    <tr>
                        <td>自動バックアップ時刻</td>
                        <?php
                        $backupTime = $this->masterData[Admin_Model_Master::$KEY_BACKUP_TIME];
                        $backupHour = floor($backupTime / 3600);
                        $backupMinute = floor(($backupTime - $backupHour * 3600) / 60);
                        $backupSecond = $backupTime - $backupHour * 3600 - $backupMinute * 60;
                        ?>
                        <td width="120" class="backup-input">
                            <div>
                                <input type="text" name="backup_time_hour" value="<?php echo $backupHour ?>" />時
                            </div>
                            <div>
                                <input type="text" name="backup_time_minute" value="<?php echo $backupMinute ?>" />分
                            </div>
                        </td>
                    </tr>
                </table>
                <div><input type="submit" class="normal-button" value="更新" /></div>
            </form>
            <div class="res_step_t_r" style="margin-bottom: 20px;width: 685px"></div>
            <div>
                <a href="<?php echo $this->baseUrl() ?>/admin/index/backup">
                    <button class="normal-button" style="width: 200px">システムをバックアップする</button>
                </a>
            </div>
            <!--            <div class="auto-backup">
                            <div class="status">
                                <span>
                                    自動バックアップステータス:
                                </span>
            <?php if ($this->autoBackup) { ?>
                                                                                        <span class="on">
                                                                                            <span>オン</span>
                                                                                            <a href="<?php echo $this->baseUrl() ?>/admin/index/auto-backup?turn=off">
                                                                                                <button class="normal-button">オフにする</button>
                                                                                            </a>
                                                                                        </span>
            <?php } else { ?>
                                                                                        <span class="off">
                                                                                            <span>オフ</span>
                                                                                            <a href="<?php echo $this->baseUrl() ?>/admin/index/auto-backup?turn=on">
                                                                                                <button class="normal-button">オンにする</button>
                                                                                            </a>
                                                                                        </span>
            <?php } ?>
                            </div>
                        </div>-->
            <div>
                <?php foreach ($this->backupList['data'] as $file) { ?>
                    <div class="backup-file">
                        <div class="file-name"><?php echo $file; ?></div>
                        <a href="<?php echo $this->baseUrl() . "/admin/index/restore?file=" . $file; ?>">
                            <button class="normal-button restore-btn">回復する</button>
                        </a>
                    </div>
                <?php } // End foreach backup list  ?>
                <?php
                if ($this->backupList['next']) {
                    $nextLink = $this->baseUrl() . "/admin/index/maintain?page=" . ($this->backupList['currentPage'] + 1);
                } else {
                    $nextLink = "";
                }
                if ($this->backupList['pre']) {
                    $preLink = $this->baseUrl() . "/admin/index/maintain?page=" . ($this->backupList['currentPage'] - 1);
                } else {
                    $preLink = "";
                }
                echo $this->partial("pager.phtml", array('page' => $this->backupList['currentPage'], 'total' => $this->backupList['total'], 'next' => $nextLink, 'pre' => $preLink))
                ?>
            </div>
        </div>
    </div>
    <?php echo $this->render("right-banner.phtml") ?>
</div>