
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/public/css/admin-common-style.css"); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/public/css/ta123_style.css"); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/public/css/ta123_style2.css"); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/public/css/common-style.css"); ?>

<?php echo $this->render('admin-layout.phtml') ?>

<div style="width: 1000px; margin: 20px auto">
    <div class="detail_layout" style="width: 1000px">
        <div class="detail_layout_title" style="width: 1000px">
            <div class="detail_title_left title_left_1">I</div>
            <div class="detail_title_center title_center_1" style="width: 938px">支払い情報</div>
            <div class="detail_title_right title_right_1"></div>
        </div>
        <div class="detail_layout_content" style="width: 954px">
            
            <form action="<?php echo $this->baseUrl()?>/admin/index/month-payment-info" method="get">
                <span><input type="number" style="padding: 5px;" placeholder="年" name= "year"></span>
                <span><input type="number" style="padding: 5px;" placeholder="月" name = "month"></span>
                <span><input type="submit" class="normal-button" value="見る" style="float: none"></span>
            </form>
            <div class="res_step_t_r" style="margin-bottom: 20px;width: 960px"></div>
            <table>
                <tr>
                    <td>システム固有ＩＤ</td>
                    <td>: ELS-UBT-GWK54M78</td>
                </tr>
                <tr>
                    <td>本請求データの時間</td>
                    <td>: <?php echo $this->param["year"];?>年<?php echo $this->param["month"]?>月</td>
                </tr>
                <tr>
                    <td>作成時間</td>
                    <td>: <?php echo date("Y年m月d日H時i分s秒", time())?></td>
                </tr>
                <tr>
                    <td>作成者ID</td>
                    <td>: <?php echo $this->currentUser["username"]?></td>
                </tr>
                <tr>
                    <td>作成者名前</td>
                    <td>: <?php echo $this->currentUser["username"]?></td>
                </tr>
            </table>
            <div class="res_step_t_r" style="margin-bottom: 20px;width: 960px"></div>
            <table width="960" border="1" bordercolor="#d5d5d5" style="border-collapse:collapse" cellpadding="4" cellspacing="4">
                <tr align="left" class="title_table" bordercolor="4f4f4f" style="background-color: rgb(251, 251, 251); background-position: initial initial; background-repeat: initial initial;">
                    <td>登録ＩＤ</td>
                    <td>名前</td>
                    <td>請求金額</td>
                    <td>住所</td>
                    <td>電話番号</td>
                    <td>請求区分</td>
                    <td>クレジットカード番号</td>
                </tr>
                <?php if(!empty($this->paymentInfos) || !empty($this->teacherPaymentInfos)):?>
                <?php foreach ($this->paymentInfos as $info):?>
                <tr align="left">
                    <td class="orange"><?php echo $info["username"]?></td>
                    <td><?php echo $info["name"]?></td>
                    <td><?php echo $info["total"] * $this->price?></td>
                    <td><?php echo $info["address"]?></td>
                    <td><?php echo $info["phone"]?></td>
                    <td>18</td>
                    <td><?php echo $info["bank_account"]?></td>
                </tr>
                <?php endforeach;?>
                <?php foreach ($this->teacherPaymentInfos as $info):?>
                <tr align="left">
                    <td class="orange"><?php echo $info["username"]?></td>
                    <td><?php echo $info["name"]?></td>
                    <td><?php echo $info["total"] * $this->price * 0.6 ?></td>
                    <td><?php echo $info["address"]?></td>
                    <td><?php echo $info["phone"]?></td>
                    <td>54</td>
                    <td><?php echo $info["bank_account"]?></td>
                </tr>
                <?php endforeach;?>
                <?php else : echo "<tr><td colspan ='7'>でーたがありません</td></tr>"?>
                <?php endif;?>
            </table>
            <a href = "<?php echo $this->baseUrl()?>/admin/index/month-payment-info?year=<?php echo $this->param['year']?>&month=<?php echo $this->param['month']?>&download=true"<button class="normal-button" style="margin-top: 10px">TSVファイル作成</button></a>
        </div>
    </div>
</div>