
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/public/css/admin-common-style.css"); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/public/css/ta123_style.css"); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/public/css/ta123_style2.css"); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/public/css/common-style.css"); ?>

<?php echo $this->render('admin-layout.phtml') ?>

<div style="width: 1000px; margin: 20px auto">
    <div class="detail_layout">
        <div class="detail_layout_title">
            <div class="detail_title_left title_left_1">I</div>
            <div class="detail_title_center title_center_1">支払い情報</div>
            <div class="detail_title_right title_right_1"></div>
        </div>
        <div class="detail_layout_content">
            <table width="690" border="1" bordercolor="#d5d5d5" style="border-collapse:collapse" cellpadding="4" cellspacing="4">
                <tr align="left" class="title_table" bordercolor="4f4f4f" style="background-color: rgb(251, 251, 251); background-position: initial initial; background-repeat: initial initial;">
                    <td width="120">年・月</td>
                    <td width="120">収入(VND)</td>
                    <td width="120">利益</td>
                </tr>
                <?php foreach ($this->paymentInfos as $info): ?>
                <tr align="left">
                    <td class="orange"><a href="<?php echo $this->baseUrl()?>/admin/index/month-payment-info?year=<?php echo $info["year"]?>&month=<?php echo $info["month"]?>"><?php echo $info["time"] ?></a></td>
                    <td><a href="#"><?php echo $info["total"]* $this->price; ?></a></td>
                    <td> <?php echo $info["total"]* $this->price * (100-$this->rate)/100; ?></td>
                </tr>
                <?php endforeach; ?>
               
            </table>
            <?php echo $this->partial("pager.phtml", array('page'=>1, 'total'=>10, 'next'=>"#", 'pre'=>"#")) ?>
            <div  style="margin-bottom: 20px; clear: both; height: 15px; border-bottom: 1px solid #ababab;"></div>
            <form action="<?php echo $this->baseUrl()?>/admin/index/month-payment-info" method="get">
                <span><input type="number" style="padding: 5px;" placeholder="年" name ="year" ></span>
                <span><input type="number" style="padding: 5px;" placeholder="月" name = "month" ></span>
                <span><input type="submit" class="normal-button" value="見る" style="float: none"></span>
            </form>
        </div>
    </div>
    <?php echo $this->render("right-banner.phtml") ?>
</div>