
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/public/css/admin-common-style.css"); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/public/css/ta123_style.css"); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/public/css/ta123_style2.css"); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/public/css/common-style.css"); ?>

<?php echo $this->render('admin-layout.phtml') ?>

<div style="width: 1000px; margin: 20px auto">
    <div class="detail_layout">
        <div class="detail_layout_title">
            <div class="detail_title_left title_left_1">I</div>
            <div class="detail_title_center title_center_1">支払い情報</div>
            <div class="detail_title_right title_right_1"></div>
        </div>
        <div class="detail_layout_content">
            <table width="690" border="1" bordercolor="#d5d5d5" style="border-collapse:collapse" cellpadding="4" cellspacing="4">
                <tr align="left" class="title_table" bordercolor="4f4f4f" style="background-color: rgb(251, 251, 251); background-position: initial initial; background-repeat: initial initial;">
                    <td width="120">年・月</td>
                    <td width="120">収入(VND)</td>
                    <td width="120">利益</td>
                </tr>
                <tr align="left">
                    <td class="orange"><a href="#">2013年11月</a></td>
                    <td><a href="#">10.000.000</a></td>
                    <td>4.000.000</td>
                </tr>
               <tr align="left">
                   <td class="orange"><a href="#">2013年10月</a></td>
                    <td>10.000.000</td>
                    <td>4.000.000</td>
                </tr>
                <tr align="left">
                    <td class="orange"><a href="#">2013年9月</a></td>
                    <td>10.000.000</td>
                    <td>4.000.000</td>
                </tr>
                <tr align="left">
                    <td class="orange"><a href="#">2013年8月</a></td>
                    <td>10.000.000</td>
                    <td>4.000.000</td>
                </tr>
                <tr align="left">
                    <td class="orange"><a href="#">2013年7月</a></td>
                    <td>10.000.000</td>
                    <td>4.000.000</td>
                </tr>
            </table>
            <?php echo $this->partial("pager.phtml", array('page'=>1, 'total'=>10, 'next'=>"#", 'pre'=>"#")) ?>
            <div class="res_step_t_r" style="margin-bottom: 20px"></div>
            <form>
                <span><input type="text" style="padding: 5px;" placeholder="年"></span>
                <span><input type="text" style="padding: 5px;" placeholder="月"></span>
                <span><input type="submit" class="normal-button" value="見る" style="float: none"></span>
            </form>
        </div>
    </div>
    <?php echo $this->render("right-banner.phtml") ?>
</div>