<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<center>
    <div class="content" style="background: #F0F0F0;">
        <div class="top_content clear banner">
            <!--                <div class="logo" style="float: left;">
                                <a href="#"> <img width="230" height="58" src="#" alt="Logo">
                                </a>
                            </div>-->
            <div style="position: absolute; top: 120px; right: 70px; ">
                <a href="<?php echo $this->baseUrl(); ?>/user/logout"><font style="color: #7E3500; font-weight: bold; text-decoration: underline;">ログアウト</font>
                </a>
            </div>
            <div  class="topbar-username"><big>ようこそ!</bigF><?php echo $this->user_info['name']; ?></div>
        </div>
        <!--Menu Tab Bar-->
        <div class="menus clear">
            <div class="mn">
                <a class="home" href="<?php echo $this->baseUrl() ?>/student/index">
                    <font style="color: white;">ホーム</font>
                </a>
            </div>
            <div title="" class="mn first_mn"><a href="<?php echo $this->baseUrl(); ?>/student/myLesson"><font style="color: white;">マイ授業</font></a>
            </div>
            <!--                <div class="mn" title=""><a href="#"><font style="color: white;">授業リスト</font></a>
                            </div>-->
            <div title="" class="mn "><a href="<?php echo $this->baseUrl(); ?>/student/payment"><font style="color: white;">支払い</a>
            </div>
            <div title="" class="mn "><a href="<?php echo $this->baseUrl(); ?>/student/profile"><font style="color: white;">プロファイル</font></a>
            </div>
        </div>

        <div class="row-show float-left">
            <div class="lesson_register_content" style="width: 98%;">
                <div class="full-width lesson-big-title">
                    <?php echo $this->lessonInfo['title']; ?>
                </div>
                <table cellpadding='1' cellspacing='0' border='0' style="width: 100%;border-width: thin;border-style: solid;">
                    <tbody>
                        <tr valign="top">
                            <!--Left content-->
                            <td style="width: 22%;">
                                <div class="full-width" style="font-weight: bolder; color: white; padding-top: 3px;font-size: 16px; background: #51A007; width: 100%;">
                                    ファイル一覧
                                </div>
                                <div class="full-width" style="background: wheat; padding-top: 3px;">
                                    <?php
                                    $count = 0;
                                    foreach ($this->files as $file) {
                                        $count++;
                                        $fileType = explode(".", $file['filename'])[1];
                                        if ($fileType == 'pdf') {
                                            ?>
                                            <a href="<?php echo $this->baseUrl(); ?>/student/file?lessonId=<?php echo $this->lessonInfo['id']; ?>&currentFile=<?php echo $file['id']; ?>">
                                                <div class="full-width" style="font-size: 16px; font-weight: bold; margin: 5px;">
                                                    <font style="color: #7E3500">
                                                    <?php echo $count . '.'; ?>
                                                    </font>
                                                    <?php echo $file['filename']; ?>
                                                    <img src="<?php echo $this->baseUrl(); ?>/public/images/pdf.png" width="16" height="16">
                                                </div>
                                            </a>           
                                            <?php
                                        } else if ($fileType == 'mp3') {
                                            ?>
                                            <a href="<?php echo $this->baseUrl(); ?>/student/file?lessonId=<?php echo $this->lessonInfo['id']; ?>&fileId=<?php echo $file['id']; ?>">
                                                <div class="full-width" style="font-size: 16px;  font-weight: bold; margin: 5px;">
                                                    <font style="color: #7E3500">
                                                    <?php echo $count . '.'; ?>
                                                    </font>
                                                    <?php echo $file['filename']; ?>
                                                    <img src="<?php echo $this->baseUrl(); ?>/public/images/audio.png" width="16" height="16">
                                                </div>
                                            </a>              
                                            <?php
                                        } else if ($fileType = 'mp4') {
                                            ?>
                                            <a href="<?php echo $this->baseUrl(); ?>/student/file?lessonId=<?php echo $this->lessonInfo['id']; ?>&fileId=<?php echo $file['id']; ?>">
                                                <div class="full-width" style="font-size: 16px;  font-weight: bold; margin: 5px;">
                                                    <font style="color: #7E3500">
                                                    <?php echo $count . '.'; ?>
                                                    </font>
                                                    <?php echo $file['filename']; ?>
                                                    <img src="<?php echo $this->baseUrl(); ?>/public/images/mp4.png" width="16" height="16">
                                                </div>
                                            </a>       
                                            <?php
                                        } else if ($fileType = 'png' || $fileType == 'jpg' || $fileType == 'jpeg') {
                                            ?>
                                            <a href="<?php echo $this->baseUrl(); ?>/student/file?lessonId=<?php echo $this->lessonInfo['id']; ?>&fileId=<?php echo $file['id']; ?>">
                                                <div class="full-width" style="font-size: 16px;  font-weight: bold; margin: 5px;">
                                                    <font style="color: #7E3500">
                                                    <?php echo $count . '.'; ?>
                                                    </font>
                                                    <?php echo $file['filename']; ?>
                                                    <img src="<?php echo $this->baseUrl(); ?>/public/images/image.png" width="16" height="16">
                                                </div>
                                            </a> 
                                            <?php
                                        } else if ($fileType == 'tsv') {
                                            ?>
                                            <a href="<?php echo $this->baseUrl(); ?>/student/file?lessonId=<?php echo $this->lessonInfo['id']; ?>&fileId=<?php echo $file['filename']; ?>">
                                                <div class="full-width" style="font-size: 16px;  font-weight: bold; margin: 5px;">
                                                    <font style="color: #7E3500">
                                                    <?php echo $count . '.'; ?>
                                                    </font>
                                                    <?php echo $file['filename']; ?>
                                                    <img src="<?php echo $this->baseUrl(); ?>/public/images/test.png" width="16" height="16">
                                                </div>
                                            </a> 
                                            <?php
                                        }
                                    }
                                    ?>
                                </div>
                            </td>
                            <!--View-->
                            <td>
                                <div class="full-width" style="font-weight: bolder; color: white; padding-top: 3px; padding-bottom: 3px; font-size: 16px; background: #51A007;">
                                    ファイル内容
                                </div>
                                <div style="margin: 10px; width: 95%;min-height: 500px;max-height: 800px; border-color: #007F9F; border-style: solid; border-width: thin;">
                                    <!--Content here-->
                                    <?php
                                    $currentFile = explode(".", $this->currentFile['filename'])[1];
                                    if ($currentFile == 'pdf') {
                                        ?>
                                        <embed src = "<?php echo $this->baseUrl(); ?>/<?php echo $this->currentFile['location']; ?>"
                                               width = "100%" height = "600px;">
                                               <?php
                                           } else if ($currentFile == 'mp3') {
                                               ?>
                                        <audio controls>
                                            <source src="<?php echo $this->baseUrl(); ?>/<?php echo $this->currentFile['location']; ?>" type="audio/mpeg">
                                            <embed height="100" width="90%" src="<?php echo $this->baseUrl(); ?>/<?php echo $this->currentFile['location']; ?>">
                                        </audio>
                                        <?php
                                    } else if ($currentFile == 'mp4') {
                                        ?>
                                        <video width="100%" autoplay="false" controls>
                                            <source src="<?php echo $this->baseUrl(); ?>/<?php echo $this->currentFile['location']; ?>" type="video/mp4">
                                        </video>                                    
                                        <?php
                                    }
                                    ?>
                                </div>
                                <script>
                                    function showReportForm()
                                    {
                                        $("#report_form").show();
                                        $("#btn_report").hide();
                                    }

                                    function hideReportForm() {
                                        $("#report_form").hide();
                                        $("#btn_report").show();
                                    }

                                    function hideReport() {
                                        $("#report_form").hide();
                                        $("#btn_report").hide();
                                    }

                                </script>
                                <div id="report_form" style="display: none; width: 60%; margin-left: 100px; border: none; border-radius: 4px;">
                                    <form method="post" action="<?php echo $this->baseUrl(); ?>/student/file?lessonId=<?php echo $this->lessonInfo['id']; ?>&fileId=<?php echo $this->currentFile['id']; ?>">
                                        <textarea cols="60" name="report_content" rows="5" placeholder="理由" style="border-style: solid; border-width: medium; border-radius: 3px;"></textarea>
                                        <input type="submit" onclick="hideReport();" value="賛成" class="showlogfromm" style="width: 80px; height: 30px; margin-left: 180px;">
                                        <input id="btn_sen_report" onclick="hideReportForm();" type="button" value="キャンセル" class="register-cus" style="width: 80px; height: 30px;">
                                    </form>
                                </div>


                                <!--Report button-->
                                <div class="full-width" style="margin: 0px auto;" id="btn_report">
                                    <button id="btn_report" onclick="showReportForm();" style="border: none; border-radius: 4px; padding: 5px; margin-left: 10px; background: #007F9F;  color: white;">違犯レポート</button>
                                </div>



                                <!--Comment file-->
                                <div style="width: 70%; margin-left: 100px;">
                                    <?php
                                    if (isset($this->comments)) {
                                        ?>
                                        //TODO
                                        <?php
                                    }
                                    ?>
                                </div>
                                <div style="width: 70%; margin-left: 100px;">
                                    <textarea cols="60" rows="5"></textarea>

                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</center>
<?php
if (isset($this->reportNotify)) {
    ?>
    <script type="text/javascript">
        alert("<?php echo $this->reportNotify; ?>");
        hideReport();
    </script>
    <?php
    unset($this->reportNotify);
}
?>