
<!DOCTYPE html>
<html>
    <head>
        <script type="text/javascript"
        src="../public/js/libraries.js"></script>
        <script type="text/javascript"
        src="../public/js/jquery_ready.js"></script>
    </head>
    <body>
    <center>
        <div class="top_content clear">
            <div class="logo" style="float: left;">
                <a href="#"> <img width="230" height="58" src="#" alt="Logo">
                </a>
            </div>
            <div align="right" style="float: right; margin-top: 20px;">
                <a href="../user/logout"><button class="register-cus">ログアウト</button>
                </a>
            </div>
        </div>
        <div class="menus clear">
            <ul>
                <li class="home mn"><a href="#"></a>
                </li>
                <li title="" class="mn first_mn"><a href="#">マイ授業</a>
                </li>
                <li class="mn" title=""><a href="#">授業リスト</a>
                </li>
                <li title="" class="mn "><a href="#">支払い</a>
                </li>
                <li title="" class="mn "><a href="javascript:;">プロファイル</a>
                </li>
            </ul>
        </div>



        <div>
            <button style="float: left; " name="btn_tag" class="showlogfromm">タグ</button>
            <button style="float: left; margin-left: 10px;" name="btn_teacher" class="register-cus">先生</button>
            <div  style="float: right;">
                <form action="#">
                    <input type="text" name="q" class="input_search" placeholder="検索内容"/>
                    <input class="btnsm" name="sa" style="width: 37px; height: 38px;" type="image" src="../public/images/bg_search_right.jpg">
                </form>
            </div>
        </div>

        <div class="containt_center_cen clear">
            <table class="list_lession_content" style="border: 1px;border-style: solid; border-color: navy" cellpadding="0" cellspacing="0" border="0">
                <tbody>
                    <tr>
                        <td valign="top" class="containt_center_cen_left">
                            <div style="width: 100%;"></div>
                            <?php
                            for ($i = 0; $i < 10; $i++) {
                                ?>
                                <button class="showlogfromm" style="margin-bottom: 5px;">タグ名</button>
                                <?php
                            }
                            ?>
                        </td>
                        <td valign="top" class="containt_center_cen_right">
                            <?php
                            for ($i = 0; $i < 10; $i++) {
                                ?>
                                <div class="lession-content row-input">
                                    <a href=""><h3  class="lession-title">C programming</h3></a>
                                    <div class="row-input">
                                        <div class="lession-teacher">ごんだい先生</div>
                                        <div class="lession-time">2013年02月20日</div>
                                    </div>
                                    <div id="lession-description" class="lession-description">この授業はCプログラミング言語について、教えてさせます。</div>
                                </div>
                            <?php }
                            ?>

                        </td>
                    </tr>
                </tbody>
            </table>
        </div>

    </center>
</body>
</html>
