<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<center>
    <div class="content" style="background: #F0F0F0;">
        <div class="top_content clear banner">
            <!--                <div class="logo" style="float: left;">
                                <a href="#"> <img width="230" height="58" src="#" alt="Logo">
                                </a>
                            </div>-->
            <div style="position: absolute; top: 120px; right: 70px; ">
                <a href="../user/logout"><font style="color: #7E3500; font-weight: bold; text-decoration: underline;">ログアウト</font>
                </a>
            </div>
            <div  class="topbar-username"><big>ようこそ!</bigF><?php echo $this->user_info['name']; ?></div>
        </div>
        <!--Menu Tab Bar-->
        <div class="menus clear">
            <div class="mn first_mn">
                <a class="home" href="../student/index">
                    <font style="color: white;">ホーム</font>
                </a>
            </div>
            <div title="" class="mn"><a href="#"><font style="color: white;">マイ授業</font></a>
            </div>
            <!--                <div class="mn" title=""><a href="#"><font style="color: white;">授業リスト</font></a>
                            </div>-->
            <div title="" class="mn "><a href="#"><font style="color: white;">支払い</a>
            </div>
            <div title="" class="mn "><a href="../student/profile"><font style="color: white;">プロファイル</font></a>
            </div>
        </div>
        <!--Function tab bar-->
        <div class="row-show">
            <a href="../student/index?type=1"><button style="margin-top: 10px;"  name="btn_tag" class="showlogfromm float-left">タグ</button></a>
            <a href="../student/index?type=2">
                <button style="margin-left: 10px; margin-top: 10px;" name="btn_teacher" class="register-cus float-left">
                    先生</button>
            </a>
            <div  style="margin-top: 10px;" class="float-right">
                <form action="#" style="height: 30px;">
                    <input type="text" name="q" class="input_search" placeholder="検索内容"/>
                    <input  name="sa" type="button" class="button-search" value="検索">
                </form>
            </div>
        </div>
        <!--Content tab bar-->
        <div class="containt_center_cen clear">
            <table class="list_lession_content"  cellpadding="0" cellspacing="0" border="0">
                <tbody>
                    <tr>
                        <td valign="top" class="containt_center_cen_left">
                            <div style="width: 100%"><input type="text" style="width: 90%; margin-left: 10px; border: none; background: #7E3500; height: 25px;"></div>
                            <div style="width: 100%;"></div>
                            <?php
                            /* タグが表現の倍は */
                            $type = $this->type;
                            if ($type == 1) {
                                if (isset($this->tags)) {
                                    for ($i = 0; $i < count($this->tags); $i++) {
                                        ?>
                                        <button class="tag-item">
                                            <?php
                                            echo $this->tags[$i]['tag_name'];
                                            ?>
                                        </button>
                                        <?php
                                    }
                                } else {
                                    echo "タグがない";
                                }
                            } else if ($type == 2) {
                                /* 先生表現の倍は */
                                if (isset($this->teachers)) {
                                    for ($i = 0; $i < count($this->teachers); $i++) {
                                        ?>
                                        <button class="teacher-item">
                                            <?php
                                            echo $this->teachers[$i]['name'];
                                            ?>
                                        </button>
                                        <?php
                                    }
                                } else {
                                    echo $type;
                                    echo "先生がいない";
                                }
                            }
                            ?>
                        </td>
                        <td valign="top" class="containt_center_cen_right">
                            <?php
                            $counter = 0;
                            foreach ($this->data as $item) {
                                $counter ++;
                                if ($counter % 2 == 1) {
                                    ?>
                                    <div class="row-show">
                                        <div class="lession-content-left">
                                            <div class="row-show">
                                                <a href=""><div class="lession-title">C programming</div></a>
                                            </div>
                                            <hr class="title">
                                            <div class="row-show">
                                                <div class="lession-teacher"><b>先生: </b> ごんだい</div>
                                                <div class="lession-time">2013年02月20日</div>
                                            </div>
                                            <hr class="title">
                                            <div class="row-show">
                                                <div id="lession-description" class="lession-description">この授業はCプログラミング言語について、教えてさせます。</div>
                                            </div>
                                            <div class="row-show">
                                                <div class="lession-bottom">
                                                    <img src="../public/images/num-like.png" width="15" height="15"> <font class="num-like-comment">100</font>
                                                    <img src="../public/images/num-comment.png" width="15" height="15"> <font class="num-like-comment">100</font>
                                                </div>
                                                <div style="float: right; position: relative; top: 30px;bottom: 0;"><a href="../student/lession-detail" class="link-view-detail">詳細</a></div>
                                            </div>
                                        </div>  
                                        <?php
                                    } else if ($counter % 2 == 0) {
                                        ?>
                                        <div class="lession-content-right">
                                            <div class="row-show">
                                                <a href=""><div class="lession-title">C programming</div></a>
                                            </div>
                                            <hr class="title">
                                            <div class="row-show">
                                                <div class="lession-teacher"><b>先生: </b> ごんだい</div>
                                                <div class="lession-time">2013年02月20日</div>
                                            </div>
                                            <hr class="title">
                                            <div class="row-show">
                                                <div id="lession-description" class="lession-description">この授業はCプログラミング言語について、教えてさせます。</div>
                                            </div>
                                            <div class="row-show">
                                                <div class="lession-bottom">
                                                    <img src="../public/images/num-like.png" width="15" height="15"> <font class="num-like-comment">100</font>
                                                    <img src="../public/images/num-comment.png" width="15" height="15"> <font class="num-like-comment">100</font>
                                                </div>
                                                <div style="float: right; position: relative; top: 30px;bottom: 0;"><a href="../student/lession-detail" class="link-view-detail">詳細</a></div>
                                            </div>
                                        </div>
                                        <?php
                                    }
                                    ?>
                                </div>
                            <?php }
                            ?>

                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="paging">
                <div class="paging-center">
                    <?php
                    echo $this->paginationControl($this->data, 'Sliding', 'pageinator.phtml');
                    ?>
                </div>
            </div>
        </div>
    </div>
</center>