<center>
    <div class="content" style="background: #F0F0F0;">
        <div class="top_content clear banner">
            <!--                <div class="logo" style="float: left;">
                                <a href="#"> <img width="230" height="58" src="#" alt="Logo">
                                </a>
                            </div>-->
            <div style="position: absolute; top: 120px; right: 70px; ">
                <a href="<?php echo $this->baseUrl(); ?>/user/logout"><font style="color: #7E3500; font-weight: bold; text-decoration: underline;">ログアウト</font>
                </a>
            </div>
            <div  class="topbar-username"><big>ようこそ!</bigF><?php echo $this->user_info['name']; ?></div>
        </div>
        <!--Menu Tab Bar-->
        <div class="menus clear">
            <div class="mn">
                <a class="home" href="<?php echo $this->baseUrl(); ?>/student/index">
                    <font style="color: white;">ホーム</font>
                </a>
            </div>
            <div title="" class="mn first_mn"><a href="<?php echo $this->baseUrl(); ?>/student/myLesson"><font style="color: white;">マイ授業</font></a>
            </div>
            <!--                <div class="mn" title=""><a href="#"><font style="color: white;">授業リスト</font></a>
                            </div>-->
            <div title="" class="mn "><a href="#"><font style="color: white;">支払い</a>
            </div>
            <div title="" class="mn "><a href="<?php echo $this->baseUrl(); ?>/student/profile"><font style="color: white;">プロファイル</font></a>
            </div>
        </div>
        <!--Function tab bar-->
        <div class="row-show">
            <a href="<?php echo $this->baseUrl(); ?>/student/myLesson?type=1&tagId=0"><button style="margin-top: 10px;"  name="btn_tag" class="showlogfromm float-left">タグ</button></a>
            <a href="<?php echo $this->baseUrl(); ?>/student/myLesson?type=2&teacherId=0">
                <button style="margin-left: 10px; margin-top: 10px;" name="btn_teacher" class="register-cus float-left">
                    先生</button>
            </a>
            <div  style="margin-top: 10px;" class="float-right">
                <form action="#" style="height: 30px;" method="post">
                    <input type="text" name="keyword" class="input_search" placeholder="検索内容"/>
                    <input  name="sa" type="button" class="button-search" value="検索">
                </form>
            </div>
        </div>
        <div class="detail_layout_content">
            <table width="690" border="1" bordercolor="#d5d5d5" style="border-collapse:collapse" cellpadding="4" cellspacing="4">
                <tr align="left" class="title_table" bordercolor="4f4f4f" style="background-color: rgb(251, 251, 251); background-position: initial initial; background-repeat: initial initial;">
                    <td width="120">年・月</td>
                    <td width="120">授業数</td>
                    <td width="120">収入(VND)</td>
                    
                </tr>
                <?php if (!empty($this->paymentInfos)):?>
                <?php foreach ($this->paymentInfos as $info): ?>
                <tr align="left">
                    <td class="orange"><a href="#"><?php echo $info["time"] ?></a></td>
                    <td> <?php echo $info["total"] ?></td>
                    <td><a href="#"><?php echo $info["total"]* $this->price; ?></a></td>
                    
                </tr>
                <?php endforeach; ?>
               <?php else : echo "<tr><td colspan = '3'>データがありません</td></tr>"; ?>
               <?php endif; ?>
            </table>
            <?php //echo $this->partial("pager.phtml", array('page'=>1, 'total'=>10, 'next'=>"#", 'pre'=>"#")) ?>
            <div  style="margin-bottom: 20px; clear: both; height: 15px; border-bottom: 1px solid #ababab;"></div>
        </div>
    </div>
</center>