
<!DOCTYPE html>
<html>
    <body>
    <center>
        <div class="content">
            <div class="top_content clear banner">
                <!--                <div class="logo" style="float: left;">
                                    <a href="#"> <img width="230" height="58" src="#" alt="Logo">
                                    </a>
                                </div>-->
                <div style="position: absolute; top: 120px; right: 70px; ">
                    <a href="../user/logout"><font style="color: #7E3500; font-weight: bold; text-decoration: underline;">ログアウト</font>
                    </a>
                </div>
                <div  class="topbar-username"><big>ようこそ!</bigF><?php echo $this->user_info['name']; ?></div>
            </div>
            <!--Menu Tab Bar-->
            <div class="menus clear">
                <div class="mn "><a class="home" href="">ホーム</a></div>
                <div title="" class="mn"><a href="#"><font style="color: white;">マイ授業</font></a>
                </div>
                <div class="mn" title=""><a href="#"><font style="color: white;">授業リスト</font></a>
                </div>
                <div title="" class="mn "><a href="#"><font style="color: white;">支払い</a>
                </div>
                <div title="" class="mn first_mn"><a href="../student/profile"><font style="color: white;">プロファイル</font></a>
                </div>
            </div>
            <div>
                <table cellpadding="0" cellspacing="0">
                    <tr>
                        <!--ユーザネーム-->
                        <td>
                            ユーザ名
                        </td>
                        <td>
                            <?php echo $this->user_info['username']; ?>
                        </td>
                    </tr>
                    <tr>
                        <!--Full name-->
                        <td>名前</td>
                        <td><?php echo $this->user_info['name'] ?></td>
                    </tr>

                    <tr>
                        <!--Birthday-->
                        <td>生年月日</td>
                        <td><?php echo $this->user_info['birthday'] ?></td>
                    </tr>
                </table>
            </div>
        </div>
    </center>
</body>
</html>
