
<!DOCTYPE html>
<html>
    <body>
        <div class="content">
            <center>
                <div class="top_content clear banner">
                    <!--                <div class="logo" style="float: left;">
                                        <a href="#"> <img width="230" height="58" src="#" alt="Logo">
                                        </a>
                                    </div>-->
                    <div style="position: absolute; top: 120px; right: 70px; ">
                        <a href="../user/logout"><font style="color: #7E3500; font-weight: bold; text-decoration: underline;">ログアウト</font>
                        </a>
                    </div>
                    <div  class="topbar-username"><big>ようこそ!</bigF><?php echo $this->user_info['name']; ?></div>
                </div>
                <!--Menu Tab Bar-->
                <div class="menus clear">
                    <div class="mn">
                        <a class="home" href="../student/index">
                            <font style="color: white;">ホーム</font>
                        </a>
                    </div>
                    <div title="" class="mn"><a href="#"><font style="color: white;">マイ授業</font></a>
                    </div>
                    <!--                    <div class="mn" title=""><a href="#"><font style="color: white;">授業リスト</font></a>
                                        </div>-->
                    <div title="" class="mn "><a href="#"><font style="color: white;">支払い</a>
                    </div>
                    <div title="" class="mn first_mn"><a href="../student/profile"><font style="color: white;">プロファイル</font></a>
                    </div>
                </div>
                <div class="row-show" style="background: #F0F0F0;">
                    <font style="text-align: center; color: #bb670a; font-size: 23px; width: 100%; float: left; margin-top: 20px;margin-bottom: 20px; font-weight: bold;">ユーザ情報</font>
                    <table cellpadding="10" cellspacing="1" style="border-style: double; border-color: #093; width: 50%;padding-left: 40px;">
                        <tr class="profile">
                            <!--ユーザネーム-->
                            <td>
                                <b>ユーザ名:</b>
                            </td>
                            <td colspan="2">
                                <font style="font-family: fantasy; font-size: 18px;">
                                <?php echo $this->user_info['username']; ?>
                                </font>
                            </td>
                        </tr>
                        <tr class="profile">
                            <!--Full name-->
                            <td><b>名前:</b></td>
                            <td colspan="2"><font style="font-family: serif; font-size: 18px;">
                                <?php echo $this->user_info['name'] ?>
                                </font>
                            </td>
                        </tr>

                        <tr class="profile">
                            <!--Birthday-->
                            <td><b>生年月日:</b></td>
                            <td colspan="2"><?php echo str_replace('-', '/', $this->user_info['birthday']); ?></td>
                        </tr>

                        <tr class="profile">
                            <!--Address-->
                            <td><b>アドレス:</b></td>
                            <td colspan="2"><?php echo $this->user_info['address'] ?></td>
                        </tr>

                        <tr class="profile">
                            <!--Email-->
                            <td><b>イーメール:</b></td>
                            <td><?php echo $this->user_info['email'] ?></td>
                        </tr>

                        <tr class="profile">
                            <!--Phone number-->
                            <td><b>電話番後:</b></td>
                            <td colspan="2"><?php echo $this->user_info['phone'] ?></td>
                        </tr>

                        <tr class="profile">
                            <!--Bank account-->
                            <td><b>銀後アカウント:</b></td>
                            <td colspan="2"><?php echo $this->user_info['bank_account'] ?></td>
                        </tr>

                        <tr class="profile">
                            <!--Role-->
                            <td><b>役割:</b></td>
                            <td colspan="2"><?php
                                if ($this->user_info['role'] == 1) {
                                    echo "学生";
                                } else {
                                    echo "先生";
                                }
                                ?></td>
                        </tr>
                        <tr col="3">
                            <td><a href="../student/profileChangeInfo"><button class="showlogfromm">情報更新</button></a></td>
                            <td><a href="../student/changePassword"><button class="showlogfromm">パスワード更新</button></a></td>
                            <td style="width: 160px;"><a href="../student/changeSecretQA"><button class="showlogfromm">機密質問情報を更新</button></a></td>
                        </tr>
                    </table>
                </div>
            </center>
        </div>

    </body>
</html>
