<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<center>
    <div class="content" style="background: #F0F0F0;">
        <div class="top_content clear banner">
            <!--                <div class="logo" style="float: left;">
                                <a href="#"> <img width="230" height="58" src="#" alt="Logo">
                                </a>
                            </div>-->
            <div style="position: absolute; top: 120px; right: 70px; ">
                <a href="<?php echo $this->baseUrl(); ?>/user/logout"><font style="color: #7E3500; font-weight: bold; text-decoration: underline;">ログアウト</font>
                </a>
            </div>
            <div  class="topbar-username"><big>ようこそ!</bigF><?php echo $this->user_info['name']; ?></div>
        </div>
        <!--Menu Tab Bar-->
        <div class="menus clear">
            <div class="mn first_mn">
                <a class="home" href="<?php echo $this->baseUrl() ?>/student/index">
                    <font style="color: white;">ホーム</font>
                </a>
            </div>
            <div title="" class="mn"><a href="#"><font style="color: white;">マイ授業</font></a>
            </div>
            <!--                <div class="mn" title=""><a href="#"><font style="color: white;">授業リスト</font></a>
                            </div>-->
            <div title="" class="mn "><a href="#"><font style="color: white;">支払い</a>
            </div>
            <div title="" class="mn "><a href="<?php echo $this->baseUrl(); ?>/student/profile"><font style="color: white;">プロファイル</font></a>
            </div>
        </div>
        <div class="row-show float-left">
            <div  style="margin: 0px auto;">
                <div style="width: 80%; color: black;" class="lesson_register_content">
                    <div class="float-left" style="text-align: left; background: #51A007; width: 100%; color: white; font-weight: bold; padding-top: 10px; padding-bottom: 10px;">
                        <font style="padding-left: 30px;"><?php echo $this->lessonInfo['title']; ?></font>
                    </div>
                    <div class="row-show">
                        <table cellpadding="0" cellspacing="0" border="1"  style="border: none; text-align: center;">
                            <tbody>
                                <tr>
                                    <td>タグ</td>
                                    <td style="text-align: left; height: 30px;">
                                        <?php
                                        foreach ($this->tagsInfo as $tag) {
                                            ?>
                                            <div style="border: none; float: left; margin: 1px; border-radius: 4px; padding: 5px; background: #51A007; color: white;"> <?php echo $tag['tag_name']; ?>
                                            </div>
                                            <?php
                                        }
                                        ?>
                                    </td>
                                </tr>
                                <tr>
                                    <td style="width: 100px; text-align: center;">説明</td>
                                    <td style="text-align: left;"><?php echo $this->lessonInfo['description']; ?></td>
                                </tr>
                                <tr>
                                    <td style="text-align: center;">作成した日</td>
                                    <td style="height: 30px; font-weight: bold; font-size: 14px;">
                                        <?php
                                        $time = $this->lessonInfo['create_time'];
                                        $correct = explode(" ", $time)[0];
                                        $arr = explode("-", $correct);
                                        $year = $arr[0];
                                        $mon = $arr[1];
                                        $day = $arr[2];
                                        echo $year . "年" . $mon . "月" . $day . "日";
                                        ?>

                                    </td>
                                </tr>

                                <tr>
                                    <td>学生数</td>
                                    <td style="height: 30px; font-weight: bold; font-size: 14px;">
                                        <?php
                                        echo $this->numStudent;
                                        ?></td>
                                </tr>

                                <tr>
                                    <td colspan="2" style="text-align: left; height: 30px; padding-left: 10px; font-weight: bold; font-size: 14px;">アップロードしたファイル</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</center>