<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<center>
    <div class="content" style="background: #F0F0F0;">
        <div class="top_content clear banner">
            <!--                <div class="logo" style="float: left;">
                                <a href="#"> <img width="230" height="58" src="#" alt="Logo">
                                </a>
                            </div>-->
            <div style="position: absolute; top: 120px; right: 70px; ">
                <a href="<?php echo $this->baseUrl() ?>/user/logout"><font style="color: #7E3500; font-weight: bold; text-decoration: underline;">ログアウト</font>
                </a>
            </div>
            <div  class="topbar-username"><big>ようこそ!</bigF><?php echo $this->user_info['name']; ?></div>
        </div>
        <!--Menu Tab Bar-->
        <div class="menus clear">
            <div class="mn first_mn">
                <a class="home" href="<?php echo $this->baseUrl() ?>/student/index">
                    <font style="color: white;">ホーム</font>
                </a>
            </div>
            <div title="" class="mn"><a href="#"><font style="color: white;">マイ授業</font></a>
            </div>
            <!--                <div class="mn" title=""><a href="#"><font style="color: white;">授業リスト</font></a>
                            </div>-->
            <div title="" class="mn "><a href="#"><font style="color: white;">支払い</a>
            </div>
            <div title="" class="mn "><a href="<?php echo $this->baseUrl() ?>/student/profile"><font style="color: white;">プロファイル</font></a>
            </div>
        </div>
        <!--Function tab bar-->
        <div class="row-show">
            <a href="<?php echo $this->baseUrl() ?>/student/index?type=1"><button style="margin-top: 10px;"  name="btn_tag" class="showlogfromm float-left">タグ</button></a>
            <a href="<?php echo $this->baseUrl() ?>/student/index?type=2">
                <button style="margin-left: 10px; margin-top: 10px;" name="btn_teacher" class="register-cus float-left">
                    先生</button>
            </a>
            <div  style="margin-top: 10px;" class="float-right">
                <form action="#" style="height: 30px;">
                    <input type="text" name="q" class="input_search" placeholder="検索内容"/>
                    <input  name="sa" type="button" class="button-search" value="検索">
                </form>
            </div>
        </div>
        <!--Content tab bar-->
        
    </div>
</center>