<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<center>
    <div class="content" style="background: #F0F0F0;">
        <div class="top_content clear banner">
            <!--                <div class="logo" style="float: left;">
                                <a href="#"> <img width="230" height="58" src="#" alt="Logo">
                                </a>
                            </div>-->
            <div style="position: absolute; top: 120px; right: 70px; ">
                <a href="<?php echo $this->baseUrl(); ?>/user/logout"><font style="color: #7E3500; font-weight: bold; text-decoration: underline;">ログアウト</font>
                </a>
            </div>
            <div  class="topbar-username"><big>ようこそ!</bigF><?php echo $this->user_info['name']; ?></div>
        </div>
        <!--Menu Tab Bar-->
        <div class="menus clear">
            <div class="mn first_mn">
                <a class="home" href="<?php echo $this->baseUrl() ?>/student/index">
                    <font style="color: white;">ホーム</font>
                </a>
            </div>
            <div title="" class="mn"><a href="#"><font style="color: white;">マイ授業</font></a>
            </div>
            <!--                <div class="mn" title=""><a href="#"><font style="color: white;">授業リスト</font></a>
                            </div>-->
            <div title="" class="mn "><a href="#"><font style="color: white;">支払い</a>
            </div>
            <div title="" class="mn "><a href="<?php echo $this->baseUrl(); ?>/student/profile"><font style="color: white;">プロファイル</font></a>
            </div>
        </div>
        <div class="row-show float-left">
            <div  style="margin: 0px auto;">
                <div style="width: 80%; color: black;" class="lesson_register_content">
                    <div class="float-left" >タイトル：<?php echo $this->lessonInfo['title']; ?></div>
                    <div class="row-show">
                        <table cellpadding="0" cellspacing="0" border="0">
                            <tbody>
                                <tr>
                                    <td colspan="2">Tag1, tag2</td>
                                </tr>
                                <tr>
                                    <td>説明</td>
                                    <td><?php echo $this->lessonInfo['description']; ?></td>
                                </tr>
                                <tr>
                                    <td>作成した日</td>
                                    <td><?php echo $this->lessonInfo['create_time']; ?>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</center>