
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/public/css/admin-common-style.css"); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/public/css/ta123_style.css"); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/public/css/ta123_style2.css"); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/public/css/common-style.css"); ?>

<?php $this->headScript()->appendFile($this->baseUrl() . "/public/js/jquery.min.js"); ?>

<style type="text/css">
    .content {
        width: 1000px;
        min-height: 528px;
        margin: 0px auto;
        margin-top: 10px;
        margin-bottom: 10px;
        background-color: whitesmoke;
        box-shadow: 0px 0px 5px 1px gray;
    }
    .left-content {
        width: 186px;
        height: 463px;
        float: left;
        margin-left: 10px;
        margin-top: 51px;
        border: 1px solid gray;
        border-radius: 3px;
    }
    .right-content {
        padding: 10px;
        width: 780px;
        float: left;
    }
    .bottom-border {
        line-height: 1px;
    }
    .lesson-item {
        padding: 10px;
        border: 1px solid gray;
        margin-top: 5px;
        border-radius: 3px;
    }
    .lesson-left {
        width: 200px;
        height: 100px;
        float: left;
        position: relative;
    }
    .lesson-right {
        width: 541px;
        height: 100px;
        float: left;
        border: 1px solid green;
        padding: 5px;
        margin-left: 5px;
    }
    .lesson-bottom {
        line-height: 1px;
    }
    .lesson-title {
        padding: 5px;
        color: white;
        background-color: yellowgreen;
        border-radius: 3px;
        height: 20px;
        line-height: 22px;
    }
    .lesson-teacher {
        font-size: 16px;
        font-weight: bold;
        margin-top: 5px;
    }
    .lesson-created {
        color: gray;
    }
    .lesson-like {
        position: absolute;
        bottom: -10px;
    }
    .lesson-like span {
        padding-right: 10px;
    }
    .lesson-item:hover {
        box-shadow: 0px 0px 3px 1px yellowgreen;
    }
    .left-title {
        width: 87px;
        float: left;
        padding: 3px;
        font-size: 18px;
        font-weight: bold;
        text-align: center;
        cursor: pointer;
    }
    .left-title:hover {
        text-shadow: 0px 0px 5px gray;
        text-decoration: underline;
    }
    .title-active {
        background-color: yellowgreen;
        color: black;
    }
    .filter-item {
        padding: 10px 5px;
        border-top: 1px solid gray;
    }
    .filter-item:hover {
        cursor: pointer;
        color: orange;
    }
    .filter-item-active {
        box-shadow: 0px 0px 3px 1px yellowgreen;
    }
    .paging {
        width: 100px;
        margin: 0px auto;
    }
    .paging-item {
        height: 20px;
        margin: 5px;
        float: left;
        text-decoration: underline;
    }
    .top-content {
        margin: 10px 10px 0px 0px;
        float: right;
    }
    .top-content input {
        padding: 3px;
    }
    .report-num {
        padding-right: 20px;
        color: red;
        font-weight: bold;
        text-decoration: underline;
    }
</style>

<script type="text/javascript">
    $(document).ready(function(){
        $(".left-title").click(function(){
            var type = $(this).data('type');
            if (type == 'tag') {
                $('.filter-list-tag').show();
                $('.filter-list-teacher').hide();
                $('.title-active').removeClass('title-active');
                $(this).addClass('title-active');
            } else {
                $('.filter-list-tag').hide();
                $('.filter-list-teacher').show();
                $('.title-active').removeClass('title-active');
                $(this).addClass('title-active');
            }
        });
        var type = "<?php
            if (isset($this->tagId)) {
                echo "tag";
            } else if (isset($this->teacherId)) {
                echo "teacher";
            } else {
                echo "tag";
            }
        ?>";
        if (type === "tag") {
            $('.filter-list-tag').show();
            $('.filter-list-teacher').hide();
        } else {
            $('.filter-list-tag').hide();
            $('.filter-list-teacher').show();
        }
        
        $(".sort_asc").change(function(){
            var link = "<?php echo $this->baseUrl(); ?>/admin/lesson/index";
            link += "?sort_asc="+$(this).val();
            link += "&sort_type=<?php echo $this->sortType; ?>";
            <?php if (isset($this->tagId)) { ?>
                link += "&tagId=<?php echo $this->tagId; ?>";
            <?php } else if (isset($this->teacherId)) { ?>
                link += "&teacherId=<?php echo $this->teacherId; ?>";
            <?php } else if (isset($this->searchText)) { ?>
                link += "&text=<?php echo $this->searchText; ?>";
            <?php } else if (isset($this->copyright)) { ?>
                link += "&copyright=<?php echo $this->copyright; ?>";
            <?php } ?>
            window.top.location = link;
        });
        
        $(".sort_type").change(function(){
            var link = "<?php echo $this->baseUrl(); ?>/admin/lesson/index";
            link += "?sort_type="+$(this).val();
            link += "&sort_asc=<?php echo $this->asc; ?>";
            <?php if (isset($this->tagId)) { ?>
                link += "&tagId=<?php echo $this->tagId; ?>";
            <?php } else if (isset($this->teacherId)) { ?>
                link += "&teacherId=<?php echo $this->teacherId; ?>";
            <?php } else if (isset($this->searchText)) { ?>
                link += "&text=<?php echo $this->searchText; ?>";
            <?php } else if (isset($this->copyright)) { ?>
                link += "&copyright=<?php echo $this->copyright; ?>";
            <?php } ?>
            window.top.location = link;
        });
    });
</script>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php echo $this->render('admin-layout.phtml') ?>
<div class="content">
    
    <div class="top-content">
        <form method="get" action='<?php echo $this->baseUrl(); ?>/admin/lesson/index'>
            <a href="<?php echo $this->baseUrl(); ?>/admin/lesson/index?copyright=false">
                <span class="report-num"><?php echo $this->reportsNum; ?>レポート</span>
            </a>
            <?php if ($this->searchText) { ?>
            <span>
                <span>検索</span>
                <span>"<?php echo $this->searchText; ?>"</span>
                <span>：<?php echo $this->data->getTotalItemCount(); ?>結果</span>
            </span>
            <?php } ?>
            <select class="sort_asc" name="sort_asc" style="height: 26px;width: 70px;">
                <option value="0" <?php if ($this->asc == 0) { echo "selected"; } ?>>昇順</option>
                <option value="1" <?php if ($this->asc == 1) { echo "selected"; } ?>>降順</option>
            </select>
            <select class="sort_type" name="sort_type" style="height: 26px;width: 90px;">;
                <option value="0" <?php if ($this->sortType == 0) { ?> selected <?php } ?>>タイトル</option>
                <option value="1" <?php if ($this->sortType == 1) { ?> selected <?php } ?>>時間</option>
                <option value="2" <?php if ($this->sortType == 2) { ?> selected <?php } ?>>ビュー数</option>
                <option value="3"  <?php if ($this->sortType == 3) { ?> selected <?php } ?>>ライク数</option>
            </select>
            <input class="search-text" name="searchText" type="text" placeholder="検索テキスト" 
                <?php if ($this->searchText) echo "value='".$this->searchText."'"; ?>>
            <input type="submit" class="normal-button search-btn" value="検索">
        </form>
    </div>
    
    <div class="left-content">
        <div class="left-title <?php 
            if($this->tagId) echo "title-active";
            if (!$this->tagId && !isset($this->teacherId)) echo "title-active";
        ?>" data-type="tag">タグ</div>
        <div class="left-title <?php if(isset($this->teacherId)) echo "title-active";?>" data-type="teacher">先生</div>
        <div class="bottom-border">&nbsp;</div>
        <div class="filter-list-tag">
            <a href="<?php echo $this->baseUrl(); ?>/admin/lesson/index?tagId=0">
                <div class="filter-item<?php if ($this->tagId == 0 || !$this->tagId) {echo " filter-item-active";} ?>">
                    全部
                </div>
            </a>
            <?php foreach($this->tags as $tag) {
                ?>
                <a href="<?php echo $this->baseUrl(); ?>/admin/lesson/index?tagId=<?php echo $tag['id']; ?>">
                    <div class="filter-item<?php if ($tag['id'] == $this->tagId) {echo " filter-item-active";} ?>">
                        <?php echo $tag['tag_name']; ?>
                    </div>
                </a>
                <?php
            } ?>
        </div>
        <div class="filter-list-teacher">
            <a href="<?php echo $this->baseUrl(); ?>/admin/lesson/index?teacherId=0">
                <div class="filter-item<?php if ($this->teacherId == 0 || !$this->teacherId) {echo " filter-item-active";} ?>">
                    全部
                </div>
            </a>
            <?php foreach($this->teachers as $teacher) {
                ?>
                <a href="<?php echo $this->baseUrl(); ?>/admin/lesson/index?teacherId=<?php echo $teacher['id']; ?>">
                    <div class="filter-item<?php if ($teacher['id'] == $this->teacherId) {echo " filter-item-active";} ?>">
                        <?php echo $teacher['name']; ?>
                    </div>
                </a>
                <?php
            } ?>
        </div>
    </div>
    <div class="right-content">
        <?php
        foreach ($this->data as $item) {
        ?>
        <div class="lesson-item">
            <a href="<?php echo $this->baseUrl(); ?>/admin/lesson/lesson?do=view&lesson_id=<?php echo $item['id']; ?>">
                <div class="lesson-left">
                    <div class="lesson-title"><?php echo $item['title']; ?></div>
                    <div class="lesson-teacher">先生: <?php echo $item['name']; ?></div>
                    <div class="lesson-created"><?php echo $item['create_time']; ?></div>

                    <div class="lesson-like">
                        <img src="<?php echo $this->baseUrl(); ?>/public/images/num-like.png" width="15" height="15">
                        <span class="num-like-comment"><?php echo $item['num_like']; ?></span>
                        <img src="<?php echo $this->baseUrl(); ?>/public/images/num-view.png" width="15" height="15">
                        <span class="num-like-comment"><?php echo $item['view']; ?></span>
                        <?php if ($item['is_reported']) { ?>
                            <img src="<?php echo $this->baseUrl(); ?>/public/images/copyright_report.png" width="30" height="30">
                        <?php } ?>
                        <?php if ($item['status'] == 0) { ?>
                            <img src="<?php echo $this->baseUrl(); ?>/public/images/locked.png" width="30" height="30">
                        <?php } ?>
                    </div>
                </div>
                <div class="lesson-right">
                    <div>
                        <?php echo $item['description']; ?>
                    </div>
                </div>
                <div class="lesson-bottom">&nbsp;</div>
            </a>
        </div>
        <?php
        }
        ?>
        <div class="paging">
            <div class="page-item">
                <?php
                if ($this->numpage > 1) {
                    echo $this->paginationControl(
                                $this->data, 
                                'Sliding', 
                                'pageinator.phtml', 
                                array(
                                    "tagId" => $this->tagId,
                                    "teacherId" => $this->teacherId,
                                    "searchText" => $this->searchText,
                                    "copyright" => $this->copyright,
                                    "sortType" => $this->sortType,
                                    "asc" => $this->asc
                                )
                            );
                }
                ?>
            </div>
        </div>
    </div>
    <div class="bottom-border">&nbsp;</div>
</div>