
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<center>
    <div class="content" style="background: #F0F0F0;">
        
        <!--Content tab bar-->
        <div class="containt_center_cen clear" style="min-height: 600px;">
            <table class="list_lession_content"  cellpadding="0" cellspacing="0" border="0">
                <tbody>
                    <tr>
                        <td valign="top" class="containt_center_cen_left">
                            
                        </td>
                        <td valign="top" class="containt_center_cen_right">
                            <?php
                            $counter = 0;
                            foreach ($this->data as $item) {
                                if ($counter % 2 == 0) {
                                    ?>
                                    <div class="row-show">
                                        <div class="lession-content-left">
                                            <table cellpadding="1" cellspacing="4" border="0" style="width: 100%;margin: 0px auto;">
                                                <tbody>
                                                    <tr>
                                                        <td style="width: 100%;" colspan="1" class="lession-title"><?php echo $item['title']; ?></td>
                                                    </tr>
                                                    <tr><td><hr></td></tr>
                                                    <tr>
                                                        <td class="lession-teacher"><b>先生: </b><?php echo $item['name']; ?></td>
                                                        <td class="lession-time"><?php echo $item['create_time']; ?></td>
                                                    </tr>
                                                    <tr>
                                                        <td class="lession-description lesson-description-correct" style="width: 100%;" colspan="2"><?php echo $item['description']; ?></td>
                                                    </tr>
                                                    <tr>
                                                        <td>
                                                            <img src="<?php echo $this->baseUrl(); ?>/public/images/num-like.png" width="15" height="15"> <font class="num-like-comment"><?php echo $item['like']; ?></font>
                                                            <img src="<?php echo $this->baseUrl(); ?>/public/images/num-view.png" width="15" height="15"> <font class="num-like-comment"><?php echo $item['view']; ?></font>
                                                            <a href="<?php echo $this->baseUrl(); ?>/admin/lesson/lesson?do=view&lessonId=<?php echo $item['id']; ?>"  class="link-view-detail float-right">詳細</a>
                                                        </td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                        <?php
                                    } else if ($counter % 2 == 1) {
                                        ?>
                                        <div class="lession-content-right">
                                            <table cellpadding="1" cellspacing="4" border="0" style="width: 100%;margin: 0px auto;">
                                                <tbody>
                                                    <tr>
                                                        <td style="width: 100%;" colspan="2" class="lession-title"><?php echo $item['title']; ?></td>
                                                    </tr>
                                                    <tr><td><hr></td></tr>
                                                    <tr style="width: 100%;">
                                                        <td class="lession-teacher"><b>先生: </b><?php echo $item['name'] ?></td>
                                                        <td class="lession-time"><?php echo $item['create_time']; ?></td>
                                                    </tr>
                                                    <tr class="lession-description lesson-description-correct" style="width: 100%;">
                                                        <td colspan="2"><?php echo $item['description']; ?></td>
                                                    </tr>
                                                    <tr>
                                                        <td>
                                                            <img src="<?php echo $this->baseUrl(); ?>/public/images/num-like.png" width="15" height="15"> <font class="num-like-comment"><?php echo $item['like']; ?></font>
                                                            <img src="<?php echo $this->baseUrl(); ?>/public/images/num-view.png" width="15" height="15"> <font class="num-like-comment"><?php echo $item['view']; ?></font>
                                                            <a href="<?php echo $this->baseUrl(); ?>/admin/lesson/lesson?do=view&lessonId=<?php echo $item['id']; ?>"  class="link-view-detail float-right">詳細</a>
                                                        </td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                    <?php
                                }
                                $counter ++;
                                ?>

                                <?php
                            }
                            if ($counter % 2 == 0) {
                                echo "</div>";
                            }
                            ?>
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="paging">
                <div class="paging-center">
                    <?php
                    if ($this->numpage > 1)
                        echo $this->paginationControl($this->data, 'Sliding', 'pageinator.phtml');
                    ?>
                </div>
            </div>
        </div>
    </div>
</center>