<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/public/css/admin-common-style.css"); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/public/css/ta123_style.css"); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/public/css/ta123_style2.css"); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/public/css/common-style.css"); ?>

<?php $this->headScript()->appendFile($this->baseUrl() . "/public/js/jquery.min.js"); ?>

<style type="text/css">
    #lesson_container {
        width: 800px;
        margin: 20px auto;
        margin-top: 0px;
        padding: 10px;
        border: 1px solid yellowgreen;
        border-radius: 5px;
    }
    #lesson_container .title {
        font-weight: bold;
        margin-bottom: 20px;
    }
    #lesson_container .tag_label {
        font-weight: bold;
    }
    #lesson_container .tags span {
        padding: 5px;
        margin-right: 10px;
        border-radius: 5px;
        background-color: green;
        color: white;
        font-size: 14px;
    }
    #lesson_container .created_date {
        margin-top: 5px;
        margin-bottom: 5px;
        font-size: 14px;
        color: gray;
    }
    #lesson_container .description {
        width: 500px;
        float: right;
        border: 1px solid yellowgreen;
        padding: 5px;
        height: 180px;
        margin-bottom: 10px;
        margin-left: 10px;
    }
    .message {
        width: 100%;
    }
    .file_container {
        border-top: 1px solid gray;
        cursor: pointer;
    }
    .file_container:hover {
        background-color: gainsboro;
    }
    .file_type {
        width: 50px;
        height: 50px;
        float: left;
    }
    .file_name_label {
        width: 240px;
        float: left;
        font-size: 14px;
        font-weight: bold;
        color: gray;
        margin-bottom: 5px;
        padding: 10px 5px;
        background-color: lightgray;
    }
    .file_description_label {
        width: 540px;
        float: left;
        padding: 10px 5px;
        font-size: 14px;
        font-weight: bold;
        color: gray;
        margin-bottom: 5px;
        background-color: lightgray;
    }
    .file_type img {
        width: 40px;
        height: 40px;
        margin: 5px;
    }
    .file_name {
        overflow: auto;
        line-height: 50px;
        width: 200px;
        height: 50px;
        float: left;
    }
    .file_description {
        line-height: 50px;
        overflow: hidden;
        width: 440px;
        height: 50px;
        float: left;
    }
    .file_report {
        line-height: 50px;
        overflow: hidden;
        width: 30px;
        height: 40px;
        float: left;
        padding-top: 10px;
    }
    .file_report img {
        width: 30px;
        height: 30px;
    }
    .file_lock {
        line-height: 50px;
        overflow: hidden;
        width: 50px;
        height: 40px;
        float: left;
        padding-top: 10px;
    }
    .file_lock img {
        width: 30px;
        height: 30px;
    }
    .btn-delete {
        line-height: 50px;
        width: 50px;
        height: 50px;
        color: orange;
        cursor: pointer;
    }
    .btn-delete:hover {
        color: white;
    }
    .comment_container {
        width: 600px;
        margin: 0px auto;
        padding: 10px;
    }
    .comment_slot {
        margin: 10px 0px;
        padding: 5px;
        border: 1px solid yellowgreen;
    }
    .comment_owner {
        font-weight: bold;
        font-size: 16px;
        color: #2793e6;
    }
    .comment_input textarea {
        width: 100%;
        height: 80px;
    }
    .created_time {
        color: gray;
        font-size: 14px;
        font-style: italic;
        margin-left: 30px;
    }
    .comment_content {
        margin-left: 30px;
    }
    .btn-inactive {
        color: gray;
    }
    .btn-inactive:hover {
        color: gray;
    }
    .report {
        font-size: 14px;
        float: left;
        width: 100%;
        margin: 10px 0px;
    }
    .report-form {
        width: 600px;
        /*margin: 0px auto;*/
        /*padding-bottom: 20px;*/
        /*float: right;*/
    }
    .report-form {
        display: none;
    }
    .report-icon img {
        width: 30px;
        height: 30px;
    }
    .report-icon {
        width: 40px;
        float: left;
    }
    .report-button {
        font-weight: bold;
        text-decoration: underline;
        cursor: pointer;
        /*margin-bottom: 5px*/
    }
    .report-form textarea {
        width: 100%;
        height: 80px;
        margin-bottom: 5px;
        margin-top: 5px;
    }
    .lesson_title {
        margin-bottom: 10px;
        background-color: green;
        color: white;
        padding: 5px;
        margin-top: -10px;
        margin-left: -10px;
        width: 810px;
        border-radius: 3px 3px 0px 0px;
    }
    .like-container {
        background-color: lightgray;
        margin: 10px 0px;
        padding: 5px 0px;
        float: left;
        border-top: 1px solid yellowgreen;
        border-bottom: 1px solid yellowgreen;
    }
    .like-container img {
        width: 20px;
        height: 20px;
        padding-left: 8px;
    }
    .report-status img {
        width: 20px;
        height: 20px;
    }
</style>
<script type="text/javascript">
    $(document).ready(function(){
        $(".unlock-btn").click(function(){
            if (confirm("この授業を本当にアンロックしたいですか？")) {
                window.top.location = "<?php echo $this->baseUrl()."/admin/lesson/unlock?lesson_id=".$this->lessonInfo['id']; ?>";
            }
        });
        $(".lock-btn").click(function(){
            if (confirm("この授業を本当にロックしたいですか？")) {
                window.top.location = "<?php echo $this->baseUrl()."/admin/lesson/lock?lesson_id=".$this->lessonInfo['id']; ?>";
            }
        });
        $(".btn-report").click(function(){
        
            function renderReport(reason, username) {
                
            }
            
            var reason = $(".report-input").val();
            
            if (reason == "") {
                alert("違犯勧告を入力してください");
            } else {
                $.ajax({
                    type: "POST",
                    url: "<?php echo $this->baseUrl(); ?>/api/admin-report-lesson",
                    data: {
                        'reason': reason, 
                        'lesson_id': <?php echo $this->lessonId; ?>
                    }
                }).done(function(data) {
                    console.log(data);
                    if (data.error != undefined) {
                        alert("レポート失敗しました");
                    } else {
                        var username = <?php echo ""; ?>;
                        renderReport($(".report-input").val());
                        $(".report-input").val("");
                        $(".report-num").text(data);
                    }
                });
            }
        });
    });
</script>
<?php echo $this->render('admin-layout.phtml') ?>
<div class="content" style="background: #F0F0F0;">
    <div id="lesson_container">
        <div class="message">
            <?php foreach ($this->messages as $message) { ?>
            <div style="color: green; padding-bottom: 10px;"><?php echo $message; ?></div>
            <?php } ?>
            <?php foreach ($this->errorMessages as $errorMessage) { ?>
            <div style="color: red; padding-bottom: 10px;"><?php echo $errorMessage; ?></div>
            <?php } ?>
        </div>
        <div class="description">
            <?php echo $this->lessonInfo['description']; ?>
        </div>
        <div style="height: 200px;">
            <div class="tag_label">タグ:　</div>
            <div class="tags">
                <?php foreach ($this->tags as $tag) {
                    echo "<div style='margin: 15px;'><span>".$tag['tag_name']."</span></div>";
                }
                ?>
            </div>
            <div class="created_date">
                <?php
                    $time = $this->lessonInfo['create_time'];
                    $correct = explode(" ", $time);
                    $correct = $correct[0];
                    $arr = explode("-", $correct);
                    $year = $arr[0];
                    $mon = $arr[1];
                    $day = $arr[2];
                    echo $year . "年" . $mon . "月" . $day . "日";
                ?>
            </div>
            <div class="like" style="width: 100%; margin: 10px 0px;">
                <span>
                    <img src="<?php echo $this->baseUrl(); ?>/public/images/num-like.png" width="15" height="15">
                    <span><?php echo $this->lessonInfo['num_like'] ?></span>
                </span>
                <span>
                    <img src="<?php echo $this->baseUrl(); ?>/public/images/num-view.png" width="15" height="15">
                    <span><?php echo $this->lessonInfo['view'] ?></span>
                </span>
                <span>
                    <img src="<?php echo $this->baseUrl(); ?>/public/images/student.png" width="15" height="15">
                    <span><?php echo $this->lessonInfo['students_num'] ?></span>
                </span>
                <?php if ($this->lessonInfo['is_reported']) { ?>
                <span>
                    <img src="<?php echo $this->baseUrl(); ?>/public/images/copyright_report.png" width="20" height="20">
                </span>
                <?php } ?>
                <?php if ($this->lessonInfo['status'] == 0) { ?>
                <?php // if (FALSE) { ?>
                    <div style="float:right;">
                        <img src="<?php echo $this->baseUrl(); ?>/public/images/locked.png" width="20" height="20">
                        <span style="color: red">この授業はロックされている</span>
                        <button class="normal-button unlock-btn">アンロック</button>
                    </div>
                <?php } else { ?>
                    <div style="float:right;">
                        <img src="<?php echo $this->baseUrl(); ?>/public/images/unlock.png" width="20" height="20">
                        <button class="normal-button lock-btn">ロック</button>
                    </div>
                <?php } ?>
            </div>
        </div>
        <div>
            <div>
                <div class="file_name_label">ファイル名</div>
                <div class="file_description_label">説明</div>
            </div>
            <div style="width: 100%; line-height: 3px;">&nbsp;</div>
            <?php 
                foreach ($this->files as $file) {
                    $fileTypes = explode(".", $file['filename']);
                                            
                    $fileType = strtolower($fileTypes[count($fileTypes)-1]);
                    if ($fileType == 'pdf') {
                        $icon = $this->baseUrl()."/public/images/pdf.png";
                    } else if ($fileType == 'jpg' || $fileType == 'png' || $fileType == 'gif') {
                        $icon = $this->baseUrl()."/public/images/image.png";
                    } else if ($fileType == 'mp3' || $fileType == 'wav') {
                        $icon = $this->baseUrl()."/public/images/audio.png";
                    } else if ($fileType == 'mp4') {
                        $icon = $this->baseUrl()."/public/images/mp4.png";
                    } else if ($fileType == 'tsv') {
                        $icon = $this->baseUrl()."/public/images/test.png";
                    }
            ?>
            <div class="file_container">
                <a href="<?php echo $this->baseUrl()."/admin/lesson/file?file_id=".$file['id']."&lesson_id=" . $this->lessonId; ?>">
                    <div class="file_type"><img src="<?php echo $icon ?>"></div>
                    <div class="file_name"><?php echo $file['filename']; ?></div>
                    <div class="file_description"><?php echo $file['description'] ?></div>
                    <?php if ($file['is_reported']) { ?>
                        <div class="copyright"><img src="<?php echo $this->baseUrl()."/public/images/copyright_report.png" ?>"></div>
                    <?php } ?>
                </a>
                <div class="btn-delete"></div>
            </div>
            <?php
                }
            ?>
        </div>
        <hr class="clear">
    </div>
    
    <!--レポート-->
    <div class="comment_container">
        <hr class="clear">
        <div class="report-status">
            <img src="<?php echo $this->baseUrl()."/public/images/lesson_report.png"; ?>">
            <span class="report-num"><?php
                echo count($this->reports);
            ?>レポート</span>
        </div>
        <?php
            foreach ($this->reports as $report) {
        ?>
        <div class="comment_slot">
            <div class="comment_owner"><?php echo $report['username']; ?></div>
            <div class="comment_content"><?php echo $report['reason']; ?></div>
            <div class="delete-report-btn">
                <a href="#">削除</a>
            </div>
        </div>
        <?php } ?>
        
        <div class="comment_input" >
            <textarea name="comment" class="report-input"></textarea>
        </div>
        <input type="submit" value="違犯勧告を送る" class="normal-button btn-report">
    </div>
    
    <!--コメント-->
    <form method="post" class="comment_container">
        <hr class="clear">
        <div>コメント:</div>
        <?php
            foreach ($this->comments as $comment) {
        ?>
        <div class="comment_slot">
            <div class="comment_owner"><?php echo $comment['name']; ?></div>
            <div class="comment_content"><?php echo $comment['comment']; ?></div>
            <div class="created_time"><?php echo $comment['time']; ?></div>
        </div>
        <?php
            }
        ?>
        <!--
        <div class="comment_input" >
            <textarea name="comment" class="comment-input"></textarea>
        </div>
        <input type="submit" value="コメント" class="normal-button btn-comment">
        -->
    </form>
</div>
