
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/public/css/admin-login-style.css"); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/public/css/admin-login-style-2.css"); ?>
<div align="center" style="margin-top: 50px;">
    <font size="+3"><big>Elearningシステムへようこそ</big> </font>
</div>
<center>
    <div class="ac_box" align="center">
        <div class="res_box">
            <div class="yellow_title_box">
                <div class="yellow_title_left">管理者ログイン</div>
            </div>
        </div>
        <form action="<?php echo $this->form->getAction(); ?>"
              method="<?php echo $this->form->getMethod(); ?>">
            <div class="row-input">
                <div class="title-lgu">ユーザ名:</div>
                <div class="input-lg">
                    <?php echo $this->form->username; ?>
                </div>
            </div>
            <div class="row-input">
                <div class="title-lgp">パースワード:</div>
                <div class="input-lg">
                    <?php echo $this->form->password; ?>
                </div>
            </div>
            <div class="row-input">
                <div style="color: red"><?php echo $this->errorMessage; ?></div>
            </div>
            <div class="row-input" style="margin-top: 10px; margin-left: 250px;"
                 align="center">
                <dt id="submit-label">&nbsp;</dt>
                <dd id="submit-element">
                    <input class="showlogfromm" tabindex="5" type="submit" value="ログイン"/>
                </dd>
                <?php // echo $this->element->submit; ?>
            </div>
        </form>
    </div>
</center>