
<!DOCTYPE html>
<html>
    <body>
    <center>
        <div class="content">
            <div class="top_content clear banner">
                <!--                <div class="logo" style="float: left;">
                                    <a href="#"> <img width="230" height="58" src="#" alt="Logo">
                                    </a>
                                </div>-->
                <div align="right" style="float: right; margin-top: 20px;">
                    <a href="../user/logout"><button class="register-cus">ログアウト</button>
                    </a>
                </div>
            </div>
            <!--Menu Tab Bar-->
            <div class="menus clear">
                <a href="" class="home"></a>
                <div title="" class="mn first_mn"><a href="#"><font style="color: white;">マイ授業</font></a>
                </div>
                <div class="mn" title=""><a href="#"><font style="color: white;">授業リスト</font></a>
                </div>
                <div title="" class="mn "><a href="#"><font style="color: white;">支払い</a>
                </div>
                <div title="" class="mn "><a href="javascript:;"><font style="color: white;">プロファイル</font></a>
                </div>
            </div>
            <!--Function tab bar-->
            <div class="row-show">
                <button style="margin-top: 10px;"  name="btn_tag" class="showlogfromm float-left">タグ</button>
                <button style="margin-left: 10px; margin-top: 10px;" name="btn_teacher" class="register-cus float-left">先生</button>
                <div  style="margin-top: 10px;" class="float-right">
                    <form action="#" style="height: 30px;">
                        <input type="text" name="q" class="input_search" placeholder="検索内容"/>
                        <input  name="sa" style="width: 34px; height: 34px;" type="image" src="../public/images/bg_search_right.jpg">
                    </form>
                </div>
            </div>
            <!--Content continue-->
        </div>
    </center>
</body>
</html>
