<?php if ($this->pageCount): ?>
    <?php
    if (isset($this->previous)) {
        ?>
        <div class="paging-next-prev">
            <a href="<?php $this->url(array('page' => $this->previous)); ?>">前</a> 
        </div>
        <?php
    }
    foreach ($this->pagesInRange as $page) {
        if ($page != $this->current) {
            ?>
            <a href="<?php echo $this->url(array('page' => $page)) ?>">
                <div class="paging-item"><?php echo $page ?></div>
            </a>
            <?php
        } else {
            ?>
            <a href="">
                <div class="paging-item-curr"><?php echo $page; ?>
                </div>
            </a>
            <?php
        }
    }
    if (isset($this->next)) {
        ?>
        <div class="paging-next-prev">
            <a href="<?php echo $this->url(array('page' => $this->next)); ?>">次</a>
        </div>     
        <?php
    }
    ?>
<?php endif; ?>