<center>
    <div class="content">
        <form action="<?php echo $this->element->getAction(); ?>"
              method="<?php echo $this->element->getMethod(); ?>">
            <div class="resg_box">
                <div class="yellow_title_box">
                    <div class="yellow_title_left">メンバーを登録フォーム</div>
                    <div class="yellow_title_right"></div>
                </div>
                <div class="yellow_title_bottom"></div>
                <div class="res_step_title">
                    <div class="res_step_t_num res_num1">アカウント情報</div>
                    <div class="res_step_t_r"></div>
                </div>
                <div class="res_notes">
                    <span class="red"> （*） </span>があるというのは必要なフィールド
                </div>
                <script type="text/javascript">
                    function student() {
                        $("#secret_qa").hide();
                    }

                    function teacher() {
                        $("#secret_qa").show();
                    }
                </script>
                <!--ユーザルール-->
                <div class="res_form_row">
                    <input type="radio" name="role" checked="checked" value="1" onclick="javascript:student()"><b>学生</b> <input
                        type="radio" name="role" value="2" onclick="javascript:teacher()"><b>先生</b>
                </div>

                <div class="res_form_row">
                    <div class="res_f_r_left">
                        <div class="res_f_r_left_up">
                            <b>ユーザ名</b>（6字以上）: <span class="red">*</span>
                        </div>
                        <div class="res_f_r_left_down">ユーザ名は「A-Z, a-z, 0-9, -, _ 」以外があ
                            りますかどうかチェックします。</div>
                    </div>
                    <div class="res_f_r_right">
                        <?php echo $this->element->username; ?>
                        <div id="er_username" class="res_f_note"></div>
                    </div>
                </div>
                <div class="res_form_row">
                    <div class="res_f_r_left">
                        <div class="res_f_r_left_up">
                            <b>パースワード </b>（６字以上）：<span class="red">*</span>
                        </div>
                        <div class="res_f_r_left_down">パースワードは「A-Z, a-z, 0-9, -, _ 」以外があ りますかどうかチェックします</div>
                    </div>
                    <div class="res_f_r_right">
                        <?php echo $this->element->password; ?>
                    </div>
                </div>
                <div class="res_form_row">
                    <div class="res_f_r_left">
                        <div class="res_f_r_left_up">
                            <b>パースワードを確認 </b>: <span class="red">*</span>
                        </div>
                        <div class="res_f_r_left_down">パースワードをも一度お願い</div>
                    </div>
                    <div class="res_f_r_right">
                        <?php echo $this->element->repassword; ?>
                        <div id="er_password" class="res_f_note"></div>
                    </div>
                </div>
                <div class="res_form_row">
                    <div class="res_f_r_left">
                        <div class="res_f_r_left_up">
                            <b>イーメール</b>:
                        </div>
                        <div class="res_f_r_left_down">あなたのイーメールを入力してください</div>
                    </div>
                    <div class="res_f_r_right">
                        <?php echo $this->element->email; ?>
                        <div id="er_email" class="res_f_note"></div>
                    </div>
                </div>
                <div class="res_step_title">
                    <div class="res_step_t_num res_num2">個人情報</div>
                    <div class="res_step_t_r"></div>
                </div>
                <div class="res_form_row">
                    <div class="res_f_r_left">
                        <div class="res_f_r_left_up">名前:</div>
                    </div>
                    <div class="res_f_r_right">
                        <?php echo $this->element->fullname; ?>
                        <div id="er_hoten" class="res_f_note"></div>
                    </div>
                    <div>
                        <div class="res_radio_box">
                            <input id="sex" name="sex" type="radio" " value="0"
                                   checked="checked">男 <input id="sex" name="sex" type="radio"
                                   value="1">女
                        </div>
                    </div>
                </div>
                <div class="res_form_row">
                    <div class="res_f_r_left">
                        <div class="res_f_r_left_up">生年月日：</div>
                    </div>
                    <div class="res_f_r_right">
                        <div class="res_select">
                            <label> <select id="day" name="day">
                                    <option value="0">---</option>

                                    <option value="1">1</option>

                                    <option value="2">2</option>

                                    <option value="3">3</option>

                                    <option value="4">4</option>

                                    <option value="5">5</option>

                                    <option value="6">6</option>

                                    <option value="7">7</option>

                                    <option value="8">8</option>

                                    <option value="9">9</option>

                                    <option value="10">10</option>

                                    <option value="11">11</option>

                                    <option value="12">12</option>

                                    <option value="13">13</option>

                                    <option value="14">14</option>

                                    <option value="15">15</option>

                                    <option value="16">16</option>

                                    <option value="17">17</option>

                                    <option value="18">18</option>

                                    <option value="19">19</option>

                                    <option value="20">20</option>

                                    <option value="21">21</option>

                                    <option value="22">22</option>

                                    <option value="23">23</option>

                                    <option value="24">24</option>

                                    <option value="25">25</option>

                                    <option value="26">26</option>

                                    <option value="27">27</option>

                                    <option value="28">28</option>

                                    <option value="29">29</option>

                                    <option value="30">30</option>

                                    <option value="31">31</option>

                                </select>
                            </label>​
                        </div>
                        <div class="res_select">
                            <label> <select id="mon" name="month">
                                    <option value="0">-------</option>

                                    <option value="1">1月</option>

                                    <option value="2">2月</option>

                                    <option value="3">3月</option>

                                    <option value="4">4月</option>

                                    <option value="5">5月</option>

                                    <option value="6">6月</option>

                                    <option value="7">7月</option>

                                    <option value="8">8月</option>

                                    <option value="9">9月</option>

                                    <option value="10">10月</option>

                                    <option value="11">11月</option>

                                    <option value="12">12月</option>

                                </select>
                            </label>​
                        </div>
                        <div class="res_select res_select_last">
                            <label> 
                                <select id="year" name="year">
                                    <option value="0">-----</option>

                                    <option value="2013">2013</option>

                                    <option value="2012">2012</option>

                                    <option value="2011">2011</option>

                                    <option value="2010">2010</option>

                                    <option value="2009">2009</option>

                                    <option value="2008">2008</option>

                                    <option value="2007">2007</option>

                                    <option value="2006">2006</option>

                                    <option value="2005">2005</option>

                                    <option value="2004">2004</option>

                                    <option value="2003">2003</option>

                                    <option value="2002">2002</option>

                                    <option value="2001">2001</option>

                                    <option value="2000">2000</option>

                                    <option value="1999">1999</option>

                                    <option value="1998">1998</option>

                                    <option value="1997">1997</option>

                                    <option value="1996">1996</option>

                                    <option value="1995">1995</option>

                                    <option value="1994">1994</option>

                                    <option value="1993">1993</option>

                                    <option value="1992">1992</option>

                                    <option value="1991">1991</option>

                                    <option value="1990">1990</option>

                                    <option value="1989">1989</option>

                                    <option value="1988">1988</option>

                                    <option value="1987">1987</option>

                                    <option value="1986">1986</option>

                                    <option value="1985">1985</option>

                                    <option value="1984">1984</option>

                                    <option value="1983">1983</option>

                                    <option value="1982">1982</option>

                                    <option value="1981">1981</option>

                                    <option value="1980">1980</option>

                                    <option value="1979">1979</option>

                                    <option value="1978">1978</option>

                                    <option value="1977">1977</option>

                                    <option value="1976">1976</option>

                                    <option value="1975">1975</option>

                                    <option value="1974">1974</option>

                                    <option value="1973">1973</option>

                                    <option value="1972">1972</option>

                                    <option value="1971">1971</option>

                                    <option value="1970">1970</option>

                                    <option value="1969">1969</option>

                                    <option value="1968">1968</option>

                                    <option value="1967">1967</option>

                                    <option value="1966">1966</option>

                                    <option value="1965">1965</option>

                                    <option value="1964">1964</option>

                                    <option value="1963">1963</option>

                                    <option value="1962">1962</option>

                                    <option value="1961">1961</option>

                                    <option value="1960">1960</option>

                                    <option value="1959">1959</option>

                                    <option value="1958">1958</option>

                                    <option value="1957">1957</option>

                                    <option value="1956">1956</option>

                                    <option value="1955">1955</option>

                                    <option value="1954">1954</option>

                                    <option value="1953">1953</option>

                                    <option value="1952">1952</option>

                                    <option value="1951">1951</option>

                                    <option value="1950">1950</option>
                                </select>
                            </label>​
                        </div>
                    </div>
                </div>
                <div class="res_form_row">
                    <div class="res_f_r_left">
                        <div class="res_f_r_left_up">住所:</div>
                    </div>
                    <div class="res_f_r_right">
                        <input id="res_address" name="address" class="res_input"
                               type="text">
                    </div>
                </div>
                <div class="res_form_row">
                    <div class="res_f_r_left">
                        <div class="res_f_r_left_up">電話番後:</div>
                    </div>
                    <div class="res_f_r_right">
                        <input id="res_phone_number" name="phone" class="res_input"
                               type="text">
                    </div>
                </div>

                <div class="res_form_row">
                    <div class="res_f_r_left">
                        <div class="res_f_r_left_up">銀後アカウント:</div>
                    </div>
                    <div class="res_f_r_right">
                        <input id="res_bank_account" name="bank_acc" class="res_input"
                               type="text">
                    </div>
                </div>
                <div id="secret_qa">
                    <div class="res_form_row" >
                        <div class="res_f_r_left">
                            <div class="res_f_r_left_up">機密質問:</div>
                        </div>
                        <div class="res_f_r_right">
                            <input id="res_secret_question_q" class="res_input"
                                   name="secret_question" type="text">
                        </div>
                    </div>

                    <div class="res_form_row">
                        <div class="res_f_r_left">
                            <div class="res_f_r_left_up">答え:</div>
                        </div>
                        <div class="res_f_r_right">
                            <input id="res_secret_question_a" class="res_input"
                                   name="secret_answer" type="text">
                        </div>
                    </div>
                </div>


                <div class="res_step_title">
                    <div class="res_step_t_num res_num3">使用規制</div>
                    <div class="res_step_t_r"></div>
                </div>
                <div class="res_form_row">
                    <div class="res_radio_box">
                        <div class="res_radio_te">
                            <input type="checkbox" checked="checked" disabled name="rule_accept"><span
                                class="font_weight">私は<a href="#" target="_blank" class="blue2">Elearningシステムの使用規制</a>が納得しました<span
                                    class="red">*</span>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="res_form_row" style="margin-left:250px; margin-bottom: 40px;">
                    <?php echo $this->element->submit; ?>
                    <a href="login"><input type="button" class="register-cus float-left"
                                           value="キャンセル"> </a>
                </div>
            </div>
        </form>
    </div>
</center>
