<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/public/css/admin-common-style.css"); ?>
<div class="bg_top" style="height: 200px">&nbsp;</div>
<div class="bg_center">
    <div id="contents">
        <div class="top_content clear">
            <div class="logo">
                <a href="#"> <img width="600" height="80" src="/Elearning/public/images/T08-banner.png" alt="Logo">
                </a>
            </div>
            <div align="right" style="float: right; margin-top: 20px;">
                <a href="../user/logout"><button class="register-cus">ログアウト</button>
                </a>
            </div>
        </div>
        <div class="menus clear">
            <ul>
                <li class="home mn"><a href="#"></a>
                </li>
                <li title="" class="mn"><a href="#">マイ授業</a>
                </li>
                <li class="mn" title=""><a href="#">授業リスト</a>
                </li>
                <li title="" class="mn "><a href="#">課金情報</a>
                </li>
                <li title="" class="mn "><a href="javascript:;">プロファイル</a>
                </li>
            </ul>
        </div>
    </div>
</div>