<center>
    <div class="content">
        <div align="center" style="margin-top: 50px;">
            <font size="+3"><big>Elearningシステムへようこそ</big> </font>
        </div>
        <center>
            <div class="ac_box" align="center">
                <div class="res_box">
                    <div class="yellow_title_box">
                        <div class="yellow_title_left">秘密質問確認</div>
                    </div>
                </div>
                <form action=""
                      method="post">
                    <div class="res_form_row">
                        <div class="res_f_r_left">
                            <div class="res_f_r_left_up">秘密質問:</div>
                        </div>
                        <div class="res_f_r_right">
                            <?php echo Default_Model_Account::decryptIt($this->uInfo["secret_question"])?>
                        </div>
                    </div>

                    <div class="res_form_row">
                        <div class="res_f_r_left">
                            <div class="res_f_r_left_up">答え:</div>
                        </div>
                        <div class="res_f_r_right">
                            <input id="res_secret_question_a" class="res_input"
                                   name="secret_answer" type="text">
                        </div>
                    </div>
                    <div class="res_form_row">
                        <?php
                        if (isset($this->errorMessage)) {
                            echo $this->errorMessage;
                        }
                        ?>
                    </div>
                    <div class="row-input" style="margin-top: 10px; margin-left: 250px;"
                         align="center">
                        <input type="submit"
                               class="showlogfromm float-left" value="確認"> </a>
                        <a href="login"><input type="button" 
                                               class="register-cus float-left" value="キャンセル"> </a>
                    </div>
                </form>
            </div>
        </center>
    </div>
</center>