<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
</head>
<body>


<div class="bg_top">&nbsp;</div>
<div class="bg_center">
<div id="contents">
<div class="top_content clear">
<div class="logo"><a href="#"> <img width="230"
	height="58" src="<?php echo $this->baseUrl().'/public/images/elearning-logo.png';  ?>"
	alt="Logo"> </a></div>
<div class="action">

<ul class="first_notLogin">
	<li class="reg_card">
	<div id="hover_boxdt">
	<div class="box_dt_fast">
	<div class="box_dt_ar"></div>
	</div>
	</div>
	</li>
	<li class="ac_log">
	<div><a href="/index/login" class="showlogfromm">ログイン</a>
	<a href="<?=$this->url(array( 'controller' => 'register' , 'action' => 'index' ))?>" class="register-cus">登録</a></div>
	</li>
</ul>

</div>
</div>
</div>
</div>
</body>
</html>
