<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
</head>
<body>
<div class="bg_center">
<div class="logo"><a href="#"> <img width="230" height="58"
	src="/Elearning/public/images/elearning-logo.png" alt="Logo"> </a></div>
<div class="res_box">
<div class="yellow_title_box">
<div class="yellow_title_left">ユーザログイン</div>
</div>
<div class="yellow_title_bottom"></div>
<div class="row-input"><?php echo $this->element->getMethod();?>
<form action="<?php echo $this->element->getAction();?>" method="post">
<div class="title-lgu">ユーザ名:</div>

</form>
<div class="input-lg"><input tabindex="1" type="text"
	id="clogin_username" name="txtUsername" value=""></div>
<a href="#" class="link-rf" title="アカウントを作る?">アカウントを作る?</a></div>
<div class="row-input">
<div class="title-lgp">パースワード:</div>
<div class="input-lg"><input tabindex="2" type="password"
	id="clogin_password" name="txtUsername" value=""></div>
<a href="#" class="link-rf" title="パースワードを忘れる??">パースワードを忘れる?</a></div>
<div class="row-input" style="display: none;" id="clogin_mess">
<div id="mss_login" class="res_f_note res_false" style="display: block;"></div>
</div>
<div class="row-input">
<ul>
	<li tabindex="3" id="clogin_repass" class="repass checkRePass"
		alt="false">私を覚えている</li>
</ul>
<ul class="first_notLogin">
	<li class="ac_log">
	<div><a href="#" class="showlogfromm">ログイン</a> <a href="#"
		class="register-cus">登録</a></div>
	</li>
</ul>
</div>
</div>
</div>
</body>
</html>
